package me.localx.icons.rounded

import androidx.compose.ui.graphics.vector.ImageVector
import me.localx.icons.rounded.bold.*
import kotlin.collections.List as ____KtList

private var __Bold: ____KtList<ImageVector>? = null

public val Icons.Bold.allIconsList: ____KtList<ImageVector>
  get() {
    if (__Bold != null) {
      return __Bold!!
    }
    __Bold = listOf(Search, Check, MenuBurger, Cross, Plus, Home, Envelope, AngleLeft, User,
        AngleRight, Refresh, Exit, PhoneCall, Picture, Download, Heart, ShoppingCart, List, World,
        CrossSmall, Power, MenuDotsVertical, Play, Minus, Star, LinkAlt, ListCheck, Marker,
        Checkbox, Trash, Bookmark, RotateRight, Add, Globe, ArrowRight, AngleDown, Stats, PlusSmall,
        ChartHistogram, Calendar, UsersAlt, Info, SettingsSliders, Dollar, TimePast, Portrait,
        SignOutAlt, AngleSmallRight, Edit, Running, Apps, At, PlayAlt, Eye, Lock, Exclamation,
        CrossCircle, AngleSmallDown, CommentAlt, ArrowSmallLeft, MenuDots, Smartphone, ArrowLeft,
        Users, PaperPlane, ShoppingBag, ChatArrowGrow, Comment, Question, Grid, AlarmClock, Camera,
        Sun, MinusSmall, Pencil, X, Link, ArrowSmallRight, Bell, Wallet, Interrogation,
        SocialNetwork, ChartLineUp, Shuffle, AngleDoubleRight, UserAdd, GraduationCap,
        CalendarClock, CaretDown, Ban, BookAlt, Percentage, Expand, Clock, Document, SignInAlt,
        Euro, Enter, AlignJustify, ShoppingCartAdd, SearchAlt, ShieldCheck, AngleSmallLeft, Loading,
        AngleUp, Filter, Settings, Copy, Share, AngleDoubleLeft, Briefcase, Computer,
        VideoCameraAlt, TimeFast, Upload, CalendarLines, Crown, ArrowsRepeat, Megaphone, BadgeCheck,
        CommentAltMiddle, Leaf, AddressBook, Bank, Browser, EyeCrossed, CreditCard, RotateLeft,
        ClockThree, HourglassEnd, Bulb, Hastag, Bullseye, TimeCheck, AngleDoubleSmallRight,
        BellRing, Comments, ModePortrait, AppsAdd, WifiAlt, CommentHeart, Microphone, Clip,
        Football, AsseptDocument, MapMarkerHome, Unlock, ZoomIn, MapMarker, Scissors, QuoteRight,
        EditAlt, AddDocument, Volume, MobileNotch, Calculator, Doctor, Recycle, Layers, MusicAlt,
        ArrowAltRight, FolderDownload, Shop, Ballot, Square, Film, Disk, CommentUser, SignalAlt2,
        Flame, FlagAlt, PlayPause, Stethoscope, Screen, CirclePhone, LayoutFluid, SearchHeart,
        IdBadge, CaretRight, CirclePhoneFlip, ArrowUpRight, CursorFinger, AngleDoubleSmallLeft,
        Female, A, Following, RocketLunch, Moon, ArrowUpRightFromSquare, AngleSmallUp,
        TimeTwentyFour, UndoAlt, TimeForward, CalendarCheck, SackDollar, Building, UsdCircle, Coins,
        ArrowUpRightAndArrowDownLeftFromCenter, HomeLocationAlt, Exchange, SteeringWheel,
        ShoppingBagAdd, Male, Folder, Trophy, Spinner, Italic, Form, ChevronDoubleDown,
        CloudDownloadAlt, BookBookmark, Fingerprint, SortAlt, SortAmountDownAlt, CalendarLinesPen,
        AlignLeft, Key, Notebook, Underline, ArrowSmallUp, Bug, TimeQuarterTo, Palette,
        EnvelopeOpen, AlignCenter, CompressAlt, ChartPieAlt, ChevronDoubleUp, Wheelchair,
        CircleSmall, File, LayerPlus, Pulse, TruckSide, ArrowFromBottom, Restaurant, InboxIn,
        ArrowCircleRight, DraftingCompass, Fill, VideoCamera, QuestionSquare, Database, Flag,
        ChildHead, CopyAlt, Symbol, Physics, Delete, Print, Compress, Map, GameBoardAlt,
        AngleDoubleSmallDown, BoxCheck, Circle, Wind, B, Headphones, Gift, MoonStars, FolderUpload,
        BookOpenCover, RemoveUser, LifeRing, CalendarMinus, RoomService, ChartNetwork, StoreAlt,
        DeleteUser, ClockFive, T, TimeDelete, CaretUp, P, PencilRuler, CakeBirthday, DiceD6,
        Handshake, TimeAdd, ChatArrowDown, ArrowAltCircleRight, CalendarPlus, PaintRoller,
        Dashboard, BoxAlt, AppsDelete, Donate, Car, Stars, ExpandArrows, SensorFire, TestTube,
        Interactive, GlassCheers, DiceThree, HouseFlood, ChartTree, AngleCircleUp, Biking,
        LinkSlashAlt, CommentCode, Subway, SortAmountUpAlt, F, ClipboardList, ELearning, Umbrella,
        Rocket, BarberShop, Interlining, Mountains, Confetti, Water, LineWidth, Tooth, Subtitles,
        Tablet, Shield, MugHot, N, ArrowUpToDottedLine, DeleteDocument, Laptop, Keyboard,
        EnvelopePlus, Navigation, BikingMountain, ChargingStation, ClockTwo, M, MindShare,
        MoneyCheck, SignalAlt, ArrowCircleLeft, ArrowSquareRight, ExpandArrowsAlt, DiceAlt,
        CommentQuote, Dice, Yen, Grill, CloudSun, Eclipse, Humidity, ArrowAltSquareRight,
        FileSpreadsheet, Folders, G, HandHoldingBox, _1, RectangleHorizontal, SadTear,
        ArrowAltCircleLeft, ArrowAltFromLeft, SortAmountUp, PiggyBank, I, RulerCombined, Stopwatch,
        Drumstick, Hamburger, Wheat, ArrowAltCircleDown, CommentXmark, ArrowsCross, Treatment,
        Duplicate, MicrophoneAlt, Fork, Cars, TachometerFast, ChartScatter, D, CommentDollar,
        CommentsQuestionCheck, Cream, CursorText, PhonePause, Soup, WomanHead, Pumpkin, CarBuilding,
        L, CashRegister, MoneyBillWave, Sack, SuitcaseAlt, ArrowTrendDown, Square1, Inbox,
        GrinHearts, Strawberry, AngleSquareRight, LevelUp, CloudShowersHeavy, ArrowAltFromRight,
        Ship, CommentCheck, CommentInfo, Undo, TimeQuarterPast, ShoppingCartCheck, HomeLocation,
        BadgePercent, Diploma, Headset, Target, ZoomOut, Bolt, ArrowUpFromSquare, FileInvoiceDollar,
        ArrowSmallDown, ArrowTrendUp, ModeLandscape, Tags, Books, ShieldExclamation, TextCheck,
        Pause, Paw, Care, Stop, CommentQuestion, SensorAlert, Receipt, Bold, MobileButton, Gym,
        ArrowDown, AppsSort, Broom, FileInvoice, MagicWand, Forward, Snowflake, AngleCircleRight,
        Cube, ExchangeAlt, AngleCircleLeft, DocumentSigned, ShoppingBasket, Raindrops, Boxes,
        ClipboardListCheck, ToolCrop, Thumbtack, Couple, Sparkles, SearchLocation, ArrowUpLeft,
        Text, Hiking, AngleDoubleSmallUp, ClockNine, TimeOclock, Earnings, CloudUpload, Badge,
        Diamond, Ticket, CaretLeft, MoneyCheckEdit, Hand, Copyright, TruckMoving,
        ArrowUpLeftFromCircle, GridAlt, SignalAlt1, ArrowUp, Box, Tree, RedoAlt, TruckLoading, S,
        CallHistory, RubleSign, CloudDownload, AddFolder, LockAlt, Cursor, EngineWarning,
        PhoneOffice, Utensils, Swimmer, Infinity, Music, Gallery, DataTransfer, Label, MugHotAlt,
        MarkerTime, Password, Motorcycle, C, Pound, LocationAlt, LevelDown, EclipseAlt, ReplyAll,
        BullseyePointer, AlarmExclamation, Pharmacy, Triangle, Heat, CommentExclamation, VideoPlus,
        CallOutgoing, AppleWhole, ArrowAltDown, E, BedAlt, SquareRoot, LetterCase, CallIncoming,
        CarAlt, FileChartLine, Brush, School, Book, Redo, TruckContainer, ArrowAltUp,
        CommentsQuestion, Hourglass, Resources, Rewind, HeadSideThinking, Bed, Arrows, CalendarPen,
        Q, Camcorder, CarSide, Syringe, RecordVinyl, AngleCircleDown, ArrowAltToRight, InboxOut,
        UserTime, Road, Gamepad, ArrowsH, BusAlt, ArrowAltToTop, ArrowsRepeat1, TimeForwardTen,
        TimeHalfPast, Flower, ManHead, Plane, DownLeftAndUpRightToCenter, BookArrowRight, GiftCard,
        MapMarkerPlus, Gem, Grin, AngleSquareDown, SortAmountDown, FolderMinus, H, CloudShare,
        Transform, CaretCircleRight, ArrowAltLeft, CommentPen, PlayingCards, Glasses, ChartPie,
        Thunderstorm, PlaneAlt, MusicFile, Cloud, EnvelopeDownload, Glass, AngleSquareLeft,
        GasPumpAlt, SortAlphaDown, CalendarExclamation, ChartArea, HandHoldingSeeding, Rec, Sad,
        Equality, BookArrowUp, Comet, O, Presentation, GlobeAlt, Test, HatChef, LevelDownAlt,
        TemperatureHigh, CarMechanic, ClockSeven, FileChartPie, Mailbox, Basketball, Medicine,
        Cookie, FlowerTulip, ChessQueen, Tire, ArrowAltToLeft, Calendars, FolderTree, R, Gifts,
        BowArrow, TreasureChest, Resize, SchoolBus, EnvelopeMarker, MugAlt, Pot, AngleSquareUp,
        BaseballAlt, SunriseAlt, UsdSquare, _3, NetworkCloud, Asterik, Taxi, Camping, KissWinkHeart,
        Pepper, ArrowFromRight, ArrowToRight, DiceOne, Sledding, TireRugged, BalanceScaleLeft,
        FilterSlash, Golf, Spa, Mouse, Butterfly, Happy, DrinkAlt, Mushroom, Sort, ArrowFromTop,
        ArrowToLeft, CloudsSun, AssistiveListeningSystems, Registered, _7, Square2, EyeDropper,
        LuggageRolling, CakeWedding, Candy, Mug, Plate, Tomato, Turkey, HockeyPuck, Luchador,
        SortAlphaUpAlt, ShekelSign, U, BadgeSheriff, Square4, Gif, GasPump, Train, CandyAlt, Onion,
        ArrowToBottom, Smoke, Volcano, ClockFourThirty, Blinds, CommentArrowUpRight, Fox,
        BreadSlice, MaleCouple, MapMarkerMinus, ChartPyramid, HatBirthday, Grimace, GrinBeam,
        CannedFood, CaretSquareLeft1, Skating, CarCrash, ArrowAltSquareLeft, BlindsOpen, Bells,
        Reflect, Dizzy, BowlingBall, ChessRookAlt, PuzzlePiece, Sleigh, TemperatureFrigid,
        TruckMonster, BoxTissue, Circle1, Dart, IceSkate, DiscoBall, GrinTongueSquint, LaughSquint,
        MehRollingEyes, Lettuce, SaltPepper, Skewer, ChessClockAlt, Curling, CloudSleet, CaravanAlt,
        FighterJet, GasPumpSlash, Tram, WagonCovered, ClockSevenThirty, Democrat, BlindsRaised,
        Keynote, BrainCircuit, CodeCommit, CodeSimple, MessageCode, RectangleBarcode,
        SquareTerminal, Circle0, Circle4, Circle6, Circle7, Square6, Square7, BorderBottom,
        BorderCenterV, BorderNone, BorderOuter, CassetteVhs, CircleDashed, CircleHalfStroke,
        ObjectIntersect, ObjectSubtract, TextWidth, BatteryFull, BatteryQuarter,
        BatteryThreeQuarters, DoorClosed, Hammer, HeadVr, LightSwitchOn, LightSwitch, BenchTree,
        BoxFragile, BoxOpenFull, BoxOpen, Fence, FireFlameCurved, HouseTree, IndustryWindows,
        IslandTropical, LuggageCart, MapMarkerCheck, MapMarkerSlash, Monument, Parking, Passport,
        PlaneProp, RampLoading, RouteInterstate, SeatAirline, SignHanging, SquarePlus,
        TrafficLightGo, WineGlassCrack, ArrowDownFromDottedLine, ArrowDownToDottedLine,
        ArrowTurnDownRight, ArrowUpSmallBig, ChartGantt, ChartRadar, ChartScatterBubble,
        DiagramLeanCanvas, DiagramNested, Bone, Tally, Highlighter, CirclePhoneHangup,
        ArrowsFromDottedLine, Snowboarding, Scale, FlipHorizontal, TrainSide, Pyramid, Picnic,
        Sandwich, CaretCircleDown, Skiing, ArrowAltToBottom, BarsProgress, LightbulbDollar, _2,
        PaintBrush, Speaker, Carrot, PizzaSlice, Popcorn, Bahai, Y, RulerTriangle, BellSchool,
        PingPong, Lipstick, Salad, ThermometerHalf, Balloons, Dewpoint, Ad, MoneyCheckEditAlt,
        Rainbow, FlowerBouquet, CarBattery, CommentArrowUp, ArrowUpSquareTriangle, Backpack,
        Ambulance, RectanglePanoramic, Bike, Lemon, Sauce, ArrowCircleUp, RugbyHelmet, Starfighter,
        _4, Volleyball, Egg, DiceFour, CloudRain, WaterRise, ClockTen, BoxBallot, FolderTimes,
        Stamp, Cheese, GingerbreadMan, HamburgerSoda, Spoon, CaretCircleUp, Dreidel, BabyCarriage,
        Hryvnia, SensorSmoke, Circle5, Rugby, MakeupBrush, UsbPendrive, Vector, FileEps, Cocktail,
        ChessBoard, DiceD4, Whistle, TemperatureDown, CarBump, SkiLift, Tractor, ArrowAltCircleUp,
        SortNumericDown, AlarmSnooze, ClockFiveThirty, LayerMinus, PhotoVideo, VideoArrowUpRight,
        _0, _9, Square5, FilePsd, ChartSetTheory, Poo, Broccoli, Cherry, Chocolate, Pineapple,
        Meteor, Snowflakes, ThunderstormSun, GarageCar, OilCan, TachometerSlow, TruckPlow,
        CarCircleBolt, CommentSms, Bowling, MugTea, Watermelon, BowlingPins, ChessKnight, Club,
        DiceD20, HockeyMask, SkiingNordic, CarGarage, Snowmobile, Trailer, ClockEleven,
        ClockOneThirty, CarBolt, Protractor, Skateboard, BandAid, Wink, GrinSquintTears, GrinWink,
        KissBeam, Kiss, SadCry, Radish, ChessKingAlt, ChessPawn, DiceD12, HockeySticks, CloudHail,
        Smog, ThunderstormMoon, TachometerAverage, TachometerSlowest, EnvelopeBulk, BarcodeRead,
        BarcodeScan, Barcode, CodeBranch, CodePullRequestClosed, FileCode, LinkHorizontalSlash,
        TablePivot, Square0, Square8, BookFont, BorderInner, BorderLeft, BorderRight, BorderStyle,
        BringForward, BringFront, CassetteTape, ObjectExclude, ObjectUnion, BatterySlash, HammerWar,
        BookAtlas, BoxUp, Cabin, ConciergeBell, FishingRod, FlagCheckered, Fort, HotTub, HouseBlank,
        HouseChimneyBlank, HouseTurret, LandmarkAlt, MapMarkerQuestion, MapMarkerSmile,
        PeopleCarryBox, PlaneDeparture, PlaneTail, RollerCoaster, ShopLock, StoreLock, TablePicnic,
        TaxiBus, ToiletPaperBlank, TrafficLightStop, TrainTram, TreeDeciduous, UmbrellaBeach, Down,
        BalanceScaleRight, FileVideo, ArrowsToLine, Mobile, RingsWedding, ArrowFromLeft,
        EnvelopeOpenDollar, W, SensorOn, CocktailAlt, ArrowSquareLeft, DiceSix, Garage,
        ArrowAltFromTop, Coin, StarOctogram, Noodles, Steak, Pennant, SkiJump, SnowBlowing, CarWash,
        Chair, ToolBox, PodiumStar, ArrowsFromLine, CursorPlus, Sticker, Archive, Croissant,
        ArrowsAlt, WaterLower, Bus, TachometerFastest, TirePressureWarning, Sensor, CommentImage,
        Sword, CallMissed, ChartConnected, Guitar, SmileBeam, WaterBottle, BasketballHoop, J,
        AirConditioner, ChairOffice, Filters, RulerVertical, FlushedFace, Hotdog, Sausage,
        ChessKing, ChessKnightAlt, Sunset, Windsock, FlagUsa, Z, CommentsDollar, PhotoFilmMusic,
        CrystalBall, Lasso, AstonishedFace, CoffeePot, Grape, Peach, Sushi, CaretSquareLeft,
        TemperatureUp, WindWarning, Snowplow, TachometerAltFastest, TruckCouch, ArrowsAltV,
        AlarmPlus, MoneyBillWaveAlt, Republican, TextSlash, VideoArrowDownLeft, _8, CloudDisabled,
        Laugh, FemaleCouple, Cupcake, Flushed, Corn, ChessBishop, CloudShowers, HelicopterSide,
        TachometerAltSlowest, ArrowAltSquareUp, ClockEightThirty, Taco, Kerning, GraphicTablet,
        MaskCarnival, GrinBeamSweat, Aubergine, EggFried, FrenchFries, Garlic, DiceD8, GolfBall,
        GolfClub, Shuttlecock, CloudHailMixed, Fog, Rv, TruckRamp, ClockElevenThirty,
        ClockThreeThirty, ClockTwelve, ClockTwoThirty, FilmSlash, Typewriter, Circle2, Circle8,
        AlbumCircleUser, Cow, Clouds, Kite, GrinTongueWink, LaughWink, Tired, Bacon, Burrito,
        Olives, CaretQuareUp, ChessRook, Cricket, Hurricane, ClockSixThirty, ClockTenThirty,
        ClockTwelveThirty, CarSideBolt, CodeCompare, CodePullRequest, DiagramProject, DisplayCode,
        LaptopCode, Qrcode, RectangleXmark, SidebarFlip, TableColumns, WrenchSimple, Square9,
        Betamax, BorderAll, BorderStyleAlt, Cowbell, DistributeSpacingVertical, GalleryThumbnails,
        HighlighterLine, TextSize, BatteryBolt, BatteryEmpty, BatteryHalf, DoorOpen, HammerCrash,
        LightSwitchOff, Projector, Archway, Binoculars, Castle, HouseChimneyMedical,
        HouseChimneyWindow, HouseMedical, HouseWindow, Igloo, LocationCrosshairsSlash,
        LocationCrosshairs, MapMarkerEdit, ParkingCircle, ParkingSlash, RouteHighway, ShoePrints,
        StreetView, TicketAlt, TrafficLightSlow, TrophyStar, VestPatches, ArrowDownSmallBig, Bong,
        BadgeDollar, CircleEnvelope, LiraSign, TvMusic, ToolMarquee, Money, ShieldPlus, Beer,
        Rhombus, GrinStars, ArrowCircleDown, CloudDrizzle, CloudUploadAlt, EnvelopeOpenText,
        ShieldInterrogation, PhoneCross, Fish, TreeChristmas, Bottle, ArrowSquareUp, Summer,
        ArrowsAltH, BusinessTime, RupeeSign, CloudCheck, Jpg, Sunrise, SortAlphaUp, SortDown, Tty,
        BookOpenReader, PeoplePoll, LinkSlash, CommentArrowDown, Feather, Package, Indent,
        HeartArrow, Tornado, MapMarkerCross, LevelUpAlt, V, AirFreshener, SearchDollar, Tennis,
        Incognito, RectabgleVertical, VectorAlt, FileAi, Terrace, Angry, Chess, Tachometer,
        ArrowAltFromBottom, SortNumericDownAlt, FunnelDollar, K, CommentAltMiddleTop, CommentText,
        _5, TimeForwardSixty, CursorTextAlt, Coffee, Bread, Pie, Braille, VideoSlash, _6, Network,
        Soap, EnvelopeBan, IceCream, GrinAlt, MehBlank, Avocado, Pan, Shrimp, CaretSquareDown,
        CaretSquareRight, CloudRainbow, GarageOpen, OilTemp, ClockSix, RulerHorizontal, Square3,
        ChessPiece, PhoneSlash, FerrisWheel, Knife, ArrowSquareDown, ChessClock, DiceTwo, CarBus,
        SpaceShuttle, TireFlat, ArrowAltSquareDown, Podium, BagsShopping, Ftp, Opacity, LaughBeam,
        PepperHot, ArrowToTop, ArrowsHCopy, BoxingGlove, DiceD10, Racquet, CloudMoon, CloudSnow,
        CarTilt, ClockOne, Tenge, Overline, PageBreak, ArrowsToDottedLine, CrossReligion, Billiard,
        PokerChip, Surfing, ShipSide, Jam, Melon, Spade, CloudMoonRain, CloudSunRain, CloudsMoon,
        TemperatureLow, ShuttleVan, TachometerAltAverage, TruckPickup, SortAlphaDownAlt,
        CommentSlash, Album, Baseball, Sphere, GrinSquint, GrinTears, GrinTongue, Surprise,
        OliveOil, ChessPawnAlt, ChessQueenAlt, FieldHockey, Caravan, TachometerAltSlow,
        ClockNineThirty, CodeFork, CodeMerge, CodePullRequestDraft, LinkHorizontal, RectangleCode,
        Sidebar, SquareCode, TableLayout, TableRows, TableTree, Circle3, Circle9, AlbumCirclePlus,
        AlbumCollection, BorderCenterH, BorderTop, CowbellMore, DistributeSpacingHorizontal,
        GridDividers, LassoSparkles, TextHeight, BlockBrick, Block, Apartment, Bomb, City,
        DiamondTurnRight, Dungeon, Farm, FireSmoke, Gavel, Hotel, HouseBuilding, HouseChimneyCrack,
        HouseChimney, HouseCrack, LocationDotSlash, MapPin, ParkingCircleSlash, PlaneArrival, Route,
        Vest, Wifi, DiagramSuccessor, SquareInfo, FileExcel, FilePowerpoint, SignalStream,
        WifiExclamation, HandHorns, Background, Devices, Mockup, ReflectHorizontal, BookmarkSlash,
        InputNumeric, ScrollTorah, BellConcierge, EarthAfrica, EarthAsia, PersonSeatReclined,
        TruckTow, WaterLadder, CircleCalendar, ChartUser, DongSign, Envelopes, Fax, FlorinSign,
        LariSign, MillSign, PaperclipVertical, PenNibSlash, WonSign, BlenderPhone, Bullhorn,
        MessageImage, MessageQuote, SmilePlus, Symbols, BracketsRound, BracketsSquare, Microchip,
        Terminal, FilesMedical, HospitalUser, Inhaler, Joint, LaptopMedical, Microscope,
        PrescriptionBottleAlt, ScalpelPath, SmokingBan, Walker, ArrowDownLeft, CircleQuarter,
        FaceConfused, FaceDisguise, FaceExpressionless, FaceGrinTongueWink, FaceRelieved, FaceShush,
        FaceSwear, FaceTissue, PersonSimple, CommentAltMusic, PenFancy, RssAlt, SendBackward,
        SlidersHSquare, Speakers, Subscript, Superscript, Table, VolumeDown, SquareM, SquareS,
        CoffeeBeans, Meat, CircleO, CircleW, CloudQuestion, FileEdit, SealQuestion, TrashRestore,
        BookSpells, FlaskPotion, HatWizard, HollyBerry, Joystick, PortalEnter, Radar, Dog,
        Transporter4, Transporter7, CircleEllipsis, DialMax, DialOff, PenField, BlockQuote,
        CircleWaveformLines, FaceViewfinder, ForwardFast, StarSharpHalf, EyeDropperHalf, ListMusic,
        PenCircle, SaxHot, LeafMaple, TeddyBear, Wreath, HandScissors, ParachuteBox, Chimney,
        ScannerImage, BrailleC, BrailleG, BrailleNAlt, DiscDrive, HouseSignal, Satellite, SimCard,
        Tools, PersonCirclePlus, UserLock, HouseLeave, ShippingTimed, SolarPanel, Sprinkler,
        DryerAlt, Dryer, GaugeCircleBolt, GaugeCirclePlus, ConveyorBeltEmpty, HouseChimneyUser,
        ScannerGun, Shelves, Stairs, ToiletPaperBlankUnder, TruckContainerEmpty, TruckFlatbed,
        Dolphin, Trillium, KeyboardDown, LampStreet, LaptopArrowDown, LaptopSlash, MicrochipAi,
        TentArrowTurnLeft, BadgerHoney, Duck, Frog, Site, FamilyDress, FamilyPants, HatCowboySide,
        Ring, Socks, UserCowboy, CupStraw, MartiniGlassEmpty, HandHoldingMagic, Mace, Quiz, Second,
        Blueberries, Coconut, CrateEmpty, Potato, BowlScoop, FonduePot, TtyAnswer, Admin,
        CategoryAlt, ExitAlt, Process, SwipeRight, WorkflowSettingAlt, BrowserUi, Constellation,
        CloudCode, LandLayers, React, CustomerCare, FeaturesAlt, HrPerson, MagnetUser, Brightness,
        DiagramNext, DownRight, Up, FileWord, HeadSideBrain, HeadSideCoughSlash, FaceAwesome,
        HandPeace, CopyImage, MoveToFolder, MemoPad, Notes, SpaghettiMonsterFlying, Tally2, Tally3,
        EarthAmericas, TicketsAirline, AustralSign, BookSection, BriefcaseBlank, BullseyeArrow,
        CentSign, ChartTreeMap, EnvelopeDot, HandsUsd, LightbulbSlash, ManatSign, MessageDollar,
        MessagesDollar, MoneyBillSimple, SignatureLock, SquareKanban, TugrikSign, Vault,
        MessageQuestion, BracketCurly, BracketRoundRight, BracketsCurly, BugSlash, LaptopMobile,
        WindowAlt, WindowMaximize, WindowMinimize, BookMedical, BookUser, BooksMedical,
        ClipboardUser, Crutches, FileMedicalAlt, FileMedical, Lungs, Skeleton, Virus,
        RectangleVertical, FaceGlasses, FaceParty, FaceUnamused, FaceWeary, HandBackPointLeft,
        PersonDress, SnowmanHead, Columns3, DrawSquare, H4, HeadSideHeadphones, Scrubber,
        StepBackward, VolumeOff, SquareC, SquareH, SquareL, SquareP, SquareR, BowlRice, BookCopy,
        CalculatorSimple, CircleD, CircleM, CircleU, Dharmachakra, WatchCalculator, WaveTriangle,
        BellSlash, CircleQuartersAlt, CloudExclamation, FileCsv, PartyHorn, ToggleOff, Sink, Coffin,
        LightsHoliday, PoliceBox, Skull, StarShooting, Telescope, TombstoneAlt, UfoBeam, PenSlash,
        PencilSlash, TrashCanClock, TrashSlash, VectorCircle, Aperture, CameraCctv,
        ClapperboardPlay, Panorama, StandardDefinition, RectangleVerticalHistory, TintSlash,
        Turntable, Webcam, ConveyorBelt, Dumpster, LampDesk, ShieldAlt, BrailleB, BrailleJ,
        BrailleK, BrailleO, HardHat, UserUnlock, Magnet, ScannerKeyboard, ToiletPaperSlash,
        BedEmpty, Drone, FanTable, Fan, Fireplace, Refrigerator, Angle90, Engine, Sickle, TruckBolt,
        PersonCarryBox, Unicorn, KeyboardLeft, MeterBolt, Mound, Pompebled, SnowflakeDroplets, Crow,
        Dove, RabbitFast, Spider, BuildAlt, ItAlt, Balloon, Child, ClothesHanger, HatWinter,
        Pool8Ball, ShirtLongSleeve, ShirtRunning, Transgender, UserTag, BowlSoftServe, CupcakeAlt,
        MugTeaSaucer, Award, AxeBattle, First, HockeyStickPuck, LacrosseStickBall, Cucumber,
        PanFood, Peapod, PepperAlt, Baguette, BreadSliceButter, CubesStacked, SaltShaker, Feedback,
        Journal, RankingStar, Review, SignUp, Subscription, TextBoxEdit, Category, ReferArrow,
        ComplianceClipboard, ChallengeAlt, DepositAlt, ArrowUpFromDottedLine, ChartMixed,
        ChartScatter3d, DiagramPrevious, DiagramSankey, SortShapesDown, SignalStreamSlash, Wifi2,
        PeopleDress, CandyCorn, CheeseAlt, Pattern, Replace, SmileyCommentAlt, BookQuran,
        EarthEuropa, Elevator, TicketAirline, BitcoinSign, BriefcaseArrowRight, FileSignature,
        HandHoldingUsd, MoneyBills, NfcMagnifyingGlass, RectanglePro, Shredder,
        SquarePollHorizontal, CircleUser, CommentAltMinus, CommentDots, Language, Messages,
        SquareQuote, BanBug, BarsSort, Binary, BinarySlash, BracketCurlyRight, BracketSquareRight,
        Gears, KeySkeletonLeftRight, BoneBreak, Hospital, MortarPestle, Pager, PrescriptionBottle,
        RadiationAlt, Toothbrush, UserMd, UserNurse, XRay, CircleBolt, Split, FaceAngryHorns,
        FaceDowncastSweat, FaceFearful, FaceLying, FacePleading, FaceSmileHearts, FaceSmileTongue,
        FaceSmilingHands, FaceTongueSweat, FaceWoozy, HandDots, HandHeart, HandsBubbles,
        MarsStrokeUp, PersonDressSimple, PipeSmoking, UsersGear, ObjectGroup, Podcast, SquareQ,
        SquareT, CircleC, CircleK, CircleR, Peace, PencilPaintbrush, Tilde, FileDownload, FileImage,
        FileUpload, GripHorizontal, GripLinesVertical, GripLines, HexagonExclamation,
        LightbulbQuestion, LightbulbExclamation, LocationExclamation, TimesHexagon, CoffinCross,
        Ornament, SpaceStationMoonAlt, SpiderWeb, StarChristmas, CircleTrash, DialMin, HexagonCheck,
        SquareEllipsisVertical, SquareEllipsis, CameraSlash, CameraViewfinder, Films,
        MusicNoteSlash, Screencast, StarSharpHalfStroke, TableList, DrumSteelpan, ObjectsColumn,
        RadioAlt, SprayCan, BallPile, Seedling, CalendarHeart, HandMiddleFinger, PersonDollyEmpty,
        Bath, Blender, DollyFlatbedAlt, HouseDay, IndustryAlt, Router, BrailleE, BrailleV,
        HouseUser, SatelliteDish, UserMinus, UserRobotXmarks, Lamp, LockOpenAlt, SirenOn, BedBunk,
        DroneAlt, PalletAlt, Frame, HoseReel, PhoneRotary, SprayCanSparkles, UtilityPole, Bird,
        PawClaws, Ram, Squid, Bugs, TentArrowDownToLine, Alicorn, CatSpace, DeerRudolph, It,
        SiteAlt, SiteBrowser, Boot, Family, HouseChimneyHeart, Piñata, UserMusic, UserNinja, Banana,
        CandySweet, WheatSlash, FirstAward, FirstLaurel, LacrosseStick, SecondMedal, ThirdAward,
        CanFood, Pear, PumpkinAlt2, BowlSpoon, Falafel, JugAlt, SushiAlt, Tamale, Live, Meeting,
        SubscriptionAlt, DescriptionAlt, DropDown, ModeAlt, PriorityArrow, Pig, TrafficLight,
        TrainSubwayTunnel, ArrowsRetweet, AudioDescriptionSlash, ChartCandlestick, Cubes,
        DiagramCells, EarDeaf, HeadSideHeart, UniversalAccess, YinYang, FilePdf, Brain,
        HeadSideVirus, CircleHeart, BreadLoaf, BurgerFries, Bullet, GraphicStyle, Images,
        BookTanakh, MemoCircleCheck, Memo, Note, PersonPraying, Tally1, CalendarImage, CalendarWeek,
        BangladeshiTakaSign, BasketShoppingSimple, ChartSimple, DiagramVenn, IndianRupeeSign,
        MoneyBillsSimple, MoneySimpleFromBracket, NfcPen, NotebookAlt, PenClip, PollH, RupiahSign,
        SignatureSlash, SterlingSign, CommentMinus, MessageSlash, Rss, BinaryLock, BracketSquare,
        Memory, Bacterium, ClipboardPrescription, CommentMedical, Ear, FilePrescription, Hospitals,
        LungsVirus, MaskFace, NotesMedical, PrescriptionBottlePill, Smoking, TeethOpen, UserMdChat,
        VirusSlash, Right, SealExclamation, FaceMonocle, FacePensive, FaceSleeping, FaceSmileHalo,
        FaceSmileTear, FaceWorried, HandBackPointRibbon, UniformMartialArts, UserSlash,
        CameraSecurity, Eject, H1, H2, H3, Paragraph, PauseCircle, SlidersV, StepForward,
        VolumeSlash, SquareF, SquareG, SquareJ, SquareU, SquareV, Cheeseburger,
        BowlChopsticksNoodles, FishCooked, MugMarshmallows, Stroopwafel, WineBottle, CircleF,
        CircleJ, CircleL, Pi, PlusMinus, Sigma, Theta, ValueAbsolute, FileExclamation, FileImport,
        FileMinus, LightEmergencyOn, PartyBell, SignalBarsGood, SquareExclamation, TrashUndoAlt,
        TrashUndo, Cauldron, FlaskPoison, HatSanta, KnifeKitchen, Mistletoe, Scarecrow, Tombstone,
        DialHigh, PenClipSlash, TrashCanCheck, TrashList, TrashPlus, Clapperboard, Gramophone,
        Kazoo, PaintbrushPencil, PianoKeyboard, Piano, SquareDashed, Trumpet, WebcamSlash,
        CompassSlash, Icicles, PooBolt, TemperatureList, HandSparkles, PersonDolly, ComputerClassic,
        PrintSlash, Shovel, BrailleP, BrailleS, Ethernet, TrafficCone, PersonCircleMinus,
        DoNotEnter, ThermometerAlt, LightCeiling, Microwave, Oven, Pallet, Angle, Grate, Hose, Pump,
        VrCardboard, BoxCircleCheck, FireHydrant, Sheep, TreeAlt, Worm, FloppyDiskPen, MeterFire,
        Meter, SimCards, HouseTsunami, MattressPillow, SunPlantWilt, Tents, PersonSign, Scarf,
        UserHeadset, UserInjured, AppleCore, WheatAwn, BroomBall, CardDiamond, FirstMedal,
        HelmetBattle, Scroll, Staff, ThirdLaurel, ThirdMedal, Loan, DownLeft, PersonWalkingWithCane,
        UpLeft, HeadSideCough, HeadSideMask, HeartCrack, BurgerGlass, BlogText, Squircle,
        BookCircleArrowUp, SquareMinus, CalendarDay, CalendarStar, CalendarXmark, HourglassStart,
        WatchSmart, Watch, BoxDollar, CalendarDays, CediSign, CruzeiroSign, FileCircleInfo,
        FloppyDiskCircleXmark, GuaraniSign, KipSign, ListDropdown, Nfc, PesoSign,
        PrintMagnifyingGlass, ShopSlash, Signature, CommentAltCheck, CommentAltDots, CommentAltEdit,
        CommentSmile, MessageArrowUp, MessagesQuestion, Voicemail, BinaryCircleCheck, Browsers,
        FileBinary, Hdd, WindowRestore, Eyes, HeartRate, HospitalSymbol, Radiation, MedicalStar,
        Hexagon, Left, SquareSmall, SquareStar, FaceCowboyHat, FaceDrooling, FaceIcicles, FaceMask,
        FaceNauseated, FacePersevering, FaceSleepy, FaceSmileUpsideDown, HandHoldingWater,
        SlidersVSquare, Waveform, SquareA, SquareB, SquareI, SquareO, SquareW, SquareX, CookieAlt,
        GlassWhiskeyRocks, ChalkboardUser, CircleE, CircleN, CircleX, DotCircle, GripVertical,
        LowVision, Ghost, HandSpock, PlanetRinged, Scythe, Transporter3, Transporter6, UserAlien,
        UserVisor, DialLow, Dial, TrashCheck, GifSquare, VectorPolygon, CameraRotate, ImagesUser,
        MusicNote, RectangleList, Cello, Splotch, TriangleMusic, Anchor, Campfire, FeatherPointed,
        LeafOak, SunDust, ThermometerQuarter, Angel, BoxHeart, LeafHeart, ContainerStorage,
        DollyFlatbed, Flask, HouseNight, BrailleH, BrailleL, BrailleN, BrailleQ, BrailleW,
        WrenchAlt, PersonCircleCheck, PersonCircleXmark, UserCheck, ClipboardCheck, HouseReturn,
        Toilet, LampFloor, Washer, GrateDroplet, WindTurbine, ClockDesk, ShieldSlash,
        ToiletPaperUnder, Bee, KiwiBird, DisplayArrowDown, FireFlameSimple, FloppyDisks, Manhole,
        SdCards, TrianglePersonDigging, BagSeedling, FireBurner, MountainCity, Deer, HorseHead,
        Build, InventoryAlt, QrScan, GunSquirt, HatCowboy, CupStrawSwoosh, CupTogo, GlassEmpty,
        UserChef, CardClub, Dagger, FlyingDisc, MaskSnorkel, SecondAward, SecondLaurel, CitrusSlice,
        GarlicAlt, MushroomAlt, Olive, Peanut, BowlScoops, Donut, JarAlt, PanFrying, PlateWheat,
        ShishKebab, Waffle, NewspaperOpen, Newspaper, TextBox, Leave, SwipeLeft, Tap, ConditionAlt,
        PriorityImportance, WorkflowSetting, Workflow, Bucket, FlyInsect, LandLocation, Choose,
        Features, Sofa, ArrowDownToSquare, ArrowRightToBracket, ChartBullet, DiagramPredecessor,
        DiagramSubtask, UpRight, WheelchairMove, FileExport, Wifi1, HeadSide, HandsClapping,
        PeoplePants, SquareHeart, BurgerAlt, Api, License, MoveToFolder2, Paste, ReflectVertical,
        RemoveFolder, TriangleWarning, CircleBookOpen, UserPilotTie, BarsStaggered, CartArrowDown,
        ChartSimpleHorizontal, ColonSign, FrancSign, ItalianLiraSign, NfcTrash, PhoneFlip,
        Trademark, BallotCheck, MessageBot, PaperPlaneTop, PhonePlus, HorizontalRule, Cannabis,
        Capsules, CommentAltMedical, Crutch, Dna, ShieldVirus, Stomach, CircleThreeQuarters,
        HeartHalfStroke, FaceAnguished, FaceAnxiousSweat, FaceDisappointed, FaceHandYawn,
        FaceSadSweat, FaceSmirking, FaceTongueMoney, FaceVomit, FaceZany, FaceZipper, HandBackFist,
        HandsHolding, MarsStrokeRight, UserPen, AlignSlash, Banjo, CameraMovie, Clipboard,
        DrawPolygon, Mp3Player, PenSquare, SendBack, Strikethrough, VolumeMute, WaveformPath,
        SquareD, SquareK, SquareZ, GlassChampagne, CircleB, CircleS, CircleV, CircleXmark,
        StarAndCrescent, TheaterMasks, CheckCircle, LightEmergency, PlusHexagon, SignalBarsFair,
        StarExclamation, PlanetMoon, FluxCapacitor, Raygun, SolarSystem, SpaceStationMoon,
        Transporter2, Transporter, UserAstronaut, Airplay, Command, GripDotsVertical, TrashCanPlus,
        TrashClock, BoltAuto, BoltSlash, DroneFront, HighDefinition, GuitarElectric, Mandolin,
        MusicSlash, Radio, Saxophone, Scribble, CloudMeatball, FlowerDaffodil, SnowmanAlt,
        ThermometerFull, GlobeSnow, HomeHeart, Ribbon, UserCrown, ConveyorBeltAlt, BrailleA,
        BrailleD, BrailleI, BrailleM, BrailleT, BrailleU, BrailleY, SdCard, PersonCircleQuestion,
        UserXmark, ScannerTouchscreen, SortCircleUp, SortCircle, Vacuum, CarRear, GaugeCircleMinus,
        Robot, PlaneSlash, ToiletPaperUnderSlash, TransformerBolt, TruckFront, UserPolice, CowAlt,
        Elephant, Hippo, Lobster, Otter, MeterDroplet, Locust, MosquitoNet, Mosquito, Pickaxe,
        PlantWilt, TentArrowLeftRight, TentArrowsDown, Cat, SkullCow, Squirrel, Discover,
        ShovelSnow, Sunglasses, HandFist, Medal, SwimmingPool, PineappleAlt, Custard,
        FlatbreadStuffed, GlassWaterDroplet, JarWheat, SushiRoll, Invite, SwipeUp, Condition,
        PriorityArrows, ExternalWorld, LightbulbSetting, GalaxyStar, RectangleHistoryCirclePlus,
        Massage, Ux, BrightnessLow, ClosedCaptioningSlash, DownToLine, HandshakeAngle,
        KeyboardBrightnessLow, KeyboardBrightness, Octagon, Slash, SortSizeDown, SortSizeUp,
        FaceHeadBandage, HeadSideMedical, People, PeopleArrowsLeftRight, AnimatedIcon,
        AttributionPen, BrokenImage, FollowFolder, NoPeople, Picpeople, PicpeopleFilled, Template,
        TemplateAlt, CircleBookmark, InputText, Tally4, RestroomSimple, UserPilot,
        CalendarArrowDown, CartShoppingFast, FloppyDiskCircleArrowRight, FolderXmark, HouseLaptop,
        LitecoinSign, MoneyFromBracket, NfcLock, NfcSlash, PesetaSign, VoteYea, MessageArrowUpRight,
        MessageText, MessageXmark, WalkieTalkie, BarsFilter, Notdef, HSquare, HandHoldingMedical,
        IdCardClipAlt, Kidneys, NoteMedical, Poop, Scalpel, WatchFitness, HeartHalf, ListTimeline,
        SquareBolt, Baby, FaceBeamHandOverMouth, FaceNoseSteam, FaceRaisedEyebrow, FaceScream,
        FaceSmileHorns, FaceSunglasses, FaceThermometer, HandFingersCrossed, HandLove,
        HandPointRibbon, HandshakeSimpleSlash, PersonPregnant, Reel, BroadcastTower, Clarinet,
        ComputerSpeaker, FilmCanister, Heading, MicrophoneSlash, ObjectUngroup, ParagraphLeft,
        PenNib, PlayCircle, StopCircle, SquareE, SquareN, DrumstickBite, GlassCitrus, Cactus,
        CircleA, CircleG, CircleP, CircleQ, CircleY, StarOfDavid, BatteryExclamation, CheckDouble,
        CircleExclamationCheck, Information, MinusCircle, MinusHexagon, RotateExclamation,
        ShareAltSquare, SignalAltSlash, TrashRestoreAlt, CandleHolder, HatWitch, PumpkinAlt,
        SkullCrossbones, Transporter5, Ufo, _360Degrees, DeleteRight, TrashCanList, TrashCanSlash,
        TrashXmark, CircleCamera, CircleMicrophoneLines, CircleMicrophone, CircleVideo,
        CowbellCirclePlus, Drum, Flute, EarMuffs, ThermometerEmpty, ThermometerThreeQuarters, Trees,
        FileUser, HandPaper, DollyFlatbedEmpty, FaucetDrip, BrailleR, Digging, Forklift,
        TabletAndroidAlt, TvRetro, ArtificialIntelligence, LocationArrow, UserShield, UsersSlash,
        Loveseat, ShippingFast, Siren, SortCircleDown, Blanket, LightbulbOn, TankWater,
        TruckMedical, WindowFrame, ShieldKeyhole, ShieldXmark, Tape, UtilityPoleDouble, Crab,
        FishBones, Horse, Snake, TreesAlt, ComputerMouse, DesktopArrowDown, Pedestal,
        UserHelmetSafety, CloverAlt, Bat, Turtle, ItComputer, Qr, BlockQuestion, HandHoldingDroplet,
        HandsHeart, RingDiamond, ShirtTankTop, CandyBar, GlassHalf, MartiniGlassCitrus, CardHeart,
        TowerControl, WarehouseAlt, ArrowDownTriangleSquare, ArrowLeftFromLine, ArrowTurnDownLeft,
        ChartWaterfall, SortShapesUp, Sitemap, WifiSlash, HandLizard, Acorn, AppleCrate, CandyCane,
        Jug, AttributionPencil, Beacon, BlogPencil, DesktopWallpaper, Followcollection, IconStar,
        StarCommentAlt, TextShadow, BookCircleArrowRight, InputPipe, Escalator, PersonSeat,
        CalendarArrowUp, Snooze, BahtSign, CartMinus, Inboxes, NairaSign, NoteSticky,
        SquarePollVertical, StoreSlash, VoteNay, AddressCard, HundredPoints, MessageArrowDown,
        MessageSms, SquarePhoneHangup, BracketRound, Bacteria, Biohazard, Disease, Lips, Pills,
        Prescription, Procedures, PumpMedical, Stretcher, Tubes, UsersMedical, Viruses, CircleHalf,
        CircleStar, ShareSquare, FaceAstonished, FaceConfounded, FaceExplode, FaceEyesXmarks,
        FaceHushed, FaceThinking, HandBackPointDown, HandBackPointRight, HandHoldingSkull, HandWave,
        HandsHoldingDiamond, PuzzleAlt, ThoughtBubble, UserGear, CameraRetro, Clone, Eraser,
        FileAudio, Outdent, Swatchbook, SquareY, BowlChopsticks, CoffeeBean, GlassWhiskey, CircleH,
        CircleI, CircleT, CircleZ, WaveSine, WaveSquare, DiamondExclamation, FileZipper, FolderOpen,
        Axe, SignalBarsWeak, ToggleOn, Alien, BookDead, ClawMarks, Galaxy, HoodCloak, PortalExit,
        Stocking, Transporter1, TransporterEmpty, UserRobot, CircleEllipsisVertical, DialMedLow,
        DialMed, GripDots, PenFancySlash, PenSwirl, ImageSlash, Guitars, RectanglesMixed, Mountain,
        Sailboat, Mercury, Neuter, Faucet, Flashlight, BrailleX, BrailleZ, FireExtinguisher, Plug,
        Screwdriver, TabletAndroid, PersonCircleExclamation, Couch, DigitalTachograph, SoapAlt,
        TabletRugged, Shower, DumpsterFire, Moped, ShieldCross, VacuumRobot, WindowFrameOpen,
        ShieldMinus, ShowerDown, HorseSaddle, Monkey, DisplayMedical, DisplaySlash, GrillHotAlt,
        Dragon, Narwhal, Rabbit, SpiderBlackWidow, Whale, BootHeeled, Tshirt, CakeSlice, Badminton,
        GoalNet, QuizAlt, ScrollOld, SkiBootSki, Citrus, KiwiFruit, LeafyGreen, Butter, Flatbread,
        JugBottle, Pancakes, Popsicle, Answer, CatalogAlt, CatalogMagazine, InviteAlt, MeetingAlt,
        Rank, RankingPodium, TextBoxDots, WishlistHeart, WishlistStar, ArrowProgress, Mode,
        DirectionSignal, Chatbot, UserInterfaceUi, BuildingNgo, GovernmentUser, RegistrationPaper,
        Investment, AirplaneJourney, Refund, Plan, BicycleJourney, TeamCheck, TourVirtual, TaxAlt,
        Friday, Sunday, PhotoCapture, EmployeesWomanMan, Method, Percent90, Restock, Customize,
        HexagonDivide, PlaceOfWorship, ToriiGate, BarberPole, TruckBox, PasswordAlt, Dinner, Mix,
        Banner3, CurveAlt, Nose, Picking, QueueAlt, Multiple, OvalAlt, Oval, RotateSquare,
        DominoEffect, Insight, Age, Trust, MegaphoneAnnouncementLeader, PickingBox, BenefitDiamond,
        LightbulbCfl, BrakeWarning, PigBankBulb, ThreeLeafClover, TruckFire, Mp3File, Mp4File,
        PptFile, FeedbackCycleLoop, SpeechBubbleStory, CandlePoseYoga, DownFromBracket,
        DisplayChartUp, Free, HouseCircleCheck, HouseFire, PreviousSquare, SurveyXmark, CarsCrash,
        SafeBox, Track, Auction, LeadershipAlt, OrganizationChart, SalaryAlt,
        NotFoundMagnifyingGlass, NetworkAnalytic, CheapDollar, Percent40, Sell, Supplier,
        Customization, Floor, ShieldDog, SpringCalendar, OctagonMinus, OctagonXmark, PrayingHands,
        SquareDivide, Seal, Svg, AdPaid, BonusStar, Channel, TransformationDesign,
        FaceSunglassesAlt, MoneyBillTransfer, MoneyTransferSmartphone, AgeAlt, Life, SkillAlt,
        PlantSeedInvest, ShieldSecurityRisk, HandshakeDealLoan, LimitHand, PlugCircleMinus,
        _70sMusicDisc, BagShoppingMinus, Dropdown, PointerText, TrophyAchievementSkill,
        PaperPlaneLaunch, SunSalutationYoga, ChatBubbleCall, TimerClockCall, CloudGearAutomation,
        TurnLeftDown, MoneyWings, MapLocationTrack, SignPostsWrench, SignPosts, PlayMicrophone,
        CompassSouth, Algorithm, Operation, GalaxyAlt, UpRightFromSquare, Url, Budget, Leadership,
        Risk, FunctionProcess, Productivity, UxBrowser, Builder, FloorAlt, LionHead, Pollution,
        Integral, OctagonExclamation, RankingPodiumEmpty, SoldHouse, TruckArrowRight, Javascript,
        Otp, PasswordComputer, UiUx, PointOfSaleBill, GroceryBag, TransformationShapes, Pending,
        InfoGuide, ScrewAlt, LightbulbCflOn, HatBeach, Joker, PlantCare, PlantGrowth,
        ChartPieSimpleCircleDollar, UnderConstruction, UpFromBracket, CvvCard,
        WheatAwnCircleExclamation, BeerMugEmpty, DiaryClasp, FeedbackAlt, LiveAlt, RankingStars,
        Videoconference, ClearAlt, SwipeDown, ArrowsToEye, LandLayerLocation, SourceData, PigFace,
        CalculatorMoney, GovernmentFlag, Challenge, Compliance, DriverWoman, TrainStation,
        EmployeeAlt, EmployeeManAlt, Rent, Fail, LeaderboardAlt, UserSalary, ClockUpArrow,
        CheapStackDollar, Percent10, Percent25, Drawer, CatHead, Ankh, GreaterThan, Analyse,
        BenefitPorcent, FeeReceipt, AgeRestrictionThree, Module, Spy, GuideAlt, RulesAlt, Skill,
        Blood, DocumentCircleWrong, GovernmentBudget, TimeWatchCalendar, IotAlt, Screw,
        SolarPanelSun, BenefitDiamondAlt, Referral, GreekHelmet, GolfHole, HorseshoeBroken,
        SystemCloud, RoadBarrier, HandshakeTrust, Treadmill, LocationPinCall, ChartLineUpDown,
        EndlessLoop, HouseCircleXmark, HouseCrackAlt, ForeignLanguageAudio, Replay10, SpainMap,
        PuzzlePieces, CarJourney, AuditAlt, Audit, BadgetCheckAlt, Blockchain3, CheapBill,
        Percent30, Percent60, SupplierAlt, Damage, GreaterThanEqual, LessThan, Omega, ExpenseBill,
        LawyerMan, Onboarding, SpeedometerKpi, Banner4, TransformationCircle,
        AgeRestrictionTwentyOne, ArrowComparison, PersonCv, Snap, LessonClass, ModelCubeArrows,
        StudentAlt, ArrowUpwardGrowthCrypto, PiggyBankBudget, CareerGrowth, LeadFunnel, Mortgage,
        RevenueEuro, Roulette, TruckUtensils, PuzzlePieceIntegration, ArrowsSplitUpAndLeft,
        GroupArrowsRotate, Replay30, CompassEast, SquareUpRight, HrGroup, RefundAlt,
        CustomerService, Brand, Saturday, CheapStack, ClipboardExclamation, Percent100, Selling,
        Warranty, CustomizeComputer, Lion, BookHeart, TruckCheck, DocumentPaid, QueueLine, TipCoin,
        PeopleRoof, Muscle, GrowthChartInvest, BasketShoppingMinus, MemberSearch, ProgressUpload,
        ThunderstormRisk, AnatomicalHeart, DumbbellWeightlifting, BellNotificationCall, InboxFull,
        MailboxEnvelope, BasketShoppingPlus, HouseFlag, SeatbeltSafetyDriver, WineGlassEmpty,
        CardSpade, NestingDolls, HoneyPot, AnswerAlt, DiaryBookmarkDown, FeedbackHand, Description,
        AddImage, PlugCable, Deposit, Revenue, Total, EmployeeMan, LeaderAlt, Department, HandBill,
        DurationAlt, Tuesday, CrmComputer, Assign, Employees, SendMoney, WorkInProgress, SofaSize,
        BioLeaves, Waste, BellSchoolSlash, Workshop, LawyerWoman, PaymentPos, ConvertDocument,
        MembershipVip, PlanStrategy, RecipeBook, MultipleAlt, Effect, ModelCubeSpace,
        GiftBoxBenefits, LeadManagement, _00sMusicDisc, Desk, ArrowsToCircle,
        ChartMixedUpCircleCurrency, HighFiveCelebrationYes, ThumbsUpTrust, RunningTrack,
        ArrowsSplitRightAndLeft, HoldingHandGear, SummaryCheck, PostalAddress, RoadSignLeft,
        ErrorCamera, ReflectHorizontalAlt, CompassWest, DriverMan, TeamCheckAlt, RiskAlt,
        AssessmentAlt, Duration, NotFoundAlt, SpeedometerArrow, Debt, Percent75, Percent80,
        SendMoneySmartphone, DogLeashed, PawHeart, Intersection, Om, WomanScientist,
        MarketplaceStore, Marketplace, Banner5, CurveArrow, AgeRestrictionZero,
        TorchInspirationLeader, SmartHome, UserCoach, UserTrust, OperatingSystemUpgrade,
        ChoirSinging, DumbbellFitness, FingerprintSecurityRisk, GroupCommunitySocialMedia,
        Excavator, TurnRight, RadarMonitoringTrack, CardinalCompass, CompassNorth, SleepingBag,
        CallDuration, _404, NotFound, Payroll, StageTheatre, WastePollution, OctagonPlus,
        SoldSignal, ReservationSmartphone, ReservationTable, Bonus, Kpi, MilkAlt, Recipe,
        TransformationBlock, TogetherPeople, Introduction, SkillUser, StoryBook,
        ChecklistTaskBudget, KeyLockCrypto, Iot, Scooter, ImproveUser, TalentHand, PlugCircleCheck,
        _60sMusicDisc, DropdownSelect, GlobePointer, MovFile, QuillPenStory, ScrollDocumentStory,
        CandleLotusYoga, HeartHealthMuscle, JumpingRope, BrokenChainLinkWrong, AnglesUpDown, Swap,
        ClipboardQuestion, FuelGauge, GpsNavigation, Lighthouse, TrainTrack, Skip15Seconds,
        StopSquare, SubtitlesSlash, Tax, CheckOutCalendar, Monday, Thursday, IssueLoupe, Percent50,
        BoothCurtain, DrawerAlt, StageConcert, BadgeLeaf, Bio, ShieldCat, Bible, Chalkboard,
        EmptySet, Lambda, HairClipper, RegionPinAlt, PasswordEmail, Fee, KpiEvaluation, NoFee, Paid,
        Membership, Seller, GroceryBasket, InsertArrows, Insert, PersonShelter, SkinHair,
        PeopleNetworkPartner, PodiumVictoryLeader, StoreBuyer, PlugCircleExclamation, Meditation,
        PointerLoading, BalletDance, LoopSquare, RightFromBracket, InsertCreditCard,
        HouseCircleExclamation, LastSquare, ExternalHardDrive, BudgetAlt, CalculatorBill, Invest,
        Guide, CustomizationCogwheel, Fabric, Violin, AirPollution, Pets, NotEqual, OctagonDivide,
        Token, BuildingCircleArrowRight, RegionPin, TruckArrowLeft, UserKey, PlateUtensils,
        UtensilsSlash, Banner2, Curve, AgeRestrictionEighteen, BookPlus, FunctionSquare,
        StoryFairyTale, StoryFantasy, SkinDrop, LeaderSpeech, WalletBuyer, CalendarPaymentLoan,
        EmployeeHandbook, CloudBackUpAlt, CloudBackUp, SmartHomeAlt, BenefitHand, Benefit, BonusAlt,
        ConveyorBeltArm, PlugCirclePlus, Webhook, MemberList, RadioButton, DashboardMonitor,
        AudienceMegaphone, TurnLeft, HouseLock, BlockMicrophone, Replay5, Mango, BottleDroplet,
        DiaryBookmarks, FeedbackReview, JournalAlt, Preview, WorkflowAlt, GalaxyPlanet, PlugAlt,
        MatchFire, RevenueAlt, StateCountry, ToDo, Legal, Expense, LeaderboardTrophy, DailyCalendar,
        Wednesday, CrmAlt, PayrollCalendar, FloorLayer, Tie, CircleDivide, Hamsa, UsersClass,
        MosqueMoon, LockHashtag, PointOfSale, Milk, InsertAlt, Queue, AgeRestrictionSix,
        AgeRestrictionSixteen, MoneyCoinTransfer, ModelCube, Rules, BackUp, RoboticArm,
        BenefitIncrease, TalentAlt, DumbbellRay, MouseField, BagMapPin, TruckLadder, IpAddress,
        Burst, FolderFire, AirplaneWindowOpen, MapPoint, PersonLuggage, Overview, Journey,
        TrainJourney, Branding, InsightHead, Leaderboard, CheckInCalendar, CorporateAlt, Corporate,
        ProblemSolving, Shirt, FlowerButterfly, LessThanEqual, OctagonCheck, ScaleComparisonAlt,
        MosqueAlt, MarketplaceAlt, PadlockCheck, SellerStore, GraphCurve, InsertSquare, QueueSignal,
        TargetAudience, AgeRestrictionTwelve, InsightAlt, MoneyTransferAlt, Lesson, CircleOverlap,
        CalendarGavelLegal, _90sMusicDisc, SkeletonRibs, SpartanHelmet, Horseshoe, RecycleBin,
        ShieldTrust, CourtSport, IncenseSticksYoga, StrategyChessRisk, EmailPending, MailboxFlagUp,
        ArrowDownFromArc, ArrowLeftFromArc, ChartKanban, LeftFromBracket, CreditCardEye,
        ClipoardWrong, PauseSquare, RewindButtonCircle, Tricycle, BloodDropper, ChooseAlt,
        Selection, Accident, TourGuidePeople, TrainStationBuilding, RentSignal, WalletArrow,
        VideoDuration, Blueprint, CustomizeEdit, Handmade, Divide, Gopuram, Kaaba, ManScientist,
        Practice, Script, UserGraduate, RazorBarber, Booking, HashtagLock, PasswordSmartphone,
        AgeRestrictionSeven, AgeRestrictionThirteen, Cryptocurrency, MoneyTransferCoinArrow,
        TrustAlt, Student, BloodTestTube, HoldingHandRevenue, Lead, ReferralAlt, PlugCircleBolt,
        _80sMusicDisc, Chip, Raccoon, LaptopBinary, ProgressComplete, ChartMixedUpCircleDollar,
        WebDesign, StationaryBike, BellNotificationSocialMedia, CalendarCall, GroupCall, PhoneGuide,
        ArrowLeftToArc, Wave, CircleNodes, OrderHistory, Resume, CarTunnel, SquareDashedCirclePlus,
        SurveillanceCamera, WheatAwnSlash, Third, Walking, MelonAlt, Peanuts, SandwichAlt, Catalog,
        AdminAlt, DirectionSignalArrow, Refer, ChatbotSpeechBubble, PlugConnection, Boss, Completed,
        CoinUpArrow, ComplianceDocument, Hr, TabFolder, Crm, Percent20, Percent70, Stage,
        SunglassesAlt, Equals, Mosque, Synagogue, Vihara, AnalyseAlt, Visit, PointOfSaleSignal,
        DotPending, LightbulbHead, IntroductionHandshake, Function, BloodTestTubeAlt, Skin,
        CreditCardBuyer, HeartPartnerHandshake, ShoppingCartBuyer, CareerPath, ReferralUser,
        FlaskGear, SlotMachine, ProgressDownload, Branching, ChartPieSimpleCircleCurrency,
        UserSkillGear, ResistanceBand, CalendarBirhtdayCake, StarRatingCall, ArrowUpFromGroundWater,
        ArrowProgressAlt, RotateReverse, ArrowTurnLeftUp, CryptoCalendar, FreeDelivery,
        PayrollCheck, WhiteSpace, CompassAlt, ToDoAlt, Leader, Assessment, BillArrow,
        CalendarSalary, DepartmentStructure, LimitSpeedometer, Cheap, Knitting, Church,
        ScaleComparison, Banner, Cv, ExchangeCryptocurrency, ConvertShapes, SourceDocumentAlt,
        SourceDocument, SkinArrow, CalculatorMathTax, CalendarEventTax, ClockTimeTracking,
        MeasuringTape, General, Talent, BinBottles, DashboardPanel, InternetSpeedWifi,
        ToiletsPortable, ArrowUpToArc, FileCloud, InsertButtonCircle).sortedBy { it.name }
    return __Bold!!
  }
