package me.localx.icons.rounded

import androidx.compose.ui.graphics.vector.ImageVector
import me.localx.icons.rounded.filled.*
import kotlin.collections.List as ____KtList

private var __Filled: ____KtList<ImageVector>? = null

public val Icons.Filled.allIconsList: ____KtList<ImageVector>
  get() {
    if (__Filled != null) {
      return __Filled!!
    }
    __Filled = listOf(Home, User, PhoneCall, Envelope, Marker, Heart, Settings, Play, Star, UsersAlt,
        Apps, ShoppingCart, Add, Bookmark, Lock, Users, Globe, MenuBurger, GraduationCap, Info,
        Pencil, Checkbox, CommentAlt, CrossCircle, Camera, Trash, Briefcase, Calendar, UserAdd,
        Share, Eye, Document, Megaphone, SettingsSliders, Comment, AngleLeft, AngleRight,
        CreditCard, Pause, BadgeCheck, UsdCircle, Edit, Bulb, Wallet, Check, CirclePhone,
        Interrogation, Bell, ShieldCheck, PaperPlane, Picture, CalendarClock, EyeCrossed,
        VideoCameraAlt, Exclamation, Bolt, Layers, Crown, Headset, Cross, Comments, Folder, Coins,
        PlayAlt, Search, ThumbsUp, ListCheck, ChartHistogram, Volume, ShoppingBag, Refresh,
        Following, HandHoldingHeart, List, Download, AngleCircleRight, MusicAlt, Filter, SackDollar,
        Paw, Plus, CrossSmall, Clock, World, Key, CalendarLines, Ballot, Trophy, Browser,
        ShoppingCartAdd, ArrowCircleRight, Stats, CirclePhoneFlip, AppsAdd, AlarmClock, Bank,
        PiggyBank, AddDocument, Handshake, SearchAlt, ModePortrait, AngleSmallRight, CaretDown,
        Undo, PlusSmall, Portrait, AngleDown, Gift, Disk, ArrowSmallLeft, Thumbtack, DocumentSigned,
        Gamepad, At, BookAlt, IdBadge, Palette, MobileButton, ClockThree, CircleEnvelope,
        CallIncoming, Doctor, Unlock, MoneyCheckEdit, CommentAltMiddle, ArrowRight, Computer,
        BellRing, Tags, Cursor, ChartPieAlt, Badge, Restaurant, Headphones, Exit, Microphone,
        AngleSmallDown, Sparkles, MapMarker, Ticket, AddressBook, SignOutAlt, Shop, Building,
        LayoutFluid, Cube, AngleCircleLeft, PhoneOffice, AsseptDocument, ArrowLeft, TimePast,
        FolderDownload, TimeFast, ShieldExclamation, RocketLunch, BadgePercent, Flame, Stop,
        WomanHead, ArrowSmallRight, Forward, CallOutgoing, MugHotAlt, CursorFinger, Fingerprint,
        CommentQuestion, Copy, WifiAlt, File, Receipt, HomeLocationAlt, PlayPause, Dashboard, Leaf,
        SignalAlt2, Clip, AngleDoubleRight, InboxIn, DeleteUser, Navigation, CommentCheck,
        ChartLineUp, Bed, ArrowCircleLeft, Moon, AngleSmallLeft, Print, PhonePause, Diamond,
        CommentInfo, Sun, Boxes, Grid, Smartphone, ArrowAltCircleRight, CloudDownloadAlt, ManHead,
        MapMarkerHome, Diploma, ShoppingCartCheck, Power, Plane, CaretRight, FileInvoice, StoreAlt,
        Loading, SortDown, CalendarCheck, Interactive, Film, MoonStars, ArrowAltCircleLeft,
        Calculator, QuestionSquare, Form, Running, Notebook, RotateRight, BookBookmark, LifeRing,
        ClipboardList, EnvelopeOpen, Donate, BookOpenCover, MicrophoneAlt, SignInAlt, Stethoscope,
        FlagAlt, CopyAlt, MenuDotsVertical, RoomService, CalendarLinesPen, CommentHeart, ClockFive,
        MindShare, Dollar, Expand, Select, Pulse, TimeForward, LinkAlt, Map, Delete, BoxAlt, Upload,
        ArrowSquareRight, DeleteDocument, PaintRoller, Duplicate, TruckSide, Stars, Shuffle,
        FolderUpload, RemoveUser, EditAlt, AngleDoubleSmallRight, Database, AngleDoubleSmallLeft,
        VideoCamera, MobileNotch, Fill, LayerPlus, Medicine, ChartNetwork, Flag, Treatment, Tooth,
        AlarmPlus, ArrowsRepeat, MoneyBillWave, UsdSquare, Bug, ChessQueen, CommentQuote, Wheat,
        CakeBirthday, HouseFlood, FlowerTulip, SortAlt, CalendarMinus, CommentCode, CaretUp,
        BikingMountain, DiceAlt, Hamburger, Shield, MoneyCheck, ChartTree, Turkey, AngleCircleUp,
        DiceD6, ToolBox, Sack, TimeQuarterTo, Circle, Ban, AngleSquareRight, FolderTree, Car,
        StarOctogram, ArrowSquareLeft, ChairOffice, EnvelopePlus, PuzzlePiece, SuitcaseAlt,
        BoxCheck, Sort, FilterSlash, Filters, ELearning, Subtitles, Mouse, ArrowUpRightFromSquare,
        CloudSun, Coin, PencilRuler, Asterik, TachometerAltFastest, HandHoldingBox, CommentDollar,
        Scissors, Sticker, GrinHearts, Water, ChildHead, Mountains, ZoomIn, Croissant,
        ChargingStation, SensorFire, Wind, SortAmountDownAlt, Euro, Basketball, CommentXmark,
        Square, Archive, TimeDelete, CallMissed, ChessKnightAlt, Cookie, AlignCenter, AppsDelete,
        Butterfly, Biking, ArrowAltSquareRight, TestTube, Umbrella, Rocket, CircleSmall, Keyboard,
        WaterBottle, Mailbox, Laptop, Soup, Wheelchair, SteeringWheel, AngleDoubleSmallDown,
        CommentsQuestionCheck, Physics, NetworkCloud, MapMarkerMinus, Grill, Guitar, MugHot, X,
        Spinner, Drumstick, SmileBeam, AngleSquareUp, Pennant, FileSpreadsheet, EnvelopeMarker,
        Cupcake, ChartConnected, GlassCheers, TachometerFast, CalendarPlus, BalanceScaleLeft,
        RulerCombined, RingsWedding, SadTear, ClockTwo, TimeAdd, Symbol, Train, ChatArrowDown, Pot,
        CommentImage, SignalAlt, ArrowAltCircleDown, Registered, PhotoFilmMusic,
        CommentArrowUpRight, ArrowSmallUp, AlignLeft, Spa, ChatArrowGrow, Rewind, FileInvoiceDollar,
        CommentsQuestion, ShoppingBasket, Pharmacy, ClipboardListCheck, CommentUser, HamburgerSoda,
        Redo, EngineWarning, School, TimeCheck, AppsSort, Broom, Smile, Box, HandHoldingSeeding,
        ThumbsDown, HomeLocation, AngleCircleDown, ModeLandscape, InboxOut, AngleDoubleLeft, Game,
        MinusSmall, Utensils, PlaneAlt, ChartPie, LocationAlt, BusinessTime, Copyright, CallHistory,
        ArrowCircleDown, ArrowUpRightAndArrowDownLeftFromCenter, UserTime, AngleUp, Link,
        BarsProgress, TimeTwentyFour, MenuDots, Triangle, PeoplePoll, Gym, Enter, Minus, Grin,
        AlignJustify, AddFolder, ChartArea, Gallery, Book, ArrowCircleUp, CloudUploadAlt,
        CirclePhoneHangup, Screen, SensorAlert, Label, Fish, Text, AppleWhole, RecordVinyl,
        BullseyePointer, FileChartLine, CarAlt, AngleSmallUp, HeadSideThinking, Swimmer, Backpack,
        DataTransfer, TruckLoading, CommentPen, ArrowTrendUp, CloudShare, Bahai, Books,
        ShoppingBagAdd, RotateLeft, FolderMinus, BedAlt, BookOpenReader, Target, Cloud, PhoneCross,
        Test, Road, Equality, CaretLeft, BadgeDollar, TimeQuarterPast, HourglassEnd, Music,
        BagsShopping, Gem, Ad, GrinStars, VideoPlus, ArrowDown, EnvelopeOpenText, Percentage,
        Question, LockAlt, CloudUpload, CarSide, GiftCard, Exchange, MapMarkerPlus, HatChef,
        EnvelopeDownload, Balloons, ArrowAltUp, TimeOclock, Feather, Carrot, GlobeAlt, Syringe,
        AngleSquareDown, Volleyball, Network, Flower, Tree, Sad, Bullseye, Scale, CommentSms,
        ArrowUpLeftFromCircle, Password, EclipseAlt, Comet, LightbulbDollar, GridAlt, MusicFile,
        Salad, CaretCircleRight, CalendarPen, Brush, Incognito, ArrowSmallDown, GasPumpAlt,
        ClockNine, Paint, Ambulance, VectorAlt, RulerTriangle, CloudDownload, Rec, Hastag,
        VenusMars, Angry, AngleSquareLeft, GarageCar, ArrowAltRight, Speaker, GrinAlt, Hiking,
        AlarmExclamation, UndoAlt, Rhombus, PhoneSlash, QuoteRight, ZoomOut, Raindrops,
        CommentExclamation, ArrowUpRight, Glasses, ArrowUp, Shrimp, ArrowSquareUp, BabyCarriage,
        CarMechanic, TruckMoving, SearchLocation, PhotoVideo, TvMusic, Coffee, Arrows,
        TachometerAltSlow, Pipette, Games, SignalAlt1, Tractor, Vector, PizzaSlice, Pyramid, Glass,
        DownLeftAndUpRightToCenter, ClockSeven, ArrowUpFromSquare, Tennis, Popcorn, Club,
        LayerMinus, CarBuilding, BadgeSheriff, Stopwatch, Tire, ArrowAltSquareLeft, Football,
        Camping, DraftingCompass, Confetti, Dice, Taxi, LaughSquint, DrinkAlt, SearchHeart,
        CloudShowersHeavy, Smoke, Gifts, Inbox, Fox, CloudsSun, TreasureChest, Gif, BarberShop,
        GrinBeam, LinkSlashAlt, ArrowTrendDown, Resize, Tablet, ChartPyramid, CandyAlt, Interlining,
        Calendars, Circle1, Square1, Italic, MugAlt, ChevronDoubleDown, FighterJet, Subway,
        Entertainment, LuggageRolling, GasPump, Dizzy, CarCrash, BreadSlice, Candy, Lettuce,
        BaseballAlt, HockeyPuck, FileChartPie, Reflect, Grimace, CannedFood, ChessRookAlt,
        SunriseAlt, ClockFourThirty, SmileWink, Fork, Tomato, CaretSquareLeft1, BowlingBall,
        WagonCovered, B, Blinds, Circle4, BowArrow, Luchador, Dart, SchoolBus, HatBirthday,
        GrinTongueSquint, KissWinkHeart, MehRollingEyes, Mug, Mushroom, Onion, ArrowFromRight,
        ChessClockAlt, Skating, TemperatureFrigid, AssistiveListeningSystems, N, ArrowsCross, Golf,
        Pepper, Plate, SaltPepper, Skewer, ArrowToRight, Tram, TruckMonster, D, U, BlindsOpen,
        Keynote, _3, _7, Square2, CakeWedding, ArrowToBottom, DiceOne, CloudSleet, Volcano,
        GasPumpSlash, Sleigh, ArrowAltToLeft, ClockSevenThirty, Democrat, I, P, R, BoxTissue,
        ObjectIntersect, ArrowFromTop, ArrowToLeft, Curling, Sledding, CaravanAlt, TireRugged,
        SortAlphaUpAlt, G, BlindsRaised, Bells, CircleDashed, CircleHalfStroke, ObjectSubtract, Yen,
        ArrowAltFromLeft, ShekelSign, F, BrainCircuit, CodeCommit, CodeSimple, MessageCode,
        RectangleBarcode, SquareTerminal, Circle0, Circle6, Circle7, Square4, Square6, Square7,
        BorderBottom, BorderCenterV, BorderNone, BorderOuter, CassetteVhs, TextWidth, BatteryFull,
        BatteryQuarter, BatteryThreeQuarters, DoorClosed, Hammer, HeadVr, LightSwitchOn,
        LightSwitch, BenchTree, BoxFragile, BoxOpenFull, BoxOpen, Fence, FireFlameCurved, HouseTree,
        IndustryWindows, IslandTropical, LuggageCart, MapMarkerCheck, MapMarkerSlash, Monument,
        Parking, Passport, PlaneProp, RampLoading, RouteInterstate, SeatAirline, SignHanging,
        SquarePlus, TrafficLightGo, WineGlassCrack, FileExcel, FilePowerpoint, SignalStream,
        WifiExclamation, HandHorns, HeartCrack, Bone, BurgerGlass, ArrowDownFromDottedLine,
        ArrowDownToDottedLine, ArrowTurnDownRight, ArrowUpSmallBig, Fax, MakeupBrush, TrainSide,
        Recycle, ArrowAltCircleUp, MoneyCheckEditAlt, ChessBoard, CarBattery, Whistle, BusAlt,
        Presentation, Sandwich, Poo, ClockTen, Radish, Spoon, Snowflakes, OilCan, Bowling, BandAid,
        TextCheck, Bold, ChartSetTheory, DiceD20, Highlighter, Earnings, FilePsd, Snowflake,
        WaterRise, BellSchool, Rugby, Cherry, Picnic, CaretCircleDown, CalendarExclamation,
        BookArrowRight, Stamp, Lemon, CarGarage, AngleDoubleSmallUp, VideoArrowUpRight,
        CommentArrowUp, GingerbreadMan, MugTea, EnvelopeBulk, ThermometerHalf, GrinSquintTears,
        BoxBallot, Lipstick, RedoAlt, AmusementPark, CaretCircleUp, FolderTimes, RubleSign,
        CarCircleBolt, Infinity, Skiing, Snowboarding, Dewpoint, A, RectanglePanoramic,
        FlipHorizontal, Sauce, Watermelon, DiceD12, DiceD4, HockeyMask, Meteor, SortNumericDown,
        Protractor, DiceFour, RugbyHelmet, Starfighter, Tally, UsbPendrive, FileEps, Cheese, Bike,
        SadCry, Pineapple, ArrowsH, ChessKingAlt, ChessKnight, ChessPawn, Dreidel, SkiingNordic,
        TachometerSlow, TachometerSlowest, ArrowAltToBottom, AlarmSnooze, ArrowUpSquareTriangle, _0,
        Skateboard, Cocktail, GrinWink, Broccoli, CloudHail, HockeySticks, CloudRain, Thunderstorm,
        CarBump, TachometerAverage, H, ArrowsFromDottedLine, Rainbow, Chocolate, Egg, BowlingPins,
        TemperatureDown, ThunderstormSun, TruckContainer, ClockEleven, C, SensorSmoke, Kiss, Smog,
        ThunderstormMoon, Snowmobile, Trailer, TruckPlow, ClockFiveThirty, ClockOneThirty, O,
        CarBolt, _2, _4, _9, Circle5, ObjectExclude, KissBeam, SkiLift, Hryvnia, E, Q, S, Square5,
        BookFont, ObjectUnion, Y, BarcodeRead, BarcodeScan, Barcode, CodeBranch,
        CodePullRequestClosed, FileCode, LinkHorizontalSlash, TablePivot, Square0, Square8,
        BorderInner, BorderLeft, BorderRight, BorderStyle, BringForward, BringFront, CassetteTape,
        BatterySlash, HammerWar, BookAtlas, BoxUp, Cabin, ConciergeBell, FishingRod, FlagCheckered,
        Fort, HotTub, HouseBlank, HouseChimneyBlank, HouseTurret, LandmarkAlt, MapMarkerQuestion,
        MapMarkerSmile, PeopleCarryBox, PlaneDeparture, PlaneTail, RollerCoaster, ShopLock,
        StoreLock, TablePicnic, TaxiBus, ToiletPaperBlank, TrafficLightStop, TrainTram,
        TreeDeciduous, UmbrellaBeach, FileExport, FileWord, Wifi1, FaceAwesome, HandPeace,
        HandsClapping, PeoplePants, SquareHeart, BurgerAlt, ArrowDownToSquare, Garage, TruckCouch,
        CashRegister, FileVideo, Humidity, Tired, Sushi, ExpandArrowsAlt, Mobile, ArrowFromBottom,
        Cars, SensorOn, CommentsDollar, Cricket, FlagUsa, MoneyBillWaveAlt, DiceThree, Sword, Venus,
        Grape, SortAmountUpAlt, Folders, Eclipse, EnvelopeOpenDollar, CocktailAlt, GameBoardAlt,
        BalanceScaleRight, CursorPlus, Shuttlecock, AirConditioner, ArrowUpToDottedLine,
        RectangleHorizontal, CompressAlt, Clouds, Steak, Snowplow, ArrowAltSquareUp, ArrowsFromLine,
        Flushed, ChessKing, Laugh, Peach, CaretSquareLeft, ExpandArrows, Cream, Underline, Compress,
        Ship, Corn, ChessBishop, DiceD8, CloudShowers, LineWidth, GrinBeamSweat, LaughWink,
        PodiumStar, CrystalBall, Circle2, CursorText, Noodles, Olives, Strawberry, LevelUp, Rv,
        Chair, FilmSlash, RulerVertical, ArrowsToLine, CoffeePot, Sausage, CaretQuareUp, DiceSix,
        WindWarning, CarWash, HelicopterSide, M, CloudDisabled, Cow, Blossom, Burrito, EggFried,
        FrenchFries, Hotdog, Taco, BasketballHoop, GolfBall, Sunset, TachometerFastest,
        SortAmountUp, Sensor, VideoArrowDownLeft, Aubergine, ArrowsAlt, ArrowFromLeft, GolfClub,
        Bus, CloudHailMixed, SnowBlowing, WaterLower, ArrowsAltV, ClockTwelveThirty, ChartScatter,
        Frown, MaskCarnival, Kite, ChevronDoubleUp, ChessRook, SkiJump, Fog, TachometerAltSlowest,
        ClockSixThirty, ClockThreeThirty, CarSideBolt, Republican, Typewriter, _1, GraphicTablet,
        Bacon, Garlic, Pumpkin, Hurricane, TemperatureUp, Windsock, TirePressureWarning,
        ArrowAltFromRight, ClockEightThirty, ClockElevenThirty, ClockTwelve, ClockTwoThirty, L, _8,
        GrinTongueWink, ArrowAltFromTop, ClockTenThirty, J, TextSlash, Circle8, AlbumCircleUser,
        Betamax, GalleryThumbnails, Lasso, TruckRamp, T, W, Z, Kerning, CodeCompare,
        CodePullRequest, DiagramProject, DisplayCode, LaptopCode, Qrcode, RectangleXmark,
        SidebarFlip, TableColumns, WrenchSimple, Square9, BorderAll, BorderStyleAlt, Cowbell,
        DistributeSpacingVertical, HighlighterLine, TextSize, BatteryBolt, BatteryEmpty,
        BatteryHalf, DoorOpen, HammerCrash, LightSwitchOff, Projector, Archway, Binoculars, Castle,
        HouseChimneyMedical, HouseChimneyWindow, HouseMedical, HouseWindow, Igloo,
        LocationCrosshairsSlash, LocationCrosshairs, MapMarkerEdit, ParkingCircle, ParkingSlash,
        RouteHighway, ShoePrints, MarkerTime, Money, LetterCase, Beer, TreeChristmas, Hourglass,
        MapMarkerCross, ArrowSquareDown, Motorcycle, ShieldPlus, TruckPickup, VideoSlash,
        ShieldInterrogation, Meh, HeartArrow, FileAi, IceCream, SortAlphaDown, Transform,
        ExchangeAlt, CaretSquareRight, CloudsMoon, DiceD10, ArrowsRepeat1, Resources, Bread,
        CaretSquareDown, Spade, TemperatureHigh, ArrowAltSquareDown, ArrowUpLeft, TimeForwardTen,
        Ftp, ToolCrop, ShipSide, Bottle, CommentText, Jpg, Pie, ArrowAltDown, Camcorder, CloudCheck,
        Package, Mars, GarageOpen, Tty, CommentArrowDown, CommentAltMiddleTop, Opacity, EnvelopeBan,
        LevelDown, BoxingGlove, BookArrowUp, AirFreshener, Circle3, SquareRoot, Soap, Sunrise,
        Racquet, CloudMoon, Heat, SortAmountDown, TimeHalfPast, Indent, Knife, Chess, CloudDrizzle,
        ReplyAll, SearchDollar, Terrace, FunnelDollar, ArrowsToDottedLine, ChessPiece, Party,
        LaughBeam, MehBlank, PepperHot, CloudRainbow, SpaceShuttle, TireFlat, Podium, PageBreak,
        ChessQueenAlt, ShuttleVan, SortAlphaUp, SortNumericDownAlt, K, RulerHorizontal,
        CommentSlash, ToolMarquee, CursorTextAlt, Surfing, OliveOil, ChessClock, Pan, ChessPawnAlt,
        FieldHockey, CloudSnow, Tachometer, ArrowAltToTop, ArrowsAltH, ClockOne, LiraSign,
        LinkSlash, Baseball, Billiard, GrinSquint, TemperatureLow, CarTilt, ArrowAltLeft,
        ArrowAltToRight, TimeForwardSixty, Equipment, Pound, RectabgleVertical, GrinTears,
        GrinTongue, Surprise, Melon, DiceTwo, CloudSunRain, Summer, CarBus, Braille,
        SortAlphaDownAlt, ClockNineThirty, ClockSix, MarsDouble, Sphere, Avocado, ArrowToTop,
        ArrowsHCopy, CloudMoonRain, RupeeSign, Tenge, _5, _6, Square3, Album, VenusDouble, Tornado,
        Jam, LevelDownAlt, Caravan, TachometerAltAverage, Circle9, CrossReligion,
        DistributeSpacingHorizontal, LevelUpAlt, OilTemp, ArrowAltFromBottom, V, Overline, CodeFork,
        CodeMerge, CodePullRequestDraft, LinkHorizontal, RectangleCode, Sidebar, SquareCode,
        TableLayout, TableRows, TableTree, AlbumCirclePlus, AlbumCollection, BorderCenterH,
        BorderTop, CowbellMore, GridDividers, LassoSparkles, TextHeight, BlockBrick, Block,
        Apartment, Bomb, City, DiamondTurnRight, Dungeon, Farm, FireSmoke, Gavel, Hotel,
        HouseBuilding, HouseChimneyCrack, HouseChimney, HouseCrack, LocationDotSlash, MapPin,
        ChartGantt, DiagramLeanCanvas, DiagramNested, DiagramSuccessor, SquareInfo, Background,
        Devices, Mockup, ReflectHorizontal, BookmarkSlash, InputNumeric, ScrollTorah, BellConcierge,
        EarthAfrica, EarthAsia, PersonSeatReclined, TruckTow, WaterLadder, CircleCalendar,
        ChartUser, DongSign, Envelopes, FlorinSign, LariSign, MillSign, PaperclipVertical,
        PenNibSlash, WonSign, BracketsRound, BracketsSquare, Microchip, Terminal, BlenderPhone,
        Bullhorn, MessageImage, MessageQuote, SmilePlus, Symbols, ArrowDownLeft, CircleQuarter,
        FilesMedical, HospitalUser, Inhaler, Joint, LaptopMedical, Microscope,
        PrescriptionBottleAlt, ScalpelPath, SmokingBan, Walker, FaceConfused, FaceDisguise,
        FaceExpressionless, FaceGrinTongueWink, FaceRelieved, FaceShush, FaceSwear, FaceTissue,
        PersonSimple, CommentAltMusic, PenFancy, RssAlt, SendBackward, SlidersHSquare, Speakers,
        Subscript, Superscript, Table, VolumeDown, SquareM, SquareS, BookSpells, FlaskPotion,
        HatWizard, HollyBerry, Joystick, PortalEnter, Radar, Transporter4, Transporter7,
        CloudQuestion, FileEdit, SealQuestion, TrashRestore, CoffeeBeans, Meat, CircleO, CircleW,
        Dog, CircleEllipsis, DialMax, DialOff, PenField, BlockQuote, CircleWaveformLines,
        FaceViewfinder, ForwardFast, StarSharpHalf, EyeDropperHalf, ListMusic, PenCircle, SaxHot,
        LeafMaple, TeddyBear, Wreath, HandScissors, ParachuteBox, Chimney, ScannerImage, BrailleC,
        BrailleG, BrailleNAlt, DiscDrive, HouseSignal, Satellite, SimCard, Tools, PersonCirclePlus,
        UserLock, HouseLeave, ShippingTimed, SolarPanel, Sprinkler, DryerAlt, Dryer,
        GaugeCircleBolt, GaugeCirclePlus, ConveyorBeltEmpty, HouseChimneyUser, ScannerGun, Shelves,
        Stairs, ToiletPaperBlankUnder, TruckContainerEmpty, TruckFlatbed, Dolphin, Trillium,
        KeyboardDown, LampStreet, LaptopArrowDown, LaptopSlash, MicrochipAi, TentArrowTurnLeft,
        BadgerHoney, Duck, Frog, Site, FamilyDress, FamilyPants, HatCowboySide, Ring, Socks,
        UserCowboy, CupStraw, MartiniGlassEmpty, HandHoldingMagic, Mace, Quiz, Second, Blueberries,
        Coconut, CrateEmpty, Potato, BowlScoop, FonduePot, TtyAnswer, Admin, CategoryAlt, ExitAlt,
        Process, SwipeRight, WorkflowSettingAlt, BrowserUi, Constellation, CloudCode, LandLayers,
        React, CustomerCare, FeaturesAlt, HrPerson, MagnetUser, TeamCheck, BicycleJourney, _404,
        Brightness, DiagramNext, DownRight, Up, HeadSideBrain, HeadSideCoughSlash, CopyImage,
        MoveToFolder, MemoPad, Notes, SpaghettiMonsterFlying, Tally2, Tally3, EarthAmericas,
        TicketsAirline, AustralSign, BookSection, BriefcaseBlank, BullseyeArrow, CentSign,
        ChartTreeMap, EnvelopeDot, HandsUsd, LightbulbSlash, ManatSign, MessageDollar,
        MessagesDollar, MoneyBillSimple, SignatureLock, SquareKanban, TugrikSign, Vault,
        BracketCurly, BracketRoundRight, BracketsCurly, BugSlash, LaptopMobile, WindowAlt,
        WindowMaximize, WindowMinimize, MessageQuestion, RectangleVertical, BookMedical, BookUser,
        BooksMedical, ClipboardUser, Crutches, FileMedicalAlt, FileMedical, Lungs, Skeleton, Virus,
        FaceGlasses, FaceParty, FaceUnamused, FaceWeary, HandBackPointLeft, PersonDress,
        SnowmanHead, Columns3, DrawSquare, H4, HeadSideHeadphones, Scrubber, StepBackward,
        VolumeOff, SquareC, SquareH, SquareL, SquareP, SquareR, Coffin, LightsHoliday, PoliceBox,
        Skull, StarShooting, Telescope, TombstoneAlt, UfoBeam, BellSlash, CircleQuartersAlt,
        CloudExclamation, FileCsv, PartyHorn, ToggleOff, BowlRice, BookCopy, CalculatorSimple,
        CircleD, CircleM, CircleU, Dharmachakra, WatchCalculator, WaveTriangle, PenSlash,
        PencilSlash, TrashCanClock, TrashSlash, VectorCircle, Aperture, CameraCctv,
        ClapperboardPlay, Panorama, StandardDefinition, RectangleVerticalHistory, TintSlash,
        Turntable, Webcam, ConveyorBelt, Dumpster, LampDesk, ShieldAlt, BrailleB, BrailleJ,
        BrailleK, BrailleO, HardHat, UserUnlock, Magnet, ScannerKeyboard, Sink, ToiletPaperSlash,
        BedEmpty, Drone, FanTable, Fan, Fireplace, Refrigerator, Angle90, Engine, Sickle, TruckBolt,
        PersonCarryBox, Unicorn, KeyboardLeft, MeterBolt, Mound, Pompebled, SnowflakeDroplets, Crow,
        Dove, RabbitFast, Spider, BuildAlt, ItAlt, Balloon, Child, ClothesHanger, HatWinter,
        Pool8Ball, ShirtLongSleeve, ShirtRunning, Transgender, UserTag, BowlSoftServe, CupcakeAlt,
        MugTeaSaucer, Award, AxeBattle, First, HockeyStickPuck, LacrosseStickBall, Cucumber,
        PanFood, Peapod, PepperAlt, Baguette, BreadSliceButter, CubesStacked, SaltShaker, Feedback,
        Journal, RankingStar, Review, SignUp, Subscription, TextBoxEdit, Category, ReferArrow,
        ComplianceClipboard, ChallengeAlt, DepositAlt, SafeBox, CarsCrash, Track, TrafficLightSlow,
        VestPatches, SignalStreamSlash, Wifi2, PeopleDress, CandyCorn, CheeseAlt, ArrowDownSmallBig,
        ArrowUpFromDottedLine, ChartMixed, ChartScatter3d, DiagramPrevious, DiagramSankey,
        SortShapesDown, Pattern, Replace, SmileyCommentAlt, BookQuran, EarthEuropa, Elevator,
        TicketAirline, BitcoinSign, BriefcaseArrowRight, FileSignature, HandHoldingUsd, MoneyBills,
        NfcMagnifyingGlass, RectanglePro, Shredder, SquarePollHorizontal, BanBug, BarsSort, Binary,
        BinarySlash, BracketCurlyRight, BracketSquareRight, Gears, KeySkeletonLeftRight, CircleUser,
        CommentAltMinus, CommentDots, Language, Messages, SquareQuote, CircleBolt, Split, BoneBreak,
        Bong, Hospital, MortarPestle, Pager, PrescriptionBottle, RadiationAlt, Toothbrush, UserMd,
        UserNurse, XRay, FaceAngryHorns, FaceDowncastSweat, FaceFearful, FaceLying, FacePleading,
        FaceSmileHearts, FaceSmileTongue, FaceSmilingHands, FaceTongueSweat, FaceWoozy, HandDots,
        HandHeart, HandsBubbles, MarsStrokeUp, PersonDressSimple, PipeSmoking, UsersGear,
        ObjectGroup, Podcast, SquareQ, SquareT, CoffinCross, Ornament, SpaceStationMoonAlt,
        SpiderWeb, StarChristmas, FileDownload, FileImage, FileUpload, GripLines, GripHorizontal,
        GripLinesVertical, HexagonExclamation, LightbulbQuestion, LightbulbExclamation,
        LocationExclamation, TimesHexagon, CircleC, CircleK, CircleR, Peace, PencilPaintbrush,
        Tilde, CircleTrash, DialMin, HexagonCheck, SquareEllipsisVertical, SquareEllipsis,
        CameraSlash, CameraViewfinder, Films, Screencast, StarSharpHalfStroke, TableList,
        DrumSteelpan, ObjectsColumn, RadioAlt, SprayCan, BallPile, Seedling, CalendarHeart,
        HandMiddleFinger, PersonDollyEmpty, Bath, Blender, DollyFlatbedAlt, HouseDay, IndustryAlt,
        Router, BrailleE, BrailleV, HouseUser, SatelliteDish, UserMinus, UserRobotXmarks, Lamp,
        LockOpenAlt, SirenOn, BedBunk, DroneAlt, PalletAlt, Frame, HoseReel, PhoneRotary,
        SprayCanSparkles, UtilityPole, Bird, PawClaws, Ram, Squid, Bugs, TentArrowDownToLine,
        Alicorn, CatSpace, DeerRudolph, It, SiteAlt, SiteBrowser, Boot, Family, HouseChimneyHeart,
        Piñata, UserMusic, UserNinja, Banana, CandySweet, WheatSlash, FirstAward, FirstLaurel,
        LacrosseStick, SecondMedal, ThirdAward, CanFood, Pear, PumpkinAlt2, BowlSpoon, Falafel,
        JugAlt, SushiAlt, Tamale, Live, Meeting, SubscriptionAlt, DescriptionAlt, DropDown, Route,
        TrafficLight, TrainSubwayTunnel, FilePdf, Wifi, CircleHeart, BreadLoaf, BurgerFries,
        ArrowsRetweet, AudioDescriptionSlash, ChartCandlestick, Cubes, DiagramCells, EarDeaf,
        HeadSideHeart, UniversalAccess, YinYang, Brain, HeadSideVirus, Bullet, GraphicStyle, Images,
        BookTanakh, MemoCircleCheck, Memo, Note, PersonPraying, Tally1, CalendarImage, CalendarWeek,
        BangladeshiTakaSign, BasketShoppingSimple, ChartSimple, DiagramVenn, IndianRupeeSign,
        MoneyBillsSimple, MoneySimpleFromBracket, NfcPen, NotebookAlt, PenClip, PollH, RupiahSign,
        SignatureSlash, SterlingSign, BinaryLock, BracketSquare, Memory, CommentMinus, MessageSlash,
        Rss, Right, SealExclamation, Bacterium, ClipboardPrescription, CommentMedical, Ear,
        FilePrescription, Hospitals, LungsVirus, MaskFace, NotesMedical, PrescriptionBottlePill,
        Smoking, TeethOpen, UserMdChat, VirusSlash, FaceMonocle, FacePensive, FaceSleeping,
        FaceSmileHalo, FaceSmileTear, FaceWorried, HandBackPointRibbon, UniformMartialArts,
        UserSlash, CameraSecurity, Eject, H1, H2, H3, Paragraph, PauseCircle, SlidersV, StepForward,
        VolumeSlash, SquareF, SquareG, SquareJ, SquareU, Pi, SquareV, Cauldron, FlaskPoison,
        HatSanta, KnifeKitchen, Mistletoe, Scarecrow, Tombstone, FileExclamation, FileImport,
        FileMinus, LightEmergencyOn, PartyBell, SignalBarsGood, SquareExclamation, TrashUndoAlt,
        TrashUndo, BowlChopsticksNoodles, Cheeseburger, FishCooked, MugMarshmallows, Stroopwafel,
        WineBottle, CircleF, CircleJ, CircleL, PlusMinus, Sigma, Theta, ValueAbsolute, DialHigh,
        PenClipSlash, TrashCanCheck, TrashList, TrashPlus, Clapperboard, Gramophone, Kazoo,
        PaintbrushPencil, PianoKeyboard, Piano, SquareDashed, Trumpet, WebcamSlash, CompassSlash,
        Icicles, PooBolt, TemperatureList, HandSparkles, PersonDolly, ComputerClassic, PrintSlash,
        Shovel, BrailleP, BrailleS, Ethernet, TrafficCone, PersonCircleMinus, DoNotEnter,
        ThermometerAlt, LightCeiling, Microwave, Oven, Pallet, Angle, Grate, Hose, Pump,
        VrCardboard, BoxCircleCheck, FireHydrant, Sheep, TreeAlt, Worm, FloppyDiskPen, MeterFire,
        Meter, SimCards, HouseTsunami, MattressPillow, SunPlantWilt, Tents, PersonSign, Scarf,
        UserHeadset, UserInjured, AppleCore, WheatAwn, BroomBall, CardDiamond, FirstMedal,
        HelmetBattle, Scroll, Staff, ThirdLaurel, ChartRadar, ChartScatterBubble, DownLeft,
        PersonWalkingWithCane, UpLeft, HeadSideCough, HeadSideMask, BlogText, BookCircleArrowUp,
        SquareMinus, CalendarDay, CalendarStar, CalendarXmark, HourglassStart, WatchSmart, Watch,
        BoxDollar, CalendarDays, CediSign, CruzeiroSign, FileCircleInfo, FloppyDiskCircleXmark,
        GuaraniSign, KipSign, ListDropdown, Nfc, PesoSign, PrintMagnifyingGlass, ShopSlash,
        Signature, BinaryCircleCheck, Browsers, FileBinary, Hdd, WindowRestore, CommentAltCheck,
        CommentAltDots, CommentAltEdit, CommentSmile, MessageArrowUp, MessagesQuestion, Voicemail,
        Hexagon, Left, SquareSmall, SquareStar, Eyes, HeartRate, HospitalSymbol, Radiation,
        MedicalStar, FaceCowboyHat, FaceDrooling, FaceIcicles, FaceMask, FaceNauseated,
        FacePersevering, FaceSleepy, FaceSmileUpsideDown, HandHoldingWater, SlidersVSquare,
        Waveform, SquareA, SquareB, SquareI, SquareO, SquareW, SquareX, Ghost, HandSpock,
        PlanetRinged, Scythe, Transporter3, Transporter6, UserAlien, UserVisor, DotCircle,
        GripVertical, LowVision, CookieAlt, GlassWhiskeyRocks, ChalkboardUser, CircleE, CircleN,
        CircleX, DialLow, Dial, TrashCheck, VectorPolygon, CameraRotate, GifSquare, ImagesUser,
        MusicAltSlash, MusicNote, RectangleList, Cello, Splotch, TriangleMusic, Anchor, Campfire,
        FeatherPointed, LeafOak, SunDust, ThermometerQuarter, Angel, BoxHeart, LeafHeart,
        ContainerStorage, DollyFlatbed, Flask, HouseNight, BrailleH, BrailleL, BrailleN, BrailleQ,
        BrailleW, WrenchAlt, PersonCircleCheck, PersonCircleXmark, UserCheck, ClipboardCheck,
        HouseReturn, Toilet, LampFloor, Washer, GrateDroplet, WindTurbine, ClockDesk, ShieldSlash,
        ToiletPaperUnder, Bee, KiwiBird, DisplayArrowDown, FireFlameSimple, FloppyDisks, Manhole,
        SdCards, TrianglePersonDigging, BagSeedling, FireBurner, MountainCity, Deer, HorseHead,
        Build, InventoryAlt, QrScan, GunSquirt, HatCowboy, CupStrawSwoosh, CupTogo, GlassEmpty,
        UserChef, CardClub, Dagger, FlyingDisc, MaskSnorkel, SecondAward, SecondLaurel, CitrusSlice,
        GarlicAlt, MushroomAlt, Olive, Peanut, BowlScoops, Donut, JarAlt, PanFrying, PlateWheat,
        ShishKebab, Waffle, NewspaperOpen, Newspaper, TextBox, Leave, SwipeLeft, Tap, ConditionAlt,
        PriorityImportance, WorkflowSetting, Workflow, Bucket, FlyInsect, LandLocation, Choose,
        Sofa, ArrowRightToBracket, ChartBullet, DiagramPredecessor, DiagramSubtask, Down, UpRight,
        WheelchairMove, HeadSide, Api, License, MoveToFolder2, Paste, ReflectVertical, RemoveFolder,
        TriangleWarning, CircleBookOpen, UserPilotTie, BarsStaggered, CartArrowDown,
        ChartSimpleHorizontal, ColonSign, FrancSign, ItalianLiraSign, NfcTrash, PhoneFlip,
        Trademark, HorizontalRule, BallotCheck, MessageBot, PaperPlaneTop, PhonePlus,
        CircleThreeQuarters, HeartHalfStroke, Cannabis, Capsules, CommentAltMedical, Crutch, Dna,
        ShieldVirus, Stomach, FaceAnguished, FaceAnxiousSweat, FaceDisappointed, FaceHandYawn,
        FaceSadSweat, FaceSmirking, FaceTongueMoney, FaceVomit, FaceZany, FaceZipper, HandBackFist,
        HandsHolding, MarsStrokeRight, UserPen, AlignSlash, Banjo, CameraMovie, Clipboard,
        DrawPolygon, Mp3Player, PenSquare, SendBack, Strikethrough, VolumeMute, WaveformPath,
        SquareD, SquareK, SquareZ, FluxCapacitor, PlanetMoon, Raygun, SolarSystem, SpaceStationMoon,
        Transporter2, Transporter, UserAstronaut, CheckCircle, LightEmergency, PlusHexagon,
        SignalBarsFair, StarExclamation, GlassChampagne, CircleB, CircleS, CircleV, CircleXmark,
        StarAndCrescent, TheaterMasks, Airplay, Command, GripDotsVertical, TrashCanPlus, TrashClock,
        BoltAuto, BoltSlash, DroneFront, HighDefinition, GuitarElectric, Mandolin, MusicSlash,
        Radio, Saxophone, Scribble, CloudMeatball, FlowerDaffodil, SnowmanAlt, ThermometerFull,
        GlobeSnow, HomeHeart, Ribbon, UserCrown, ConveyorBeltAlt, BrailleA, BrailleD, BrailleI,
        BrailleM, BrailleT, BrailleU, BrailleY, SdCard, PersonCircleQuestion, UserXmark,
        ScannerTouchscreen, SortCircleUp, SortCircle, Vacuum, CarRear, GaugeCircleMinus, Robot,
        PlaneSlash, ToiletPaperUnderSlash, TransformerBolt, TruckFront, UserPolice, CowAlt,
        Elephant, Hippo, Lobster, Otter, MeterDroplet, Locust, MosquitoNet, Mosquito, Pickaxe,
        PlantWilt, TentArrowLeftRight, TentArrowsDown, Cat, SkullCow, Squirrel, Discover,
        ShovelSnow, Sunglasses, HandFist, Medal, SwimmingPool, PineappleAlt, Custard,
        FlatbreadStuffed, GlassWaterDroplet, JarWheat, SushiRoll, Invite, SwipeUp, Condition,
        PriorityArrows, ExternalWorld, GalaxyStar, LightbulbSetting, Massage,
        RectangleHistoryCirclePlus, SquareUpRight, ChooseAlt, HrGroup, Selection, RefundAlt,
        Accident, TourGuidePeople, StreetView, TicketAlt, TrophyStar, People, PeopleArrowsLeftRight,
        BrightnessLow, ClosedCaptioningSlash, DownToLine, HandshakeAngle, KeyboardBrightnessLow,
        KeyboardBrightness, Octagon, Slash, SortSizeDown, SortSizeUp, FaceHeadBandage,
        HeadSideMedical, AnimatedIcon, AttributionPen, BrokenImage, FollowFolder, NoPeople,
        Picpeople, PicpeopleFilled, Template, TemplateAlt, CircleBookmark, InputText, Tally4,
        RestroomSimple, UserPilot, CalendarArrowDown, CartShoppingFast, FloppyDiskCircleArrowRight,
        FolderXmark, HouseLaptop, LitecoinSign, MoneyFromBracket, NfcLock, NfcSlash, PesetaSign,
        VoteYea, BarsFilter, Notdef, MessageArrowUpRight, MessageText, MessageXmark, WalkieTalkie,
        HeartHalf, ListTimeline, SquareBolt, HSquare, HandHoldingMedical, IdCardClipAlt, Kidneys,
        NoteMedical, Poop, Scalpel, WatchFitness, Baby, FaceBeamHandOverMouth, FaceNoseSteam,
        FaceRaisedEyebrow, FaceScream, FaceSmileHorns, FaceSunglasses, FaceThermometer,
        HandFingersCrossed, HandLove, HandPointRibbon, HandshakeSimpleSlash, PersonPregnant, Reel,
        BroadcastTower, Clarinet, ComputerSpeaker, FilmCanister, Heading, MicrophoneSlash,
        ObjectUngroup, ParagraphLeft, PenNib, PlayCircle, StopCircle, SquareE, SquareN,
        CandleHolder, HatWitch, PumpkinAlt, SkullCrossbones, Transporter5, Ufo, BatteryExclamation,
        CheckDouble, CircleExclamationCheck, Information, MinusCircle, MinusHexagon,
        RotateExclamation, ShareAltSquare, SignalAltSlash, TrashRestoreAlt, DrumstickBite,
        GlassCitrus, Cactus, CircleA, CircleG, CircleP, CircleQ, CircleY, StarOfDavid, _360Degrees,
        DeleteRight, TrashCanList, TrashCanSlash, TrashXmark, CircleCamera, CircleMicrophoneLines,
        CircleMicrophone, CircleVideo, CowbellCirclePlus, Drum, Flute, EarMuffs, ThermometerEmpty,
        ThermometerThreeQuarters, Trees, FileUser, HandPaper, DollyFlatbedEmpty, FaucetDrip,
        BrailleR, Digging, Forklift, TabletAndroidAlt, TvRetro, ArtificialIntelligence,
        LocationArrow, UserShield, UsersSlash, Loveseat, ShippingFast, Siren, SortCircleDown,
        Blanket, LightbulbOn, TankWater, TruckMedical, WindowFrame, ShieldKeyhole, ShieldXmark,
        Tape, UtilityPoleDouble, Crab, FishBones, Horse, Snake, TreesAlt, ComputerMouse,
        DesktopArrowDown, Pedestal, UserHelmetSafety, CloverAlt, Bat, Turtle, ItComputer, Qr,
        BlockQuestion, HandHoldingDroplet, HandsHeart, RingDiamond, ShirtTankTop, CandyBar, Boss,
        ParkingCircleSlash, PlaneArrival, TowerControl, Vest, WarehouseAlt, Sitemap, WifiSlash,
        HandLizard, Acorn, AppleCrate, CandyCane, Jug, ArrowDownTriangleSquare, ArrowLeftFromLine,
        ArrowTurnDownLeft, ChartWaterfall, SortShapesUp, AttributionPencil, Beacon, BlogPencil,
        DesktopWallpaper, Followcollection, IconStar, StarCommentAlt, TextShadow,
        BookCircleArrowRight, InputPipe, Escalator, PersonSeat, CalendarArrowUp, Snooze, BahtSign,
        CartMinus, Inboxes, NairaSign, NoteSticky, SquarePollVertical, StoreSlash, VoteNay,
        BracketRound, AddressCard, HundredPoints, MessageArrowDown, MessageSms, SquarePhoneHangup,
        CircleHalf, CircleStar, ShareSquare, Bacteria, Biohazard, Disease, Lips, Pills,
        Prescription, Procedures, PumpMedical, Stretcher, Tubes, UsersMedical, Viruses,
        FaceAstonished, FaceConfounded, FaceExplode, FaceEyesXmarks, FaceHushed, FaceThinking,
        HandBackPointDown, HandBackPointRight, HandHoldingSkull, HandWave, HandsHoldingDiamond,
        PuzzleAlt, ThoughtBubble, UserGear, CameraRetro, Clone, Eraser, FileAudio, Outdent,
        Swatchbook, SquareY, Alien, BookDead, ClawMarks, Galaxy, HoodCloak, PortalExit, Stocking,
        Transporter1, TransporterEmpty, Axe, UserRobot, DiamondExclamation, FileZipper, FolderOpen,
        SignalBarsWeak, ToggleOn, BowlChopsticks, CoffeeBean, GlassWhiskey, CircleH, CircleI,
        CircleT, CircleZ, WaveSine, WaveSquare, CircleEllipsisVertical, DialMedLow, DialMed,
        GripDots, PenFancySlash, PenSwirl, ImageSlash, Guitars, RectanglesMixed, Mountain, Sailboat,
        Mercury, Neuter, Faucet, Flashlight, BrailleX, BrailleZ, FireExtinguisher, Plug,
        Screwdriver, TabletAndroid, PersonCircleExclamation, Couch, DigitalTachograph, SoapAlt,
        TabletRugged, Shower, DumpsterFire, Moped, ShieldCross, VacuumRobot, WindowFrameOpen,
        ShieldMinus, ShowerDown, HorseSaddle, Monkey, DisplayMedical, DisplaySlash, GrillHotAlt,
        Dragon, Narwhal, Rabbit, SpiderBlackWidow, Whale, BootHeeled, Tshirt, CakeSlice, Badminton,
        GoalNet, QuizAlt, ScrollOld, SkiBootSki, Citrus, KiwiFruit, LeafyGreen, Butter, Flatbread,
        JugBottle, Pancakes, Popsicle, Answer, CatalogAlt, CatalogMagazine, InviteAlt, MeetingAlt,
        Rank, RankingPodium, TextBoxDots, WishlistHeart, WishlistStar, ArrowProgress, Mode,
        DirectionSignal, Chatbot, UserInterfaceUi, BuildingNgo, GovernmentUser, RegistrationPaper,
        Plan, TourVirtual, TaxAlt, Friday, Sunday, PhotoCapture, Customize, HexagonDivide,
        PlaceOfWorship, ToriiGate, BarberPole, TruckBox, PasswordAlt, Dinner, Mix, Banner3,
        CurveAlt, Nose, Picking, QueueAlt, Multiple, OvalAlt, Oval, RotateSquare, DominoEffect,
        Insight, Age, Trust, MegaphoneAnnouncementLeader, PickingBox, BenefitDiamond, LightbulbCfl,
        BrakeWarning, PigBankBulb, ThreeLeafClover, TruckFire, Mp3File, Mp4File, PptFile,
        FeedbackCycleLoop, SpeechBubbleStory, CandlePoseYoga, DownFromBracket, DisplayChartUp, Free,
        HouseCircleCheck, HouseFire, PreviousSquare, SurveyXmark, Auction, LeadershipAlt,
        OrganizationChart, SalaryAlt, NotFoundMagnifyingGlass, Customization, Floor, ShieldDog,
        SpringCalendar, OctagonMinus, OctagonXmark, PrayingHands, SquareDivide, Seal, Svg, AdPaid,
        BonusStar, Channel, TransformationDesign, FaceSunglassesAlt, MoneyBillTransfer,
        MoneyTransferSmartphone, AgeAlt, Life, SkillAlt, PlantSeedInvest, ShieldSecurityRisk,
        HandshakeDealLoan, LimitHand, PlugCircleMinus, _70sMusicDisc, BagShoppingMinus, Dropdown,
        PointerText, TrophyAchievementSkill, PaperPlaneLaunch, SunSalutationYoga, ChatBubbleCall,
        TimerClockCall, CloudGearAutomation, TurnLeftDown, MoneyWings, MapLocationTrack,
        SignPostsWrench, SignPosts, PlayMicrophone, CompassSouth, PriorityArrow, Algorithm,
        GalaxyAlt, Operation, UpRightFromSquare, Url, Budget, Leadership, Risk, FunctionProcess,
        Productivity, UxBrowser, FloorAlt, LionHead, Pollution, Integral, OctagonExclamation,
        RankingPodiumEmpty, SoldHouse, TruckArrowRight, Javascript, Otp, PasswordComputer, UiUx,
        PointOfSaleBill, GroceryBag, TransformationShapes, Pending, InfoGuide, ScrewAlt,
        LightbulbCflOn, HatBeach, Joker, PlantCare, PlantGrowth, ChartPieSimpleCircleDollar,
        UnderConstruction, UpFromBracket, CvvCard, ThirdMedal, WheatAwnCircleExclamation,
        BeerMugEmpty, DiaryClasp, FeedbackAlt, LiveAlt, RankingStars, Videoconference, ClearAlt,
        SwipeDown, ArrowsToEye, LandLayerLocation, PigFace, SourceData, GovernmentFlag,
        CalculatorMoney, Challenge, Compliance, DriverWoman, TrainStation, EmployeeAlt,
        EmployeeManAlt, Rent, Fail, LeaderboardAlt, UserSalary, ClockUpArrow, Drawer, CatHead, Ankh,
        GreaterThan, Analyse, BenefitPorcent, FeeReceipt, AgeRestrictionThree, Module, Spy,
        GuideAlt, RulesAlt, Skill, Blood, DocumentCircleWrong, GovernmentBudget, TimeWatchCalendar,
        IotAlt, Screw, SolarPanelSun, BenefitDiamondAlt, Referral, GreekHelmet, GolfHole,
        HorseshoeBroken, SystemCloud, RoadBarrier, HandshakeTrust, Treadmill, LocationPinCall,
        ChartLineUpDown, EndlessLoop, HouseCircleXmark, HouseCrackAlt, ForeignLanguageAudio,
        Replay10, SpainMap, PuzzlePieces, CarJourney, AuditAlt, Audit, Damage, GreaterThanEqual,
        LessThan, Omega, ExpenseBill, LawyerMan, Onboarding, SpeedometerKpi, Banner4,
        TransformationCircle, AgeRestrictionTwentyOne, ArrowComparison, PersonCv, Snap, LessonClass,
        ModelCubeArrows, StudentAlt, ArrowUpwardGrowthCrypto, PiggyBankBudget, CareerGrowth,
        LeadFunnel, Mortgage, RevenueEuro, Roulette, TruckUtensils, PuzzlePieceIntegration,
        ArrowsSplitUpAndLeft, GroupArrowsRotate, Replay30, CompassEast, CustomerService, Brand,
        Saturday, CustomizeComputer, Lion, BookHeart, TruckCheck, DocumentPaid, QueueLine, TipCoin,
        PeopleRoof, Muscle, GrowthChartInvest, BasketShoppingMinus, MemberSearch, ProgressUpload,
        ThunderstormRisk, AnatomicalHeart, DumbbellWeightlifting, BellNotificationCall, InboxFull,
        MailboxEnvelope, BasketShoppingPlus, HouseFlag, SeatbeltSafetyDriver, WineGlassEmpty,
        CardHeart, CardSpade, NestingDolls, HoneyPot, AnswerAlt, DiaryBookmarkDown, FeedbackHand,
        Description, AddImage, PlugCable, Deposit, Revenue, Total, EmployeeMan, LeaderAlt,
        Department, HandBill, DurationAlt, Tuesday, CrmComputer, SofaSize, BioLeaves, Waste,
        BellSchoolSlash, Workshop, LawyerWoman, PaymentPos, ConvertDocument, MembershipVip,
        PlanStrategy, RecipeBook, MultipleAlt, Effect, ModelCubeSpace, GiftBoxBenefits,
        LeadManagement, _00sMusicDisc, Desk, ArrowsToCircle, ChartMixedUpCircleCurrency,
        HighFiveCelebrationYes, ThumbsUpTrust, RunningTrack, ArrowsSplitRightAndLeft,
        HoldingHandGear, SummaryCheck, PostalAddress, RoadSignLeft, ErrorCamera,
        ReflectHorizontalAlt, CompassWest, Investment, TeamCheckAlt, DriverMan, RiskAlt,
        AssessmentAlt, Duration, NotFoundAlt, SpeedometerArrow, DogLeashed, PawHeart, Intersection,
        Om, WomanScientist, MarketplaceStore, Marketplace, Banner5, CurveArrow, AgeRestrictionZero,
        TorchInspirationLeader, SmartHome, UserCoach, UserTrust, OperatingSystemUpgrade,
        ChoirSinging, DumbbellFitness, FingerprintSecurityRisk, GroupCommunitySocialMedia,
        Excavator, TurnRight, RadarMonitoringTrack, CardinalCompass, CompassNorth, SleepingBag,
        CallDuration, NotFound, StageTheatre, WastePollution, OctagonPlus, SoldSignal,
        ReservationSmartphone, ReservationTable, Bonus, Kpi, MilkAlt, Recipe, TransformationBlock,
        TogetherPeople, Introduction, SkillUser, StoryBook, ChecklistTaskBudget, KeyLockCrypto, Iot,
        Scooter, ImproveUser, TalentHand, PlugCircleCheck, _60sMusicDisc, DropdownSelect,
        GlobePointer, MovFile, QuillPenStory, ScrollDocumentStory, CandleLotusYoga,
        HeartHealthMuscle, JumpingRope, BrokenChainLinkWrong, AnglesUpDown, Swap, ClipboardQuestion,
        FuelGauge, GpsNavigation, Lighthouse, TrainTrack, Skip15Seconds, StopSquare, SubtitlesSlash,
        Tax, CheckOutCalendar, Monday, Thursday, BoothCurtain, DrawerAlt, StageConcert, BadgeLeaf,
        Bio, ShieldCat, Bible, Chalkboard, EmptySet, Lambda, HairClipper, RegionPinAlt,
        PasswordEmail, Fee, KpiEvaluation, NoFee, Paid, Membership, Seller, GroceryBasket,
        InsertArrows, Insert, PersonShelter, SkinHair, PeopleNetworkPartner, PodiumVictoryLeader,
        StoreBuyer, PlugCircleExclamation, Meditation, PointerLoading, BalletDance, LoopSquare,
        RightFromBracket, InsertCreditCard, HouseCircleExclamation, LastSquare, ModeAlt,
        ExternalHardDrive, Pig, BudgetAlt, CalculatorBill, Invest, Guide, CustomizationCogwheel,
        Fabric, Violin, AirPollution, Pets, NotEqual, OctagonDivide, Token,
        BuildingCircleArrowRight, RegionPin, TruckArrowLeft, UserKey, PlateUtensils, UtensilsSlash,
        Banner2, Curve, AgeRestrictionEighteen, BookPlus, FunctionSquare, StoryFairyTale,
        StoryFantasy, SkinDrop, LeaderSpeech, WalletBuyer, CalendarPaymentLoan, EmployeeHandbook,
        CloudBackUpAlt, CloudBackUp, SmartHomeAlt, BenefitHand, Benefit, BonusAlt, ConveyorBeltArm,
        PlugCirclePlus, Webhook, MemberList, RadioButton, DashboardMonitor, AudienceMegaphone,
        TurnLeft, HouseLock, BlockMicrophone, Replay5, Mango, BottleDroplet, DiaryBookmarks,
        FeedbackReview, JournalAlt, Preview, WorkflowAlt, GalaxyPlanet, PlugAlt, MatchFire,
        RevenueAlt, ToDo, StateCountry, Legal, Loan, Expense, LeaderboardTrophy, DailyCalendar,
        Wednesday, CrmAlt, FloorLayer, Tie, CircleDivide, Hamsa, UsersClass, MosqueMoon,
        LockHashtag, PointOfSale, Milk, InsertAlt, Queue, AgeRestrictionSix, AgeRestrictionSixteen,
        MoneyCoinTransfer, ModelCube, Rules, BackUp, RoboticArm, BenefitIncrease, TalentAlt,
        DumbbellRay, MouseField, BagMapPin, TruckLadder, IpAddress, Burst, FolderFire,
        AirplaneWindowOpen, MapPoint, PersonLuggage, Features, Overview, Journey, TrainJourney,
        Branding, InsightHead, Leaderboard, CheckInCalendar, Shirt, FlowerButterfly, LessThanEqual,
        OctagonCheck, ScaleComparisonAlt, MosqueAlt, MarketplaceAlt, PadlockCheck, SellerStore,
        GraphCurve, InsertSquare, QueueSignal, TargetAudience, AgeRestrictionTwelve, InsightAlt,
        MoneyTransferAlt, Lesson, CircleOverlap, CalendarGavelLegal, _90sMusicDisc, SkeletonRibs,
        SpartanHelmet, Horseshoe, RecycleBin, ShieldTrust, CourtSport, IncenseSticksYoga,
        StrategyChessRisk, EmailPending, MailboxFlagUp, ArrowDownFromArc, ArrowLeftFromArc,
        ChartKanban, LeftFromBracket, CreditCardEye, ClipoardWrong, PauseSquare, RewindButtonCircle,
        Tricycle, BloodDropper, TrainStationBuilding, RentSignal, WalletArrow, VideoDuration, Ux,
        Blueprint, CustomizeEdit, Handmade, Divide, Gopuram, Kaaba, ManScientist, Practice, Script,
        UserGraduate, RazorBarber, Booking, HashtagLock, PasswordSmartphone, AgeRestrictionSeven,
        AgeRestrictionThirteen, Cryptocurrency, MoneyTransferCoinArrow, TrustAlt, Student,
        BloodTestTube, HoldingHandRevenue, Lead, ReferralAlt, PlugCircleBolt, _80sMusicDisc, Chip,
        Raccoon, LaptopBinary, ProgressComplete, ChartMixedUpCircleDollar, WebDesign,
        StationaryBike, BellNotificationSocialMedia, CalendarCall, GroupCall, PhoneGuide,
        ArrowLeftToArc, Wave, CircleNodes, OrderHistory, Resume, CarTunnel, SquareDashedCirclePlus,
        SurveillanceCamera, GlassHalf, MartiniGlassCitrus, WheatAwnSlash, Third, Walking, MelonAlt,
        Peanuts, SandwichAlt, Catalog, AdminAlt, DirectionSignalArrow, Refer, ChatbotSpeechBubble,
        PlugConnection, Completed, CoinUpArrow, Hr, ComplianceDocument, TabFolder, Crm, Stage,
        SunglassesAlt, Equals, Mosque, Synagogue, Vihara, AnalyseAlt, Visit, PointOfSaleSignal,
        DotPending, LightbulbHead, IntroductionHandshake, Function, BloodTestTubeAlt, Skin,
        CreditCardBuyer, HeartPartnerHandshake, ShoppingCartBuyer, CareerPath, ReferralUser,
        FlaskGear, SlotMachine, ProgressDownload, Branching, ChartPieSimpleCircleCurrency,
        UserSkillGear, ResistanceBand, CalendarBirhtdayCake, StarRatingCall, ArrowUpFromGroundWater,
        ArrowProgressAlt, RotateReverse, ArrowTurnLeftUp, CryptoCalendar, FreeDelivery,
        PayrollCheck, WhiteSpace, CompassAlt, Refund, AirplaneJourney, ToDoAlt, Leader, Assessment,
        BillArrow, CalendarSalary, DepartmentStructure, LimitSpeedometer, Knitting, Church,
        ScaleComparison, Banner, Cv, ExchangeCryptocurrency, ConvertShapes, SourceDocumentAlt,
        SourceDocument, SkinArrow, CalculatorMathTax, CalendarEventTax, ClockTimeTracking,
        MeasuringTape, General, Talent, BinBottles, DashboardPanel, InternetSpeedWifi,
        ToiletsPortable, ArrowUpToArc, FileCloud, InsertButtonCircle).sortedBy { it.name }
    return __Filled!!
  }
