package me.localx.icons.straight

import androidx.compose.ui.graphics.vector.ImageVector
import me.localx.icons.straight.bold.*
import kotlin.collections.List as ____KtList

private var __Bold: ____KtList<ImageVector>? = null

public val Icons.Bold.allIconsList: ____KtList<ImageVector>
  get() {
    if (__Bold != null) {
      return __Bold!!
    }
    __Bold = listOf(Search, Marker, Check, Home, User, MenuBurger, AngleRight, Heart, Cross,
        MenuDots, Bell, AngleLeft, Refresh, MemoCircleCheck, ShoppingCart, SignInAlt, Globe, Eye,
        UsersAlt, Dollar, Plus, Envelope, PaperPlane, Share, Download, AngleDown, Exit, Trash,
        TruckSide, PhoneCall, At, Car, Power, PlusSmall, BookAlt, Info, Flame, Stats, CassetteTape,
        Navigation, Computer, Users, Add, AlarmClock, Edit, MapMarker, World, Pencil, Building,
        CrossSmall, MapMarkerEdit, SettingsSliders, RocketLunch, Apps, AngleDoubleLeft,
        ChartHistogram, ArrowUpLeft, ShieldCheck, CrossCircle, RotateRight, TimePast,
        AngleDoubleRight, List, CarAlt, SearchAlt, AngleSmallLeft, Picture, Ban, Recycle,
        Smartphone, UserAdd, Comment, Calendar, ArrowRight, Exclamation, ArrowSmallDown, Settings,
        Expand, CarMechanic, Question, Checkbox, ListCheck, AngleUp, Lock, EyeCrossed, Enter, Bank,
        HoldingHandRevenue, WifiAlt, Interrogation, Earnings, Play, Comments, AngleCircleUp, Screen,
        Bookmark, Grid, Link, Coins, MusicAlt, SignalAlt2, ChatArrowDown, ArrowUpFromSquare, Crown,
        CommentAlt, Bullseye, SignalAlt1, Euro, Following, Stethoscope, QuoteRight, ShoppingBagAdd,
        ShoppingBag, Star, AppsAdd, TruckMoving, CommentHeart, BookCircleArrowUp,
        HandHoldingDroplet, ArrowUpRight, ArrowUpLeftFromCircle, ArrowSmallLeft, Document,
        Percentage, LinkAlt, HourglassEnd, Disk, ChartLineUpDown, Minus, Volume, Running, Shop,
        CaretDown, Shield, AddressBook, SteeringWheel, AngleSmallDown, Upload, Shuffle,
        HomeLocation, BadgeCheck, AngleDoubleSmallLeft, CommentCheck, Gym, CommentInfo, SearchHeart,
        RotateLeft, Key, Camera, SackDollar, TimerClockCall, Portrait, Diamond, Leaf, X, BellRing,
        Trophy, SocialNetwork, LayoutFluid, CalendarCheck, BookOpenCover, CircleHalfStroke, Print,
        Sparkles, Browser, Copy, Bolt, Football, AngleDoubleSmallDown, Clock, ArrowsRepeat,
        Stopwatch, PlayAlt, MinusSmall, AlignJustify, Paw, Sun, Microphone, Notebook, Gallery,
        Megaphone, Folder, BookBookmark, CirclePhone, CommentUser, Raindrops, Mars, ChartTree,
        CalendarGavelLegal, UsdCircle, AsseptDocument, Diploma, CloudDownload, ShieldExclamation,
        Circle, Box, CalendarClock, Qrcode, CreditCard, Headset, Hastag, Thumbtack, CommentQuestion,
        GraduationCap, Bulb, Taxi, Form, Spinner, CloudBackUpAlt, Wallet, Flag, EditAlt,
        FolderDownload, Doctor, Filter, Scissors, Map, CakeBirthday, Restaurant, N,
        UtilityPoleDouble, Interactive, Laptop, Moon, InboxIn, Database, ModePortrait, ChessRookAlt,
        CarCrash, P, Pulse, AlbumCircleUser, MoonStars, Cars, Calculator, CircleSmall, EnvelopeOpen,
        Confetti, _90sMusicDisc, TimeFast, Square, File, ZoomIn, Layers, LayerPlus, CommentQuote,
        CopyAlt, Fingerprint, DeleteUser, RectangleHorizontal, ChartNetwork, ThumbsUpTrust,
        Treatment, Physics, Venus, Gift, AgeRestrictionTwentyOne, B, CursorFinger, Duplicate,
        Tablet, CarWash, StoreAlt, D, Coin, WrenchSimple, TestTube, AlignCenter, ArrowCircleLeft,
        Biking, SortAlphaUpAlt, FolderUpload, Film, Wheelchair, Ballot, M, DraftingCompass,
        CommentCode, BoxAlt, LifeRing, Compress, Ship, ArrowUpwardGrowthCrypto, CloudShowersHeavy,
        FeedbackCycleLoop, FlagAlt, G, CashRegister, CommentAltEdit, MobileNotch, IdBadge, CaretUp,
        Bug, Humidity, SortAmountDownAlt, Donate, FileSpreadsheet, MoneyBillWaveAlt, ClipboardList,
        PlayPause, DeleteDocument, Asterik, ELearning, CompressAlt, Headphones, Bus, SortAlt,
        CalendarLines, W, QuestionSquare, RectangleXmark, TimeAdd, Delete, RemoveUser, Keyboard,
        EnvelopePlus, Hamburger, Wind, MicrophoneAlt, ChildHead, _60sMusicDisc, HouseFlood,
        CirclePhoneFlip, SensorFire, MindShare, ArrowTurnLeftUp, _3, TimeDelete, Fill, SignalAlt,
        AlignLeft, RoomService, Camping, StarOctogram, WomanHead, CarBuilding, Subway,
        AngleDoubleSmallRight, AnglesUpDown, ArrowAltFromTop, Handshake, ToolBox, _1, Sticker,
        VideoCamera, Italic, Underline, AppsDelete, Palette, SadTear, Stars, ChargingStation,
        Garage, ArrowAltCircleRight, SmileyCommentAlt, CalendarPlus, PiggyBank, ChairOffice,
        CommentDollar, Filters, BrainCircuit, CodeCompare, CodeSimple, _8, TimeForward, Umbrella,
        ItComputer, Symbol, Inbox, Archive, GrinHearts, Wheat, Water, TachometerFast, SortAmountUp,
        ChartScatter, Folders, F, ModelCubeSpace, FilterSlash, DisplayCode, NetworkCloud, Medicine,
        Tooth, Mobile, Sword, Rocket, Subtitles, EnvelopeMarker, CallMissed, Cupcake, MugAlt, Laugh,
        RingsWedding, ChartConnected, Guitar, Kite, FrenchFries, WaterBottle, ArrowAltToLeft,
        ArrowsAlt, Rv, CarGarage, Briefcase, UndoAlt, ShirtLongSleeve, Clip, HeadSideHeart,
        RubleSign, Badge, ArrowLeft, ModeLandscape, Undo, A, SearchLocation, TimeCheck, AddDocument,
        LockAlt, Receipt, Broom, Tree, Exchange, FileChartLine, MagicWand, TruckContainer,
        TruckLoading, FileInvoice, DataTransfer, Loading, Music, BadgePercent, S, PeoplePoll,
        PaintBrush, Ticket, ShieldSecurityRisk, Snowflake, CommentPen, Cursor, ArrowsHCopy, Boxes,
        Infinity, Pharmacy, Pound, Label, ArrowsAltH, CloudUpload, ToolCrop, Bed, DoNotEnter, Tags,
        Books, Comet, BedAlt, CircleEnvelope, ArrowTurnDownLeft, Hourglass, Unlock, Thunderstorm,
        CarSide, ArrowAltLeft, HandBackPointRight, TimeForwardSixty, School, Target, Bold,
        AppsSort, ZoomOut, ShieldPlus, Stop, Forward, Rewind, Flower, VenusMars, RecordVinyl,
        AngleSquareLeft, ClockThree, PhoneOffice, CloudCheck, ArrowDown, Cloud, TextCheck,
        Motorcycle, CommentsQuestion, CloudShare, CaretRight, Copyright, Pause, EnvelopeDownload,
        Gamepad, ArrowDownToSquare, GrinStars, AlbumCirclePlus, Heat, CalendarPen, BullseyePointer,
        Highlighter, LightEmergencyOn, LocationAlt, ChartPie, Gem, Grin, ChessQueenAlt, Meteor,
        InboxOut, Bahai, CommentExclamation, CommentArrowUp, ArrowRightToBracket, _2, _5, Network,
        AddFolder, SquareRoot, CaretLeft, LetterCase, Rec, Bike, ChartTreeMap, RedoAlt, ManHead,
        Glass, Arrows, Swimmer, CarBus, PlaneAlt, AngleSquareDown, C, V, SensorAlert, ArrowUpToArc,
        MarkerTime, Ambulance, PlayingCards, Volleyball, DocumentSigned, PokerChip, Hand, Indent,
        Book, Utensils, MapMarkerHome, Road, Cube, HeartArrow, AngleCircleRight, ArrowCircleDown,
        Hiking, TemperatureHigh, CarBattery, TvMusic, MobileButton, _0, Syringe, Feather, FileAi,
        UsbPendrive, Cheese, Triangle, Pyramid, Bottle, Egg, Whistle, EclipseAlt, Equality,
        BusinessTime, FunnelDollar, ShoppingBasket, LinkSlash, PageBreak, CommentText,
        LinkHorizontal, TimeQuarterPast, Backpack, Presentation, Scale, GlobeAlt, Soap, Surfing,
        Text, RectanglePanoramic, VectorAlt, CallHistory, Avocado, ExchangeAlt, EnvelopeOpenText,
        FloppyDiskPen, Skiing, GarageOpen, ArrowAltRight, ClockNine, BadgeDollar, ChartArea,
        FolderMinus, Q, CircleBookOpen, CommentSms, ArrowsRepeat1, Barcode, _4, UserTime, E,
        AngleSquareUp, Keynote, TreasureChest, PaintRoller, ArrowsCross, Spa, BarberShop, Dice,
        IceSkate, Reflect, Cookie, Mouse, BreadSlice, Butterfly, AgeRestrictionTwelve, BowArrow,
        ChessQueen, CloudSun, TemperatureFrigid, TireRugged, Tire, CalendarMinus, Calendars,
        EmployeesWomanMan, FolderTree, Mailbox, U, Gifts, GroupArrowsRotate, SquareTerminal,
        Circle1, EyeDropper, GrinBeam, CandyAlt, Tomato, TruckMonster, ClockFive, UsdSquare,
        Registered, SuitcaseAlt, PencilRuler, CommentXmark, _7, Circle7, SchoolBus, Basketball,
        Drumstick, DrinkAlt, LuggageRolling, GasPump, SmileWink, HatBirthday, ChartScatterBubble,
        Fork, Plate, Pot, BaseballAlt, DiceOne, HockeyPuck, SunriseAlt, ArrowAltFromLeft,
        SlidersVSquare, I, R, BadgeSheriff, BlindsOpen, Sack, ArrowUpSmallBig, CodeCommit,
        ClockSevenThirty, Gif, Yen, Resize, CupStrawSwoosh, Interlining, Train, FlowerTulip,
        DiscoBall, ChartPyramid, CakeWedding, Mushroom, Onion, Pepper, Turkey, Sort, ArrowSmallUp,
        CandlePoseYoga, CandleLotusYoga, BowlingBall, Curling, Luchador, PuzzlePiece, Skating,
        CloudsSun, Smoke, ArrowAltSquareRight, ShekelSign, DownFromBracket, CommentAltMusic,
        CommentAltDots, Circle4, Circle6, Square1, Golf, Dart, Fox, Happy, GlassCheers, Dizzy,
        Grimace, LaughSquint, Candy, CannedFood, Lettuce, Mug, SaltPepper, Skewer, CalendarLinesPen,
        DiceAlt, Sledding, CloudSleet, Volcano, CaravanAlt, FighterJet, FireFlameSimple, Sleigh,
        StrategyChessRisk, StarSharpHalf, Tram, WagonCovered, SlidersHSquare, ChevronDoubleDown,
        ClockFourThirty, ChessClockAlt, ClockTwo, Democrat, BlindsRaised, Blinds, BoxTissue,
        MoneyBillWave, TruckContainerEmpty, MessageCode, RectangleBarcode, Circle0, Square2,
        Square4, Square6, Square7, Bells, BorderBottom, BinaryCircleCheck, BorderNone, BorderOuter,
        CassetteVhs, CircleDashed, CheckInCalendar, ObjectIntersect, ObjectSubtract, TextWidth,
        BatteryFull, BatteryQuarter, BalanceScaleLeft, DoorClosed, Hammer, HeadVr, LightSwitch,
        BenchTree, BoxFragile, BorderCenterV, BoxOpen, Fence, HomeLocationAlt, HouseTree,
        IndustryWindows, IslandTropical, LinkSlashAlt, LuggageCart, Monument, MoneyTransferAlt,
        Parking, Passport, PlaneProp, RampLoading, RouteInterstate, SeatAirline, SignHanging,
        SquarePlus, ToiletPaperUnder, BellSchool, Lipstick, ArrowUp, Vector, Salad,
        LacrosseStickBall, CloudRain, Dewpoint, Tractor, CalendarExclamation, BarsProgress, O, Y,
        MusicFile, Glasses, PingPong, FileEps, Speaker, MapLocationTrack, ThermometerHalf,
        Chocolate, HamburgerSoda, ArrowsH, ArrowLeftToArc, DiceD20, ClockOneThirty, BabyCarriage,
        BusAlt, CarBump, EngineWarning, ClockSeven, GiftCard, Stamp, RulerTriangle, VideoPlus,
        ArrowsFromDottedLine, ArrowAltUp, BarcodeRead, BarcodeScan, TablePivot, _9, BandAid, Brush,
        FilePsd, PizzaSlice, Cocktail, Balloons, FlowerBouquet, Cherry, Sandwich, Spoon,
        AngleDoubleSmallUp, CaretCircleDown, RugbyHelmet, Snowflakes, TemperatureDown, GarageCar,
        Snowmobile, TruckPlow, AlarmSnooze, ClockFiveThirty, Ad, BagShoppingMinus, ConveyorBeltAlt,
        H, LayerMinus, PersonCarryBox, CodeBranch, Bowling, Skateboard, FlipHorizontal, TrainSide,
        Poo, SadCry, Broccoli, GingerbreadMan, Picnic, ArrowCircleUp, ArrowAltToBottom, ChessBoard,
        ChessKingAlt, Club, DiceFour, Snowboarding, CircleQuartersAlt, TachometerAverage,
        ArrowAltCircleUp, BoxBallot, Hryvnia, CarBolt, LightbulbDollar, Tally, PhotoVideo, Test,
        CommentAltMiddle, Protractor, MakeupBrush, Rugby, Carrot, Rainbow, Sad, GlassWaterDroplet,
        GrinSquintTears, GaugeCircleMinus, GrinWink, KissBeam, Kiss, Lemon, MugTea, Pineapple,
        Popcorn, Radish, Sauce, Watermelon, CaretCircleUp, BowlingPins, CheckOutCalendar,
        ChessKnight, ChessPawn, DiceD12, DiceD4, Dreidel, HockeyMask, HockeySticks, SkiingNordic,
        CloudHail, Smog, ThunderstormMoon, ThunderstormSun, WaterRise, OilCan, SkiLift, Starfighter,
        TachometerSlow, TachometerSlowest, Trailer, AgeRestrictionThirteen, AgeRestrictionSeven,
        SortNumericDown, CircleThreeQuarters, ClockEleven, ClockTen, CirclePhoneHangup,
        EnvelopeBulk, FolderTimes, SensorSmoke, FileCode, Circle5, Square0, Square5, Square8,
        BookFont, BookArrowRight, BorderInner, BorderLeft, BorderRight, BloodTestTube, BorderStyle,
        BringForward, BringFront, CommentAltMedical, ObjectExclude, ObjectUnion, BatterySlash,
        HammerWar, ItalianLiraSign, BookAtlas, BoxUp, Cabin, ConciergeBell, ChatBubbleCall,
        FileMedicalAlt, FishingRod, FlagCheckered, Fort, HotTub, HouseBlank, HouseTurret,
        LandmarkAlt, LinkHorizontalSlash, PlaneDeparture, PlaneTail, RollerCoaster, ExpandArrows,
        Pennant, ThermometerThreeQuarters, FlagUsa, T, DiagramProject, Dashboard, CursorPlus,
        PhonePause, SmileBeam, EggFried, Steak, Strawberry, BikingMountain, Eclipse, L, Z,
        AirConditioner, BoxCheck, CalendarArrowDown, SensorOn, MoneyCheck, CrystalBall, LineWidth,
        CursorText, Soup, Cow, Mountains, MugHot, Noodles, SnowBlowing, TruckCouch, PodiumStar,
        FileVideo, ArrowsToLine, Cream, Clouds, Grill, ChessKing, ChartScatter3d, DiceD6, DiceSix,
        Shuttlecock, Sunset, Windsock, Snowplow, TabletAndroidAlt, ArrowAltSquareUp, J,
        CommentsDollar, Republican, FilmSlash, Circle2, GraphicTablet, MaskCarnival, Flushed,
        CocktailAlt, Olives, Pumpkin, Sausage, ArrowsToCircle, LevelUp, BasketballHoop, ChessBishop,
        CartShoppingFast, Cricket, DiceThree, TemperatureUp, StoryFairyTale, TachometerFastest,
        ArrowAltFromRight, SmartHomeAlt, AlarmPlus, FaceTongueSweat, Chair, RulerCombined,
        TextSlash, Typewriter, CommentAltMinus, CommentImage, LaptopCode, TableColumns, TextSize,
        CloudDisabled, Lasso, Croissant, Frown, LaughWink, MartiniGlassCitrus, Tired, Aubergine,
        Bacon, Burrito, CoffeePot, Corn, Garlic, Grape, Hotdog, Peach, Sushi, Taco,
        ArrowSquareRight, ArrowSquareLeft, ChessKnightAlt, ChessRook, DiceD8, GolfBall, GolfClub,
        SkiJump, CloudDownloadAlt, CloudShowers, CloudHailMixed, Fog, Hurricane, WaterLower,
        WindWarning, HelicopterSide, TruckRamp, SignalStreamSlash, ClockTwelve, ClockTwelveThirty,
        Sensor, Kerning, RulerVertical, SidebarFlip, Circle8, Square9, _00sMusicDisc, Betamax,
        BorderAll, CarSideBolt, Cowbell, DirectionSignalArrow, GalleryThumbnails, HighlighterLine,
        BatteryBolt, BatteryEmpty, BatteryHalf, DoorOpen, HammerCrash, LightSwitchOff, Projector,
        Archway, Binoculars, Castle, HouseChimneyHeart, HoldingHandGear, HouseMedical, HouseWindow,
        Igloo, LocationCrosshairs, LockOpenAlt, LocationCrosshairsSlash, DownToLine, ParkingCircle,
        ParkingSlash, RouteHighway, ShoePrints, StreetView, TicketAlt, TrophyStar, VestPatches,
        Wifi2, People, PeopleDress, CandyCorn, CheeseAlt, HandshakeSimpleSlash, AnimatedIcon,
        AttributionPen, BrokenImage, FollowFolder, NoPeople, Pattern, Picpeople, PicpeopleFilled,
        Replace, Template, TemplateAlt, BookQuran, CircleBookmark, InputText, Tally4, EarthEuropa,
        Password, AppleWhole, Rhombus, GrinAlt, InternetSpeedWifi, Shrimp, ArrowAltToTop,
        ArrowLeftFromLine, ArrowAltDown, BagMapPin, RupeeSign, K, AlarmExclamation, TimeForwardTen,
        TimeOclock, TextBoxDots, ShieldInterrogation, Incognito, Money, Tennis, GridAlt, Package,
        Resources, CallOutgoing, Fish, Plane, CalendarEventTax, ReplyAll, SearchDollar, ArrowToTop,
        ArrowSquareUp, CodeFork, CodeMerge, LevelUpAlt, GasPumpAlt, _6, Ftp, ToolMarquee,
        CallIncoming, PhoneCross, ShipSide, TreeChristmas, MehBlank, HatChef, Jam, CloudRainbow,
        TemperatureLow, CarTilt, TireFlat, SortAmountDown, BenefitDiamondAlt, CloudUploadAlt,
        TableLayout, TableRows, TableTree, Jpg, Redo, Opacity, Beer, Coffee, MapMarkerCross, Meh,
        Sunrise, Terrace, Angry, GrinTears, LaughBeam, Bread, Knife, DialMedLow, OliveOil, Pan,
        CaretCircleRight, LevelDown, ArrowAltToRight, BoxingGlove, ChessPawnAlt, Chess, DiceD10,
        CloudMoon, CloudSnow, CloudsMoon, OilTemp, ShuttleVan, Tachometer, TruckPickup,
        AngleSmallUp, Tty, ClipboardListCheck, ClockSix, LiraSign, MoneyBillsSimple, BeerMugEmpty,
        AirFreshener, CaretSquareRight, BagsShopping, Camcorder, VideoSlash, CloudSunRain,
        RectangleCode, Circle3, Circle9, CowbellMore, ChessPiece, Baseball, Billiard, Transform,
        RectabgleVertical, EnvelopeBan, PhoneSlash, IceCream, MarsDouble, VenusDouble, Tornado,
        FerrisWheel, Sphere, GrillHotAlt, GrinSquint, GrinTongue, Surprise, Melon, PepperHot, Pie,
        ArrowDownTriangleSquare, ArrowAltSquareDown, CaretSquareDown, ChessClock, DiceTwo,
        FieldHockey, Racquet, Spade, CloudDrizzle, Summer, Caravan, SpaceShuttle, AngleSmallRight,
        Braille, SortDown, CheapStackDollar, ClockOne, ClockNineThirty, CircleEllipsisVertical,
        Podium, Tenge, Overline, RulerHorizontal, UserMdChat, CommentSlash, ArrowsToEye,
        CloudMoonRain, Sidebar, SquareCode, CrossReligion, Square3, AirplaneWindowOpen,
        AlbumCollection, Album, BorderTop, GridDividers, LassoSparkles, TextHeight, BlockBrick,
        Block, Apartment, Bomb, City, Dungeon, Farm, FireSmoke, Gavel, Hotel, HouseBuilding,
        HeadSideVirus, HouseChimney, HouseCrack, LocationPinCall, LocationDotSlash, MapPin,
        PenFancySlash, PlaneArrival, Route, TowerControl, TrafficLight, ToDoAlt, Vest, FilePdf,
        FileExcel, FilePowerpoint, SignalStream, WifiExclamation, HandHorns, PenNibSlash, Bone,
        HatCowboySide, Background, Devices, Mockup, ReflectHorizontal, BookmarkSlash, InputNumeric,
        ScrollTorah, BellConcierge, EarthAfrica, EarthAsia, TruckTow, WaterLadder, CircleCalendar,
        ChartUser, DongSign, Envelopes, Fax, FlorinSign, LariSign, MillSign, PaperclipVertical,
        MartiniGlassEmpty, WonSign, BatteryThreeQuarters, BracketsRound, BracketsSquare, Microchip,
        Terminal, BlenderPhone, Bullhorn, ChartPieAlt, MegaphoneAnnouncementLeader, MessageImage,
        MessageQuote, SmilePlus, Symbols, FilesMedical, HospitalUser, HouseCircleCheck, Inhaler,
        Joint, LaptopMedical, Microscope, ScalpelPath, SmokingBan, Walker, CircleQuarter,
        FaceConfused, FaceDisguise, FaceExpressionless, FaceRelieved, EyeDropperHalf, FaceShush,
        FaceSwear, FaceTissue, DisplayChartUp, GaugeCirclePlus, PersonSimple, CoffeeBeans, Meat,
        ArrowDownLeft, ArrowToRight, ArrowToBottom, ChartGantt, DiagramNested, DiagramSuccessor,
        Skip15Seconds, SquareInfo, HandHoldingMagic, PenFancy, RssAlt, SendBackward, QuillPenStory,
        Speakers, Dog, Subscript, Superscript, Table, VolumeDown, CircleO, CircleW, SquareM,
        SquareS, CloudQuestion, FileEdit, SealQuestion, PlugCircleCheck, TrashRestore, BookSpells,
        FlaskPotion, HatWizard, HollyBerry, Joystick, PortalEnter, Radar, ScrollDocumentStory,
        Transporter4, Transporter7, CircleEllipsis, DialMax, DialOff, PenField,
        ToiletPaperBlankUnder, BlockQuote, FaceViewfinder, ForwardFast, ListMusic, PenCircle,
        PrescriptionBottleAlt, SaxHot, LeafMaple, TeddyBear, Wreath, HandScissors, ParachuteBox,
        Chimney, ScannerImage, BrailleC, BrailleG, DiscDrive, HouseSignal, Satellite, SimCard,
        Tools, UserLock, HouseLeave, LightSwitchOn, ShippingTimed, SolarPanel, Sprinkler, DryerAlt,
        Dryer, GasPumpSlash, ScannerGun, Shelves, Stairs, TimeQuarterTo, TruckFlatbed, Dolphin,
        Trillium, ConveyorBeltEmpty, KeyboardDown, LampStreet, KeyLockCrypto, LaptopSlash,
        MicrochipAi, SpeechBubbleStory, BadgerHoney, Duck, Frog, Site, FamilyDress, FamilyPants,
        Ring, Socks, UserCowboy, CupStraw, Mace, Quiz, Second, Blueberries, Coconut, CrateEmpty,
        Potato, VideoCameraAlt, BowlScoop, FonduePot, TtyAnswer, Admin, _404, StoreLock, TaxiBus,
        ToiletPaperSlash, UmbrellaBeach, FileWord, FaceAwesome, HandPeace, HandshakeDealLoan,
        CopyImage, ChartSetTheory, MemoPad, Notes, SignPostsWrench, Tally2, Tally3, EarthAmericas,
        TicketsAirline, AustralSign, BookSection, BriefcaseBlank, BullseyeArrow, CentSign,
        EnvelopeDot, HandsUsd, HouseChimneyBlank, LightbulbSlash, ManatSign, MessageDollar,
        MessagesDollar, MoneyCheckEditAlt, SignatureLock, SquareKanban, TugrikSign, Vault,
        _70sMusicDisc, BracketCurly, BracketsCurly, BracketRoundRight, BugSlash, LaptopMobile,
        WindowAlt, WindowMaximize, WindowMinimize, BreadSliceButter, MessageQuestion, BookMedical,
        BookUser, BooksMedical, ClipboardUser, Crutches, FileMedical, Lungs, Skeleton, Virus,
        RectangleVertical, BowlSoftServe, FaceGlasses, FaceParty, CodePullRequestClosed,
        FaceUnamused, FaceWeary, PersonDress, SnowmanHead, ArrowUpSquareTriangle, BowlRice,
        Brightness, DiagramNext, DownRight, HeadSideHeadphones, RightFromBracket, Up, Columns3,
        DrawSquare, H4, Scrubber, StepBackward, VolumeOff, BookCopy, CalculatorSimple, CircleD,
        CircleM, CircleU, Dharmachakra, Sink, WatchCalculator, WaveTriangle, SquareC, SquareH,
        SquareL, SquareP, SquareR, BellSlash, CloudExclamation, FileCsv, PartyHorn, ToggleOff,
        TrashCanClock, Coffin, LightsHoliday, PoliceBox, Skull, StarShooting, Telescope,
        TombstoneAlt, UfoBeam, FileInvoiceDollar, PenSlash, PencilSlash, TrafficLightStop,
        TrashSlash, VectorCircle, Aperture, CameraCctv, ClapperboardPlay, Panorama,
        StandardDefinition, TintSlash, Turntable, Webcam, PaperPlaneLaunch, ConveyorBelt, Dumpster,
        LampDesk, ShieldAlt, BrailleB, BrailleJ, BrailleK, BrailleO, HardHat, PeopleNetworkPartner,
        NotFoundMagnifyingGlass, UserUnlock, Magnet, ScannerKeyboard, BedEmpty, Drone, FanTable,
        Fan, Fireplace, Refrigerator, Angle90, Engine, Sickle, TruckBolt, MugTeaSaucer, Unicorn,
        KeyboardLeft, MeterBolt, TurnLeftDown, Mound, Pompebled, SnowflakeDroplets, Crow, Dove,
        RabbitFast, Spider, BuildAlt, ItAlt, Balloon, Child, ClothesHanger, HandBackPointLeft,
        HatWinter, ShirtRunning, Transgender, UserTag, CupcakeAlt, Award, AxeBattle, First,
        Pool8Ball, Cucumber, PanFood, Peapod, PepperAlt, Baguette, CubesStacked, SaltShaker,
        Feedback, Elevator, TicketAirline, BitcoinSign, BracketSquareRight, FileSignature,
        MoneyBills, RectanglePro, Shredder, SquareEllipsisVertical, BanBug, BarsSort, Binary,
        BinarySlash, Gears, CircleUser, CommentDots, Language, Messages, NfcMagnifyingGlass,
        SquareQuote, BoneBreak, Bong, Hospital, MortarPestle, Pager, PrescriptionBottle,
        RadiationAlt, Toothbrush, UserMd, UserNurse, XRay, CircleBolt, Split, FaceAngryHorns,
        FaceFearful, FaceLying, FacePleading, FaceSmileHearts, FaceSmileTongue, FaceWoozy, HandDots,
        HandHeart, HandHoldingUsd, HandsBubbles, HandMiddleFinger, LightbulbCflOn, PipeSmoking,
        UsersGear, ArrowSmallRight, ChartMixed, DiagramPrevious, DiagramSankey, GripLinesVertical,
        ObjectGroup, Podcast, CircleC, CircleK, CircleR, Peace, PencilPaintbrush, Tilde, SquareQ,
        SquareT, ChevronDoubleUp, FileDownload, FileImage, FileUpload, GripHorizontal, GripLines,
        HexagonExclamation, LightbulbQuestion, LightbulbExclamation, LocationExclamation,
        ShoppingCartAdd, RankingPodiumEmpty, TimesHexagon, CoffinCross, Ornament, SpiderWeb,
        StarChristmas, CircleTrash, DialMin, HexagonCheck, SprayCanSparkles, SquareEllipsis,
        CameraSlash, CameraViewfinder, Films, Screencast, TableList, DrumSteelpan, ObjectsColumn,
        RadioAlt, SprayCan, BallPile, Seedling, CalendarHeart, Bath, Blender, HouseDay, IndustryAlt,
        Router, BrailleE, BrailleV, HouseUser, SatelliteDish, SortShapesDown, UserMinus, Lamp,
        SirenOn, BedBunk, DroneAlt, PalletAlt, Frame, GameBoardAlt, HoseReel, PhoneRotary,
        UserRobotXmarks, UtilityPole, Bird, PawClaws, Ram, Squid, Bugs, FaceSmilingHands,
        PumpkinAlt2, Alicorn, CatSpace, DeerRudolph, It, SiteAlt, SiteBrowser, Boot, Family,
        GrinBeamSweat, Piñata, PointOfSaleBill, UserMusic, UserNinja, Banana, CandySweet,
        MarsStrokeUp, WheatSlash, UpRightFromSquare, FirstAward, FirstLaurel, FaceDowncastSweat,
        LacrosseStick, SecondMedal, ThirdAward, CanFood, Pear, BowlSpoon, Falafel, JugAlt, SushiAlt,
        Tamale, Live, Meeting, SubscriptionAlt, DescriptionAlt, DropDown, ModeAlt, ArrowsFromLine,
        PriorityArrow, Algorithm, GalaxyAlt, Operation, Pig, Url, BudgetAlt, Budget, CalculatorBill,
        Invest, Guide, PlugCirclePlus, Leadership, Risk, FunctionProcess, Productivity, UxBrowser,
        Builder, DollyFlatbedAlt, CustomizationCogwheel, Fabric, FloorAlt, SignalBarsGood, Wifi,
        CircleHeart, BreadLoaf, BurgerFries, Brain, Bullet, GraphicStyle, Images, MoneyCoinTransfer,
        BookTanakh, Memo, Note, PersonPraying, Tally1, CalendarImage, CalendarWeek,
        AudioDescriptionSlash, BoxCircleCheck, ChartSimple, DiagramVenn, NfcPen, NotebookAlt,
        PenClip, PollH, PrescriptionBottlePill, RupiahSign, SignatureSlash, SterlingSign,
        BinaryLock, BracketSquare, Memory, ClockUpArrow, CommentMinus, MessageSlash, Rss, Bacterium,
        ClipboardPrescription, CommentMedical, Ear, FaceSmileTear, FilePrescription, Hospitals,
        LungsVirus, MaskFace, NotesMedical, Smoking, TeethOpen, VirusSlash, Right, SealExclamation,
        EmployeeManAlt, DiamondTurnRight, FaceMonocle, FacePensive, FaceSleeping, FaceSmileHalo,
        FaceWorried, HandHoldingSeedling, CommentArrowDown, UserSlash, Cheeseburger, FishCooked,
        MugMarshmallows, Stroopwafel, WineBottle, AgeRestrictionThree, AgeRestrictionSix,
        ArrowsRetweet, ChartCandlestick, BowlChopsticksNoodles, Cubes, DiagramCells, EarDeaf,
        UniversalAccess, YinYang, CameraSecurity, Eject, H1, H2, H3, Paragraph, PauseCircle,
        SlidersV, StepForward, VolumeSlash, CircleF, CircleJ, CircleL, Pi, Oven, PlusMinus, Sigma,
        SortAlphaDownAlt, Theta, ValueAbsolute, SquareF, SquareG, SquareJ, SquareU, SquareV,
        FileExclamation, FileImport, FileMinus, LandLayerLocation, PartyBell, SquareExclamation,
        TrashUndo, Cauldron, FlaskPoison, HatSanta, KnifeKitchen, Mistletoe, Scarecrow,
        SortAlphaDown, Tombstone, DialHigh, TrashList, TrashPlus, Clapperboard, SortNumericDownAlt,
        SolarPanelSun, Gramophone, Kazoo, PaintbrushPencil, PianoKeyboard, Piano, SquareDashed,
        Trumpet, WebcamSlash, CompassSlash, Icicles, PooBolt, TemperatureList, HandSparkles,
        PersonDolly, ComputerClassic, PrintSlash, Shovel, BrailleP, BrailleS, Ethernet, TrafficCone,
        PersonCircleMinus, ThermometerAlt, LightCeiling, Microwave, Pallet, Angle, Grate, Hose,
        Pump, ShoppingCartCheck, VrCardboard, FireHydrant, TimeWatchCalendar, TimeHalfPast, Sheep,
        TreeAlt, Worm, MeterFire, Meter, SimCards, HouseTsunami, MattressPillow, Tents, PersonSign,
        Scarf, UserHeadset, UserInjured, AppleCore, WheatAwn, BroomBall, CardDiamond, FirstMedal,
        HelmetBattle, Scroll, Staff, ThirdLaurel, ThirdMedal, Mango, BottleDroplet, BorderCenterH,
        DiaryBookmarks, HeartCrack, BurgerGlass, HeadSideCough, BlogText, Squircle, MehRollingEyes,
        SquareMinus, PersonCircleXmark, TrafficLightGo, BoxOpenFull, CalendarDay, CalendarStar,
        CalendarXmark, HourglassStart, WatchSmart, Watch, BoxDollar, CalendarDays, CediSign,
        CruzeiroSign, GuaraniSign, HandHoldingBox, KipSign, ListDropdown, ModelCubeArrows, Nfc,
        PesoSign, ShopSlash, Signature, ScaleComparisonAlt, Browsers, FileBinary, Hdd,
        WindowRestore, CommentSmile, MessagesQuestion, Voicemail, Eyes, GrinTongueSquint, HeartRate,
        HospitalSymbol, PiggyBankBudget, Radiation, MedicalStar, ChartLineUp, HeadSideMask, Hexagon,
        Left, SquareSmall, SquareStar, FaceDrooling, FaceCowboyHat, FaceIcicles, FaceMask,
        FaceNauseated, FacePersevering, FaceSleepy, GreaterThanEqual, GlassWhiskeyRocks,
        MailboxFlagUp, CookieAlt, ArrowDownFromArc, ChartRadar, CreditCardEye, DownLeft, UpLeft,
        RewindButtonCircle, Waveform, ChalkboardUser, CircleE, CircleN, CircleX, SquareA, SquareB,
        SquareI, SquareO, SquareW, SquareX, DotCircle, FireFlameCurved, GripVertical, LowVision,
        PersonCircleCheck, Ghost, HandSpock, PlanetRinged, Scythe, Transporter3, Transporter6,
        UserAlien, UserVisor, DialLow, Dial, MessageArrowUp, TrashCheck, VectorPolygon,
        CameraRotate, CaretSquareLeft1, CommentAltCheck, GifSquare, ImagesUser, MusicNote,
        RectangleList, Cello, Splotch, TriangleMusic, Anchor, Campfire, FeatherPointed, LeafOak,
        SunDust, ThermometerQuarter, Angel, BoxHeart, HandHoldingWater, LeafHeart, ContainerStorage,
        DisplayArrowDown, DollyFlatbed, Flask, HouseNight, BrailleH, BrailleL, BrailleN, BrailleQ,
        BrailleW, WrenchAlt, UserCheck, ClipboardCheck, HouseReturn, MenuDotsVertical, Toilet,
        LampFloor, Washer, FileCircleInfo, GrateDroplet, WindTurbine, ClockDesk, FileChartPie,
        ShieldSlash, LessThanEqual, Bee, KiwiBird, BadgetCheckAlt, FloppyDisks, Manhole, SdCards,
        BagSeedling, FireBurner, MountainCity, PuzzlePieceIntegration, Deer, HorseHead,
        LeftFromBracket, Build, InventoryAlt, QrScan, GunSquirt, HatCowboy, ArrowTrendDown,
        KissWinkHeart, CupTogo, GlassEmpty, UserChef, CardClub, Dagger, FlyingDisc, ArrowToLeft,
        MaskSnorkel, SecondAward, SecondLaurel, CitrusSlice, GarlicAlt, MushroomAlt, Olive, Peanut,
        BowlScoops, Donut, JarAlt, PanFrying, PlateWheat, ShopLock, TablePicnic, TimeTwentyFour,
        TourGuidePeople, TrainTram, TreeDeciduous, VideoArrowUpRight, FileExport, Wifi1,
        HandsClapping, PeoplePants, SquareHeart, BurgerAlt, HeadSide, HandBackFist, Api, License,
        MarsStrokeRight, Paste, ReflectVertical, RemoveFolder, SignOutAlt, StarAndCrescent,
        TriangleWarning, BasketShoppingPlus, BarsStaggered, BasketShoppingMinus,
        BellNotificationCall, ChartMixedUpCircleDollar, ColonSign, FaceTongueMoney, FaceSadSweat,
        FrancSign, MugHotAlt, NfcTrash, PhoneFlip, Trademark, HorizontalRule, BallotCheck,
        MapMarkerSmile, MessageBot, PhonePlus, SpaceStationMoon, Cannabis, Capsules, CartArrowDown,
        Crutch, Dna, ShieldVirus, Stomach, FaceAnguished, FaceAnxiousSweat, FaceDisappointed,
        FaceHandYawn, FaceSmirking, FaceVomit, FaceZany, FaceZipper, GrowthChartInvest,
        GripDotsVertical, HandsHolding, PeopleCarryBox, UserPen, GlassChampagne, CarCircleBolt,
        ArrowTrendUp, ChartBullet, _80sMusicDisc, DiagramPredecessor, DiagramSubtask, Down,
        SortCircleUp, UpRight, WheelchairMove, AlignSlash, Banjo, CameraMovie, Clipboard,
        DrawPolygon, Mp3Player, PenSquare, SendBack, Strikethrough, VolumeMute, WaveformPath,
        CircleB, CircleS, CircleV, CircleXmark, TheaterMasks, SquareD, SquareK, SquareZ,
        CheckCircle, LightEmergency, PlusHexagon, StarExclamation, FluxCapacitor, PlanetMoon,
        Raygun, SolarSystem, Transporter2, Transporter, UserAstronaut, Airplay, Command, TrashClock,
        BoltAuto, BoltSlash, DroneFront, HighDefinition, MoveToFolder2, GuitarElectric, Mandolin,
        MusicSlash, Radio, Saxophone, Scribble, CloudMeatball, FlowerDaffodil, SnowmanAlt,
        ThermometerFull, GlobeSnow, HomeHeart, Ribbon, UserCrown, BrailleA, BrailleD, BrailleI,
        BrailleM, BrailleT, BrailleU, BrailleY, SdCard, UserPilotTie, UserXmark, ScannerTouchscreen,
        SignalBarsFair, SortCircle, Vacuum, CarRear, Robot, PlaneSlash, TentArrowsDown,
        TransformerBolt, TruckFront, UserPolice, CowAlt, Elephant, Hippo, Lobster, Otter,
        MeterDroplet, Locust, MosquitoNet, Mosquito, Pickaxe, PlantWilt, Cat, SkullCow, Squirrel,
        Discover, HeartHalfStroke, ShovelSnow, Sunglasses, MapMarkerQuestion, TrashCanPlus,
        HandFist, Medal, SwimmingPool, PineappleAlt, Custard, RestroomSimple, UserPilot,
        CaretSquareLeft, FolderXmark, HouseLaptop, LitecoinSign, MoneyFromBracket, NfcLock,
        NfcSlash, PesetaSign, VoteYea, BarsFilter, Notdef, CoinUpArrow, MessageText, MessageXmark,
        WalkieTalkie, HSquare, Kidneys, NoteMedical, Poop, Scalpel, WatchFitness, HeartHalf,
        ListTimeline, SquareBolt, Baby, EnvelopeOpenDollar, FaceScream, FaceRaisedEyebrow,
        FaceNoseSteam, FaceSunglasses, FaceThermometer, HandLove, PersonPregnant, Reel,
        DrumstickBite, GlassCitrus, ArrowCircleRight, ArrowUpFromGroundWater, BrightnessLow,
        HandshakeAngle, KeyboardBrightness, Octagon, Slash, BroadcastTower, Clarinet,
        ComputerSpeaker, FilmCanister, Heading, MicrophoneSlash, ObjectUngroup, ParagraphLeft,
        PenNib, PlayCircle, StopCircle, Cactus, CircleA, CircleG, CircleP, CircleQ, CircleY,
        SquareE, SquareN, BatteryExclamation, CheckDouble, CaretQuareUp, Information, MinusCircle,
        MinusHexagon, RotateExclamation, SignalAltSlash, CandleHolder, HatWitch, PumpkinAlt,
        SkullCrossbones, Transporter5, Ufo, _360Degrees, ChatbotSpeechBubble, DeleteRight,
        StarRatingCall, TrashXmark, CircleCamera, CircleExclamationCheck, CircleVideo,
        CircleMicrophone, Drum, Flute, EarMuffs, ThermometerEmpty, Trees, FileUser, HandPaper,
        DiaryBookmarkDown, FaucetDrip, BrailleR, BorderStyleAlt, Digging, Forklift, TvRetro,
        ArtificialIntelligence, LocationArrow, PeopleArrowsLeftRight, UserShield, UsersSlash,
        Loveseat, ShippingFast, Siren, SortCircleDown, Blanket, LightbulbOn, TankWater,
        TruckMedical, WindowFrame, BloodTestTubeAlt, ShieldKeyhole, ShieldXmark, Tape, Crab,
        FishBones, Horse, Snake, TreesAlt, ComputerMouse, DesktopArrowDown, Pedestal, CloverAlt,
        TachometerAltSlowest, StarOfDavid, Bat, Turtle, Qr, BlockQuestion, HandsHeart, RingDiamond,
        CandyBar, GlassHalf, IdCardClipAlt, CardHeart, CardSpade, NestingDolls, Third, Walking,
        MelonAlt, Peanuts, PointOfSaleSignal, GiftBoxBenefits, HoneyPot, SandwichAlt, AnswerAlt,
        Catalog, FeedbackHand, SortSizeUp, AdminAlt, Description, Refer, WineGlassEmpty, AddImage,
        PlugCable, PlugConnection, MessageArrowUpRight, ComplianceDocument, Deposit, Revenue, Total,
        Boss, Completed, Hr, EmployeeMan, LeaderAlt, TabFolder, Department, HandBill, DurationAlt,
        Tuesday, CrmComputer, Crm, Assign, Employees, WarehouseAlt, Sitemap, WifiSlash, HandLizard,
        Acorn, AppleCrate, CandyCane, Jug, FaceEyesXmarks, HeadSideThinking, AttributionPencil,
        Beacon, BlogPencil, DesktopWallpaper, Followcollection, IconStar, TextShadow, BookArrowUp,
        ArrowsToDottedLine, InputPipe, Escalator, PersonSeat, Snooze, BahtSign, CartMinus,
        FingerprintSecurityRisk, Inboxes, InsertButtonCircle, MessageArrowDown, NairaSign,
        NoteSticky, StoreSlash, VoteNay, BracketRound, HandsHoldingDiamond, AddressCard,
        HundredPoints, MessageSms, Bacteria, Biohazard, Disease, Lips, Pills,
        PersonCircleExclamation, Prescription, Procedures, PumpMedical, Stretcher, Tubes,
        UsersMedical, Viruses, AngleCircleLeft, CircleHalf, CircleStar, ShareSquare, FaceAstonished,
        FaceConfounded, CursorTextAlt, FaceExplode, FaceHushed, CommentAltMiddleTop,
        CodePullRequestDraft, FaceThinking, HandBackPointDown, ClockTimeTracking, HandWave,
        PuzzleAlt, ThoughtBubble, TeamCheckAlt, UserGear, BowlChopsticks, CoffeeBean, GlassWhiskey,
        ArrowAltFromBottom, ChartWaterfall, ParkingCircleSlash, SkiBootSki, CameraRetro, Clone,
        Eraser, FileAudio, Outdent, Swatchbook, CircleH, CircleI, CircleT, CircleZ,
        SquarePollVertical, WaveSine, WaveSquare, SquareY, DiamondExclamation, FileZipper,
        FolderOpen, NotFoundAlt, ToggleOn, Alien, BookDead, ClawMarks, Galaxy, HoodCloak,
        PortalExit, Stocking, Transporter1, TransporterEmpty, UserRobot, DialMed, GripDots,
        LevelDownAlt, PenSwirl, TachometerAltSlow, ImageSlash, Guitars, RectanglesMixed, Mountain,
        Sailboat, TachometerAltAverage, Mercury, Neuter, Axe, ChatArrowGrow, Faucet, Flashlight,
        BrailleX, BrailleZ, FireExtinguisher, Plug, Screwdriver, TabletAndroid, HandHoldingSkull,
        Couch, DigitalTachograph, SoapAlt, TabletRugged, Shower, DumpsterFire, Moped, ShieldCross,
        VacuumRobot, ShieldMinus, ShowerDown, HorseSaddle, Monkey, DisplayMedical, DisplaySlash,
        CalendarArrowUp, TorchInspirationLeader, Dragon, Narwhal, Rabbit, Whale, BootHeeled, Tshirt,
        CakeSlice, CalculatorMathTax, Badminton, GoalNet, QuizAlt, ScrollOld, Citrus, KiwiFruit,
        LeafyGreen, ArrowSquareDown, AngleCircleDown, Butter, Flatbread, JugBottle, Pancakes,
        Popsicle, Answer, CatalogAlt, CatalogMagazine, InviteAlt, MeetingAlt, Rank, RankingPodium,
        WishlistHeart, WishlistStar, ArrowProgress, Mode, ExitAlt, Process, SwipeRight, BrowserUi,
        CloudCode, BrailleNAlt, TeamCheck, CustomerCare, MagnetUser, BicycleJourney, TourVirtual,
        TaxAlt, Friday, Sunday, PhotoCapture, Method, Percent90, Restock, Customize, HexagonDivide,
        ToriiGate, BarberPole, PlaceOfWorship, TruckBox, PasswordAlt, Dinner, Mix, Banner3,
        CurveAlt, Nose, Picking, QueueAlt, Multiple, OvalAlt, Oval, RotateSquare, DominoEffect,
        Insight, MapMarkerSlash, Age, Trust, PickingBox, BenefitDiamond, LightbulbCfl, BrakeWarning,
        TruckFire, ArrowFromRight, Mp3File, Mp4File, PptFile, LaptopArrowDown, Free,
        DiagramLeanCanvas, HouseFire, PreviousSquare, SurveyXmark, ThreeLeafClover,
        TentArrowTurnLeft, PigBankBulb, PersonCirclePlus, MapMarkerCheck, HouseChimneyUser,
        FaceGrinTongueWink, CircleWaveformLines, ArrowAltSquareLeft, Journal, Review, SignUp,
        Subscription, Category, SafeBox, ComplianceClipboard, CarsCrash, Track, Auction,
        LeadershipAlt, OrganizationChart, SalaryAlt, MoveToFolder, NetworkAnalytic, CheapDollar,
        Percent40, Sell, Supplier, Customization, Floor, OctagonMinus, OctagonXmark, PrayingHands,
        SquareDivide, ShieldDog, SpringCalendar, Seal, Svg, AdPaid, BonusStar, Channel,
        TransformationDesign, FaceSunglassesAlt, AgeAlt, Life, SkillAlt, MoneyBillTransfer,
        LimitHand, ArrowUpRightAndArrowDownLeftFromCenter, Dropdown, PointerText, PlugCircleMinus,
        PlantSeedInvest, MoneyWings, RectangleVerticalHistory, SignPosts, PlayMicrophone,
        CompassSouth, TrophyAchievementSkill, ToiletPaperBlank, TextBoxEdit, SunSalutationYoga,
        MoneyTransferSmartphone, HeadSideCoughSlash, CloudGearAutomation, Integral,
        OctagonExclamation, LionHead, Pollution, SoldHouse, Javascript, Otp, PasswordComputer, UiUx,
        GroceryBag, TransformationShapes, Pending, InfoGuide, ArrowUpRightFromSquare,
        ExpandArrowsAlt, PhotoFilmMusic, ClockTwoThirty, PlantCare, PlantGrowth, ScrewAlt, HatBeach,
        Joker, ArrowDownSmallBig, ArrowAltCircleDown, MusicNoteSlash, PersonDressSimple,
        UnderConstruction, CvvCard, SpaceStationMoonAlt, VideoArrowDownLeft, UpFromBracket,
        TruckArrowRight, TentArrowDownToLine, SquarePollHorizontal, PersonDollyEmpty,
        ClockElevenThirty, ChartPieSimpleCircleDollar, DiaryClasp, FeedbackAlt, LiveAlt,
        RankingStars, Videoconference, ClearAlt, SwipeDown, PigFace, SourceData, CalculatorMoney,
        Challenge, Compliance, GovernmentFlag, DriverWoman, TrainStation, EmployeeAlt, Rent, Fail,
        LeaderboardAlt, UserSalary, Percent10, Percent25, Drawer, Ankh, GreaterThan, PenClipSlash,
        CatHead, Analyse, BenefitPorcent, FeeReceipt, Module, HouseCrackAlt, Spy, GuideAlt,
        RulesAlt, Skill, Blood, HouseCircleXmark, GovernmentBudget, IotAlt, Screw, Referral,
        GreekHelmet, GolfHole, HorseshoeBroken, SystemCloud, RoadBarrier, HandshakeTrust,
        MoneySimpleFromBracket, SunPlantWilt, Treadmill, BasketShoppingSimple, EndlessLoop,
        HouseChimneyCrack, ForeignLanguageAudio, Replay10, SpainMap, WheatAwnCircleExclamation,
        TrashUndoAlt, TrashCanCheck, DocumentCircleWrong, BangladeshiTakaSign, ShishKebab, Waffle,
        TextBox, Leave, SwipeLeft, PriorityImportance, PuzzlePieces, CarJourney, AuditAlt, Audit,
        Blockchain3, CheapBill, Percent30, Percent60, SupplierAlt, LessThan, Omega, Damage,
        ExpenseBill, LawyerMan, Onboarding, SpeedometerKpi, Banner4, TransformationCircle,
        ArrowComparison, PersonCv, Snap, LessonClass, StudentAlt, ArrowTurnDownRight, CareerGrowth,
        LeadFunnel, Mortgage, RevenueEuro, PersonWalkingWithCane, Roulette, TruckUtensils,
        ArrowsSplitUpAndLeft, ArrowDownToDottedLine, Replay30, CompassEast, WineGlassCrack,
        TrianglePersonDigging, PrintMagnifyingGlass, SquareUpRight, SwipeUp, Condition, GalaxyStar,
        LightbulbSetting, RefundAlt, HrGroup, SeatbeltSafetyDriver, CustomerService, Brand,
        Saturday, CheapStack, ClipboardExclamation, Percent100, Selling, Warranty,
        CustomizeComputer, BookHeart, Lion, TruckCheck, DocumentPaid, QueueLine, TipCoin,
        PeopleRoof, MapMarkerPlus, Muscle, PaperPlaneTop, MemberSearch, ProgressUpload,
        ThunderstormRisk, AnatomicalHeart, DumbbellWeightlifting, InboxFull, MailboxEnvelope,
        HouseFlag, RectangleHistoryCirclePlus, RoadSignLeft, SendMoney, SofaSize, Workshop,
        BioLeaves, Waste, LawyerWoman, PaymentPos, ConvertDocument, MembershipVip, PlanStrategy,
        RecipeBook, MultipleAlt, Effect, HighFiveCelebrationYes, HeadSideMedical, HandPointRibbon,
        LeadManagement, Desk, TrashRestoreAlt, RunningTrack, HandHoldingMedical, FaceSmileHorns,
        ArrowsSplitRightAndLeft, TrashCanSlash, SummaryCheck, PostalAddress, HandFingersCrossed,
        ErrorCamera, CowbellCirclePlus, CompassWest, WorkInProgress, TrashCanList,
        ReflectHorizontalAlt, DistributeSpacingVertical, CodePullRequest, ClockThreeThirty,
        ClockTenThirty, CircleMicrophoneLines, ChartMixedUpCircleCurrency, BellSchoolSlash,
        BalanceScaleRight, ArrowFromBottom, BookCircleArrowRight, DirectionSignal, Chatbot,
        SpiderBlackWidow, Investment, StarCommentAlt, RegistrationPaper, DriverMan, RiskAlt,
        AssessmentAlt, Duration, SpeedometerArrow, AgeRestrictionZero, Debt, Percent75, Percent80,
        Intersection, Om, WomanScientist, DogLeashed, PawHeart, MarketplaceStore, Marketplace,
        Banner5, CurveArrow, SmartHome, UserCoach, UserTrust, ChoirSinging, DumbbellFitness,
        Excavator, TurnRight, CardinalCompass, CompassNorth, SleepingBag, UserInterfaceUi,
        SortShapesUp, SortAlphaUp, SendMoneySmartphone, RadarMonitoringTrack,
        OperatingSystemUpgrade, GroupCommunitySocialMedia, CategoryAlt, Constellation, LandLayers,
        React, FeaturesAlt, HrPerson, CallDuration, ArrowFromTop, NotFound, Payroll,
        WorkflowSettingAlt, StageTheatre, OctagonPlus, WastePollution, SoldSignal,
        ReservationSmartphone, ReservationTable, Bonus, Kpi, PersonSeatReclined, MilkAlt, Recipe,
        TransformationBlock, TogetherPeople, Introduction, SkillUser, StoryBook, MapMarkerMinus,
        Iot, Scooter, ImproveUser, TalentHand, DropdownSelect, BrokenChainLinkWrong, GlobePointer,
        MovFile, JumpingRope, Swap, ClipboardQuestion, FuelGauge, GpsNavigation, HeartHealthMuscle,
        Lighthouse, TrainTrack, StopSquare, SubtitlesSlash, GaugeCircleBolt, ChecklistTaskBudget,
        AssistiveListeningSystems, RankingStar, ReferArrow, InsertCreditCard, ChallengeAlt,
        DepositAlt, Tax, Monday, Thursday, MoneyCheckEdit, IssueLoupe, Percent50, BoothCurtain,
        DrawerAlt, StageConcert, Bible, Chalkboard, EmptySet, Lambda, BadgeLeaf, Bio, ShieldCat,
        HairClipper, PasswordEmail, Fee, KpiEvaluation, NoFee, Paid, Membership, Seller,
        GroceryBasket, InsertArrows, Insert, PersonShelter, SkinHair, StoreBuyer, MoneyBillSimple,
        Meditation, RegionPinAlt, PointerLoading, HockeyStickPuck, BalletDance, LoopSquare,
        PodiumVictoryLeader, HeadSideBrain, LastSquare, SpaghettiMonsterFlying,
        PlugCircleExclamation, HouseCircleExclamation, Violin, NotEqual, OctagonDivide,
        AirPollution, Pets, Token, RegionPin, ExternalHardDrive, UserKey, PlateUtensils,
        UtensilsSlash, Banner2, Curve, AgeRestrictionEighteen, BookPlus, FunctionSquare,
        StoryFantasy, SkinDrop, BracketCurlyRight, ConveyorBeltArm, LeaderSpeech,
        TirePressureWarning, WalletBuyer, EmployeeHandbook, KeySkeletonLeftRight, ArrowsAltV,
        BenefitHand, Benefit, BonusAlt, Webhook, MemberList, RadioButton, DashboardMonitor,
        AudienceMegaphone, CommentsQuestionCheck, TurnLeft, CloudBackUp, HouseLock, BlockMicrophone,
        Replay5, ClockSixThirty, TruckArrowLeft, TrafficLightSlow, TachometerAltFastest,
        StarSharpHalfStroke, ClockEightThirty, CalendarPaymentLoan, BuildingCircleArrowRight,
        BriefcaseArrowRight, ArrowUpToDottedLine, ArrowUpFromDottedLine, ArrowFromLeft,
        ArrowAltCircleLeft, FeedbackReview, JournalAlt, Preview, WorkflowAlt, GalaxyPlanet, PlugAlt,
        MatchFire, RevenueAlt, ToDo, StateCountry, Legal, Loan, Expense, LeaderboardTrophy,
        DailyCalendar, Wednesday, CrmAlt, PayrollCalendar, FloorLayer, Tie, CircleDivide, Hamsa,
        UsersClass, MosqueMoon, LockHashtag, Milk, InsertAlt, Queue, ModelCube, Rules,
        AgeRestrictionSixteen, BookOpenReader, MouseField, BackUp, RoboticArm, BenefitIncrease,
        TalentAlt, IndianRupeeSign, DumbbellRay, TruckLadder, IpAddress, PointOfSale, Burst,
        FolderFire, MapPoint, PersonLuggage, UniformMartialArts, TrainSubwayTunnel,
        HandBackPointRibbon, DistributeSpacingHorizontal, NewspaperOpen, Newspaper, Tap,
        ConditionAlt, WorkflowSetting, Workflow, Bucket, FlyInsect, LandLocation, IncenseSticksYoga,
        ArrowLeftFromArc, Overview, Choose, Features, Journey, TrainJourney, Branding, InsightHead,
        Leaderboard, CorporateAlt, Corporate, ProblemSolving, Shirt, Sofa, OctagonCheck,
        FlowerButterfly, MosqueAlt, MarketplaceAlt, PadlockCheck, SellerStore, GraphCurve,
        InsertSquare, QueueSignal, TargetAudience, InsightAlt, Lesson, CircleOverlap,
        ArrowDownFromDottedLine, SkeletonRibs, SpartanHelmet, Horseshoe, RecycleBin, ShieldTrust,
        CourtSport, EmailPending, ChartKanban, ClipoardWrong, PauseSquare, Tricycle, BloodDropper,
        FloppyDiskCircleXmark, FaceSmileUpsideDown, CommentArrowUpRight, FlatbreadStuffed, JarWheat,
        SushiRoll, Invite, PriorityArrows, ExternalWorld, Massage, ChooseAlt, Accident, Selection,
        RentSignal, WalletArrow, VideoDuration, Ux, Blueprint, CustomizeEdit, Handmade, Divide,
        Gopuram, Kaaba, ManScientist, Practice, Script, UserGraduate, RazorBarber, Booking,
        PlugCircleBolt, HashtagLock, PasswordSmartphone, Cryptocurrency, TrustAlt, Student, Lead,
        Raccoon, ReferralAlt, Chip, BellNotificationSocialMedia, LaptopBinary, ProgressComplete,
        WebDesign, DownLeftAndUpRightToCenter, StationaryBike, CalendarCall, GroupCall, PhoneGuide,
        Wave, CircleNodes, OrderHistory, Resume, CarTunnel, SurveillanceCamera,
        TrainStationBuilding, ToiletPaperUnderSlash, TentArrowLeftRight, SquareDashedCirclePlus,
        PersonCircleQuestion, MoneyTransferCoinArrow, ChartSimpleHorizontal, Percent20, Percent70,
        Stage, SunglassesAlt, Equals, FaceHeadBandage, Mosque, Synagogue, Vihara, AnalyseAlt,
        HouseChimneyWindow, ArrowProgressAlt, SortSizeDown, Visit, DotPending, LightbulbHead,
        HandHoldingHeart, IntroductionHandshake, Function, GrinTongueWink, Skin,
        CalendarBirhtdayCake, KeyboardBrightnessLow, CareerPath, ReferralUser, AngleSquareRight,
        ShoppingCartBuyer, DollyFlatbedEmpty, FlaskGear, SlotMachine, ProgressDownload, Branching,
        CreditCardBuyer, ResistanceBand, RotateReverse, CryptoCalendar, FreeDelivery, PayrollCheck,
        FloppyDiskCircleArrowRight, WhiteSpace, CompassAlt, WheatAwnSlash, UserSkillGear,
        UserHelmetSafety, SortAmountUpAlt, ShirtTankTop, ShareAltSquare, HouseChimneyMedical,
        HeartPartnerHandshake, FaceBeamHandOverMouth, ClosedCaptioningSlash,
        ChartPieSimpleCircleCurrency, Refund, BuildingNgo, GovernmentUser, AirplaneJourney, Leader,
        Assessment, BillArrow, CalendarSalary, DepartmentStructure, LimitSpeedometer, Plan, Cheap,
        Knitting, Church, ScaleComparison, Banner, Cv, ExchangeCryptocurrency, ConvertShapes,
        SourceDocument, SkinArrow, BinBottles, MeasuringTape, General, Talent, DashboardPanel,
        ToiletsPortable, FileCloud, WindowFrameOpen, SquarePhoneHangup, SourceDocumentAlt,
        SignalBarsWeak).sortedBy { it.name }
    return __Bold!!
  }
