package me.localx.icons.straight

import androidx.compose.ui.graphics.vector.ImageVector
import me.localx.icons.straight.filled.*
import kotlin.collections.List as ____KtList

private var __Filled: ____KtList<ImageVector>? = null

public val Icons.Filled.allIconsList: ____KtList<ImageVector>
  get() {
    if (__Filled != null) {
      return __Filled!!
    }
    __Filled = listOf(User, Marker, Heart, Home, Bell, Star, Settings, UsersAlt, Users, Globe,
        PhoneCall, Envelope, PaperPlane, ShoppingCart, Eye, Play, Calendar, MapMarker, UserAdd,
        Building, MenuBurger, Flame, GraduationCap, ShieldCheck, CircleSmall, Share, BadgeCheck,
        Trash, RocketLunch, Pencil, Add, Comment, Apps, AngleRight, Comments, AngleLeft, Coins,
        BookOpenCover, Lock, Bookmark, Document, Disk, SocialNetwork, Info, Briefcase, BookAlt,
        Next, MusicAlt, Circle, Shop, AngleSmallDown, Key, CrossCircle, Bank, Following,
        ArrowCircleRight, UsdCircle, Thumbtack, Check, TruckSide, ChartHistogram, PlaneAlt, Cross,
        Volume, Edit, Interrogation, EyeCrossed, Trophy, SackDollar, Camera, Bulb, Exclamation,
        SignOutAlt, AngleDown, CirclePhone, Clock, Sparkles, Moon, Paint, Megaphone,
        AngleSmallRight, Exit, Print, ShoppingCartAdd, Laptop, Gift, Raindrops, ArrowSmallLeft,
        SettingsSliders, ChartLineUp, Microphone, MapMarkerHome, Receipt, Search, Shield, Gym,
        ChartPieAlt, AngleCircleRight, CirclePhoneFlip, Refresh, Ticket, Download, CommentAlt,
        Headset, Computer, Bolt, BookBookmark, ShoppingBag, ListCheck, Direction, CalendarClock,
        Cursor, Database, Pharmacy, List, AngleSmallLeft, Folder, Crown, AppsAdd, WomanHead, Undo,
        Filter, BookOpenReader, Notebook, Pause, CakeBirthday, Broom, AlarmClock, SearchAlt, Stats,
        BellRing, School, Plane, Stars, Books, ArrowSmallRight, CommentInfo, Dollar, Forward,
        HomeLocationAlt, DocumentSigned, Flag, PuzzlePiece, Diploma, TimePast, Bed, MoonStars,
        ClipboardList, MenuDots, Resources, At, Diamond, CreditCard, StoreAlt, Boxes, AddDocument,
        HeadSideThinking, ELearning, Plus, Map, DeleteUser, Hamburger, Paw, ShieldExclamation,
        Badge, MenuDotsVertical, HandHoldingHeart, CloudDownloadAlt, PeoplePoll, SignalAlt2,
        Picture, Navigation, CrossSmall, Restaurant, CommentsQuestion, ClipboardListCheck, WifiAlt,
        ModePortrait, CommentCheck, Film, ChartTree, ChartPie, Wallet, CircleEnvelope, Ship, Rewind,
        AddressBook, WrenchSimple, Stethoscope, Tags, FileInvoiceDollar, Select, LifeRing, Layers,
        SignalAlt1, ShoppingBasket, VideoCameraAlt, Handshake, HatChef, PiggyBank, LayoutFluid,
        RoomService, Leaf, ChatArrowGrow, FolderDownload, Form, Headphones, Browser, UserTime, Grid,
        Palette, Expand, EnvelopeOpen, PlayPause, PlusSmall, HouseFlood, ArrowAltCircleRight,
        Donate, Dashboard, IdBadge, Sun, CommentQuote, Interactive, Mouse, MicrophoneAlt,
        Basketball, Checkbox, FlagAlt, File, MoneyBillWave, BoxAlt, Mountains, TimeForward,
        AngleDoubleSmallRight, Duplicate, Confetti, Garage, CalendarLinesPen, CommentCode,
        CursorFinger, InboxIn, Fingerprint, Doctor, PlayAlt, Ballot, AsseptDocument, Pulse,
        FlowerTulip, RectangleXmark, ChartNetwork, ChessQueen, SteeringWheel, ClockFive,
        BrainCircuit, VideoCamera, RemoveUser, Ban, Running, Cars, CommentDollar, LayerPlus,
        LinkAlt, TimeFast, AngleDoubleSmallLeft, Upload, CalendarCheck, CalendarLines, Copy, Sword,
        Calculator, MapMarkerMinus, CommentHeart, Treatment, Fill, RotateRight, ArrowCircleLeft,
        Filters, CopyAlt, Asterik, EditAlt, EnvelopePlus, DiceD6, Humidity, Shuffle, SignInAlt,
        ArrowsRepeat, Delete, Gifts, ChartConnected, AngleCircleUp, ToolBox, Umbrella, Soup,
        FileSpreadsheet, DisplayCode, Stopwatch, Physics, Archive, Sort, FolderTree, StarOctogram,
        GrinHearts, Sushi, Pennant, FolderUpload, Coin, Sack, DeleteDocument, SuitcaseAlt,
        TimeDelete, TestTube, ChessKnightAlt, FilterSlash, Football, SmileBeam, Folders,
        PaintRoller, Inbox, CompressAlt, Camping, Grill, MugHot, Wheat, BikingMountain, Smoke, Bus,
        ChargingStation, Subway, TruckCouch, BoxCheck, Qrcode, TimeQuarterTo, Scissors, Rocket,
        ArrowSmallUp, Keyboard, Bug, AppsDelete, PhonePause, LuggageRolling, RingsWedding,
        ChildHead, Water, CarBuilding, Tire, ArrowAltCircleLeft, Mailbox, ChairOffice, CashRegister,
        CommentsQuestionCheck, Medicine, Spinner, DiceAlt, Shuttlecock, HandHoldingBox, Circle1,
        Guitar, ArrowSquareRight, CloudSun, AngleDoubleSmallDown, Euro, Wind, Noodles, Strawberry,
        ChevronDoubleDown, Biking, BalanceScaleRight, DraftingCompass, PencilRuler, CodeCompare,
        DiagramProject, TimeAdd, CursorPlus, Entertainment, Compress, CallMissed, Car, Train,
        ChartPyramid, SearchHeart, ArrowAltSquareRight, FlagUsa, UsdSquare, SensorFire,
        CommentsDollar, MindShare, MoneyCheck, TreasureChest, QuestionSquare, ArrowsToLine,
        NetworkCloud, Mobile, Cookie, Cupcake, Fox, GlassCheers, CakeWedding, Wheelchair, ChessKing,
        X, AirConditioner, FileVideo, Spa, World, PhoneOffice, CommentQuestion, AngleDoubleRight,
        MapMarkerPlus, ManHead, TruckMoving, ShieldPlus, Book, Unlock, ModeLandscape, HamburgerSoda,
        BadgePercent, Clip, HomeLocation, Power, RecordVinyl, TimeTwentyFour, AngleSmallUp,
        Utensils, Gamepad, AngleCircleLeft, ClockThree, Hand, Screen, ShoppingCartCheck, AngleUp,
        Redo, AppleWhole, Tree, LocationAlt, CarSide, BarsProgress, MoneyCheckEdit, Minus, Cube,
        CaretDown, ArrowCircleUp, ArrowUpRight, CloudUploadAlt, Volleyball, Triangle, CommentUser,
        FileInvoice, Enter, BagsShopping, CirclePhoneHangup, AngleDoubleLeft, BadgeDollar, Bullseye,
        Earnings, CallIncoming, Gem, Comet, DataTransfer, GasPumpAlt, CloudShare, TimeCheck,
        Loading, Presentation, Road, CommentPen, ArrowUpRightAndArrowDownLeftFromCenter, MugHotAlt,
        SearchLocation, TruckLoading, Box, AddFolder, Game, Music, Flower, Equality, Bahai,
        AlignJustify, Label, PizzaSlice, BullseyePointer, Percentage, CommentAltMiddle,
        CloudDownload, CloudCheck, CaretRight, EngineWarning, SortDown, HourglassEnd, Gallery,
        ShoppingBagAdd, CloudUpload, AppsSort, Fish, ChartArea, BarcodeRead, Recycle, MinusSmall,
        Link, Text, CallOutgoing, MapMarkerCross, GrinAlt, FileChartLine, TimeOclock, Portrait,
        Balloons, ArrowCircleDown, InboxOut, BusinessTime, Syringe, Ambulance, GridAlt, Cloud,
        UsbPendrive, TreeChristmas, AngleCircleDown, Thunderstorm, BedAlt, CommentSms, ArrowUpLeft,
        Password, LockAlt, Backpack, Feather, Test, Arrows, DiceD10, HandHoldingSeeding, GiftCard,
        SearchDollar, Highlighter, Snowflakes, GarageOpen, BookArrowRight, Question, ArrowTrendUp,
        Rugby, QuoteRight, Bike, Smile, DiceD20, Hiking, BusAlt, Tractor, FolderMinus,
        AlarmExclamation, MarkerTime, GlobeAlt, ArrowSmallDown, Rec, Coffee, Pipette,
        RectanglePanoramic, CallHistory, EnvelopeDownload, GrinStars, CaretCircleRight, Club,
        TimeQuarterPast, Brush, Tennis, Package, Smartphone, UndoAlt, Rhombus, Swimmer, CarBattery,
        ArrowAltRight, CommentExclamation, VideoPlus, TimeForwardTen, MusicFile, CaretLeft,
        MagnifyingGlass, Whistle, EclipseAlt, EnvelopeOpenText, ShieldInterrogation, ToolCrop, Grin,
        GingerbreadMan, RugbyHelmet, CarMechanic, Motorcycle, AlarmSnooze, LightbulbDollar,
        FileCode, SquareCode, Network, TimeForwardSixty, Target, TextCheck, PhoneSlash, Popcorn,
        OilCan, MobileNotch, CodeSimple, ChatArrowDown, KissWinkHeart, TemperatureFrigid, ClockTwo,
        BarberShop, SignalAlt, DrinkAlt, Butterfly, CloudShowersHeavy, Volcano, BalanceScaleLeft, P,
        Subtitles, CaretUp, Drumstick, MugAlt, GasPump, GrinBeam, MessageCode, Resize, Golf, Italic,
        Tablet, Dizzy, SadTear, CannedFood, Pot, CarCrash, CaravanAlt, FileChartPie, F,
        BadgeSheriff, CommentXmark, SquareTerminal, GrinTongueSquint, Mushroom, Turkey,
        AssistiveListeningSystems, CalendarMinus, B, Registered, CommentArrowUpRight, ArrowsCross,
        LaughSquint, MehRollingEyes, CandyAlt, Lettuce, ArrowToRight, ChessRookAlt, CloudsSun,
        SunriseAlt, FighterJet, TireRugged, Calendars, I, LinkSlashAlt, ArrowTrendDown, Bells, Gif,
        Reflect, Dart, Interlining, BreadSlice, Taxi, SaltPepper, Tomato, AngleSquareUp,
        ChessClockAlt, Skating, Sledding, ArrowAltFromLeft, Keynote, CodeCommit, _3, Circle4,
        Square1, SchoolBus, Yen, EnvelopeMarker, SmileWink, Candy, Fork, Mug, Plate, ArrowFromRight,
        ArrowToLeft, BaseballAlt, BowArrow, HockeyPuck, CloudSleet, GasPumpSlash, Tram,
        TruckMonster, WagonCovered, ClockFourThirty, D, N, BlindsOpen, BlindsRaised, Circle6,
        Circle7, Square2, Square4, ObjectSubtract, Dice, HatBirthday, Grimace, Onion, Pepper,
        Skewer, ArrowToBottom, ArrowFromTop, CaretSquareLeft1, BowlingBall, Curling, DiceOne,
        Luchador, Sleigh, ArrowAltSquareLeft, ArrowAltToLeft, SortAlphaUpAlt, ClockSevenThirty,
        Democrat, ShekelSign, G, R, U, Blinds, BoxTissue, RectangleBarcode, _7, Circle0, Square6,
        Square7, BorderBottom, BorderCenterV, BorderNone, BorderOuter, CassetteVhs, CircleDashed,
        CircleHalfStroke, ObjectIntersect, TextWidth, BatteryFull, BatteryQuarter,
        BatteryThreeQuarters, DoorClosed, Hammer, HeadVr, LightSwitchOn, LightSwitch, BenchTree,
        BoxFragile, BoxOpenFull, BoxOpen, Fence, FireFlameCurved, HouseTree, IndustryWindows,
        IslandTropical, LuggageCart, MapMarkerCheck, MapMarkerSlash, Monument, Parking, Passport,
        PlaneProp, RampLoading, RouteInterstate, SeatAirline, SignHanging, SquarePlus,
        TrafficLightGo, WineGlassCrack, HeadSideCough, HeadSideMask, HandHorns, HeartCrack, Bone,
        BurgerGlass, FileExcel, FilePowerpoint, SignalStream, WifiExclamation, Background, BlogText,
        Devices, Mockup, ReflectHorizontal, BookCircleArrowUp, AngleSquareDown, CalendarPen,
        RubleSign, RulerTriangle, MobileButton, MakeupBrush, Bowling, Games, Hastag, Salad,
        Sandwich, AngleDoubleSmallUp, RotateLeft, S, Lipstick, Snowflake, ChartSetTheory, MugTea,
        HockeyMask, GarageCar, TruckContainer, PhotoVideo, SadCry, Picnic, Spoon, Dewpoint,
        BabyCarriage, ClockSeven, MoneyCheckEditAlt, Stamp, BarcodeScan, Barcode, BellSchool, Sad,
        Pyramid, GrinWink, ArrowsH, CaretCircleUp, CarAlt, CarGarage, Ad, ArrowsFromDottedLine,
        BandAid, Scale, Bold, FilePsd, Pineapple, Meteor, ArrowAltCircleUp,
        DownLeftAndUpRightToCenter, A, Skateboard, Alignment, Speaker, Vector, Carrot, Cheese,
        Broccoli, ChessPawn, Starfighter, LayerMinus, CommentArrowUp, Infinity, Glasses, Cocktail,
        AmusementPark, GrinSquintTears, CaretCircleDown, ChessKingAlt, DiceD4, Snowboarding,
        CloudRain, ArrowAltUp, CalendarExclamation, BoxBallot, E, ArrowUpFromSquare, CodeBranch,
        Protractor, FileEps, FlipHorizontal, TrainSide, RedoAlt, Cherry, Egg, Lemon, Watermelon,
        ChessBoard, DiceD12, HockeySticks, Skiing, ThunderstormSun, SkiLift, TachometerSlowest,
        TruckPlow, ClockEleven, ClockTen, EnvelopeBulk, FolderTimes, C, H, CarCircleBolt, _2, _4,
        Rainbow, ThermometerHalf, Kiss, Radish, Sauce, ChessKnight, Dreidel, SkiingNordic,
        ThunderstormMoon, WaterRise, TachometerAverage, ArrowAltToBottom, SortNumericDown, Hryvnia,
        Q, CarBolt, ArrowUpSquareTriangle, CodePullRequestClosed, LinkHorizontalSlash, TablePivot,
        _0, Circle5, Square5, KissBeam, Poo, Chocolate, BowlingPins, DiceFour, CloudHail, Smog,
        TemperatureDown, CarBump, Snowmobile, TachometerSlow, Trailer, ClockFiveThirty,
        ClockOneThirty, O, Y, SensorSmoke, Tally, VideoArrowUpRight, _9, Square0, Square8, BookFont,
        BorderInner, BorderLeft, BorderRight, BorderStyle, BringForward, BringFront, CassetteTape,
        ObjectExclude, ObjectUnion, BatterySlash, HammerWar, BookAtlas, BoxUp, Cabin, ConciergeBell,
        FishingRod, FlagCheckered, Fort, HotTub, HouseBlank, HouseChimneyBlank, HouseTurret,
        LandmarkAlt, MapMarkerQuestion, MapMarkerSmile, PeopleCarryBox, PlaneDeparture, PlaneTail,
        RollerCoaster, ShopLock, StoreLock, TablePicnic, TaxiBus, ToiletPaperBlank,
        TrafficLightStop, TrainTram, TreeDeciduous, UmbrellaBeach, HeadSide, HeadSideBrain,
        HeadSideCoughSlash, Api, PhotoFilmMusic, Sticker, FrenchFries, Hotdog, SnowBlowing,
        Snowplow, TachometerAltFastest, ArrowAltCircleDown, EnvelopeOpenDollar, RulerVertical,
        CrystalBall, LaptopCode, Circle2, Croissant, ArrowFromBottom, ChevronDoubleUp, Eclipse,
        SortAlt, LineWidth, RectangleHorizontal, Symbol, MaskCarnival, Kite, CocktailAlt, CoffeePot,
        WaterBottle, AngleSquareRight, ExpandArrows, RulerCombined, Tooth, Center, Clouds,
        GrinBeamSweat, Grape, ExpandArrowsAlt, GameBoardAlt, SortAmountDownAlt, PodiumStar,
        ArrowUpToDottedLine, TableColumns, GraphicTablet, Laugh, Corn, Steak, Cricket, Rv,
        TachometerFast, ArrowAltSquareUp, SensorOn, Sensor, ArrowUpRightFromSquare, CodePullRequest,
        Cream, Lasso, Cow, Frown, Tired, CaretQuareUp, LevelUp, ChessBishop, ChessRook, DiceD8,
        SortAmountUp, AlarmPlus, ChartScatter, _1, Cowbell, CloudDisabled, Underline, Venus,
        Flushed, LaughWink, Bacon, Burrito, Peach, Pumpkin, DiceSix, DiceThree, GolfClub, Sunset,
        TemperatureUp, WaterLower, WindWarning, Windsock, CarWash, HelicopterSide,
        TachometerFastest, SortAmountUpAlt, CalendarPlus, T, Republican, Typewriter, CommentImage,
        CursorText, Blossom, GrinTongueWink, CaretSquareLeft, SkiJump, CloudShowers, Fog,
        TachometerAltSlowest, TruckRamp, ArrowsAltV, ClockTenThirty, ClockThreeThirty,
        ClockTwelveThirty, ClockTwelve, L, CarSideBolt, Chair, MoneyBillWaveAlt, FilmSlash, Kerning,
        VideoArrowDownLeft, ArrowsFromLine, Circle8, Aubergine, EggFried, Garlic, Olives, Sausage,
        Taco, ArrowsAlt, ArrowFromLeft, ArrowSquareLeft, BasketballHoop, GolfBall, CloudHailMixed,
        Hurricane, TirePressureWarning, ArrowAltFromRight, ArrowAltFromTop, ClockEightThirty,
        ClockElevenThirty, ClockSixThirty, ClockTwoThirty, J, M, W, Z, TextSlash, SidebarFlip, _8,
        Square9, AlbumCircleUser, Betamax, BorderAll, BorderStyleAlt, DistributeSpacingVertical,
        GalleryThumbnails, HighlighterLine, TextSize, BatteryBolt, BatteryEmpty, BatteryHalf,
        DoorOpen, HammerCrash, LightSwitchOff, Projector, Archway, Binoculars, Castle,
        HouseChimneyMedical, HouseChimneyWindow, HouseMedical, HouseWindow, Igloo,
        LocationCrosshairsSlash, LocationCrosshairs, MapMarkerEdit, ParkingCircle, ParkingSlash,
        RouteHighway, ShoePrints, StreetView, TicketAlt, TrafficLightSlow, TrophyStar, VestPatches,
        People, SpaceShuttle, ClockNine, LinkHorizontal, VectorAlt, PhoneCross, Glass,
        TemperatureHigh, TvMusic, CommentText, ArrowUpLeftFromCircle, TimeHalfPast, Incognito,
        SquareRoot, Sunrise, Angry, CloudsMoon, TachometerAltSlow, CommentArrowDown, Surfing,
        Shrimp, CloudRainbow, Summer, TableLayout, Jpg, ChessPiece, Baseball, Equipment, Copyright,
        ShipSide, Beer, VenusMars, Pie, LevelDown, ArrowSquareUp, BoxingGlove, ChessQueenAlt,
        Racquet, Heat, ArrowAltDown, BookArrowUp, TableTree, Ftp, LetterCase, FileAi, IceCream, Meh,
        Bottle, ExchangeAlt, AngleSquareLeft, CloudDrizzle, CloudSunRain, ShuttleVan, _5, Hourglass,
        Soap, Transform, Money, EnvelopeBan, HeartArrow, MehBlank, Bread, Exchange, ChessPawnAlt,
        Chess, Spade, ArrowAltLeft, CodeFork, ToolMarquee, Sphere, GrinTears, GrinTongue, LaughBeam,
        Surprise, Knife, CloudMoon, CloudSnow, CarBus, TireFlat, Tty, ClockOne, FunnelDollar,
        Podium, AirFreshener, SensorAlert, Overline, CommentAltMiddleTop, ArrowsToDottedLine,
        CodePullRequestDraft, Billiard, RectabgleVertical, Indent, OliveOil, ArrowSquareDown,
        TemperatureLow, CarTilt, ArrowAltSquareDown, ArrowsAltH, Braille, ReplyAll, SortAlphaDown,
        RupeeSign, Camcorder, PageBreak, RulerHorizontal, VideoSlash, CodeMerge, TableRows, Circle3,
        CursorTextAlt, Pound, Opacity, VenusDouble, Mars, Party, Terrace, GrinSquint, Avocado, Jam,
        PepperHot, CaretSquareDown, ArrowToTop, ArrowsHCopy, CaretSquareRight, LevelUpAlt,
        ChessClock, CloudMoonRain, Caravan, OilTemp, TachometerAltAverage, Tachometer, TruckPickup,
        ArrowAltToTop, SortAmountDown, ClockNineThirty, V, CommentSlash, ArrowsRepeat1,
        RectangleCode, Sidebar, CrossReligion, Square3, Album, GridDividers, MarsDouble, Tornado,
        Melon, Pan, LevelDownAlt, DiceTwo, FieldHockey, ArrowAltFromBottom, ArrowAltToRight,
        SortAlphaDownAlt, SortAlphaUp, SortNumericDownAlt, ClockSix, LiraSign, K, Tenge, LinkSlash,
        _6, Circle9, AlbumCirclePlus, AlbumCollection, BorderCenterH, BorderTop, CowbellMore,
        DistributeSpacingHorizontal, LassoSparkles, TextHeight, BlockBrick, Block, Apartment, Bomb,
        City, DiamondTurnRight, Dungeon, Farm, FireSmoke, Gavel, Hotel, HouseBuilding,
        HouseChimneyCrack, HouseChimney, HouseCrack, LocationDotSlash, MapPin, ParkingCircleSlash,
        Vest, BookmarkSlash, InputNumeric, ScrollTorah, BellConcierge, EarthAfrica, EarthAsia,
        PersonSeatReclined, TruckTow, WaterLadder, CircleCalendar, ChartUser, DongSign, Envelopes,
        Fax, FlorinSign, LariSign, MillSign, PaperclipVertical, PenNibSlash, WonSign, BracketsRound,
        BracketsSquare, Microchip, Terminal, BlenderPhone, Bullhorn, MessageImage, MessageQuote,
        SmilePlus, Symbols, FaceConfused, FaceDisguise, FaceExpressionless, FaceGrinTongueWink,
        FaceRelieved, FaceShush, FaceSwear, FaceTissue, PersonSimple, FilesMedical, HospitalUser,
        Inhaler, Joint, LaptopMedical, Microscope, PrescriptionBottleAlt, ScalpelPath, SmokingBan,
        Walker, ArrowDownLeft, CircleQuarter, CommentAltMusic, PenFancy, RssAlt, SendBackward,
        SlidersHSquare, Speakers, Subscript, Superscript, Table, VolumeDown, SquareM, SquareS,
        BookSpells, FlaskPotion, HatWizard, HollyBerry, Joystick, PortalEnter, Radar, Transporter4,
        Transporter7, CloudQuestion, FileEdit, SealQuestion, TrashRestore, CoffeeBeans, Meat,
        ChartGantt, DiagramLeanCanvas, DiagramNested, DiagramSuccessor, SquareInfo, CircleO,
        CircleW, CircleEllipsis, DialMax, DialOff, PenField, BlockQuote, CircleWaveformLines,
        FaceViewfinder, ForwardFast, StarSharpHalf, EyeDropperHalf, ListMusic, PenCircle, SaxHot,
        LeafMaple, TeddyBear, Wreath, HandScissors, ParachuteBox, Chimney, ScannerImage, BrailleC,
        BrailleG, BrailleNAlt, DiscDrive, HouseSignal, Satellite, SimCard, Tools, PersonCirclePlus,
        UserLock, HouseLeave, ShippingTimed, SolarPanel, Sprinkler, DryerAlt, Dryer,
        GaugeCircleBolt, GaugeCirclePlus, ConveyorBeltEmpty, HouseChimneyUser, ScannerGun, Shelves,
        Stairs, ToiletPaperBlankUnder, TruckContainerEmpty, TruckFlatbed, Dolphin, Trillium,
        KeyboardDown, LampStreet, LaptopArrowDown, LaptopSlash, MicrochipAi, TentArrowTurnLeft,
        BadgerHoney, Dog, Duck, Frog, Site, FamilyDress, FamilyPants, HatCowboySide, Ring, Socks,
        UserCowboy, CupStraw, MartiniGlassEmpty, HandHoldingMagic, Mace, Quiz, Second, Blueberries,
        Coconut, CrateEmpty, Potato, BowlScoop, FonduePot, TtyAnswer, Admin, CategoryAlt, ExitAlt,
        Process, SwipeRight, WorkflowSettingAlt, Constellation, BrowserUi, CloudCode, LandLayers,
        React, TeamCheck, CustomerCare, FeaturesAlt, HrPerson, MagnetUser, BicycleJourney,
        TourVirtual, TaxAlt, CallDuration, Friday, FaceAwesome, HandPeace, FileWord, CopyImage,
        MoveToFolder, MemoPad, Notes, SpaghettiMonsterFlying, Tally2, Tally3, EarthAmericas,
        TicketsAirline, AustralSign, BookSection, BriefcaseBlank, BullseyeArrow, CentSign,
        ChartTreeMap, EnvelopeDot, HandsUsd, LightbulbSlash, ManatSign, MessageDollar,
        MessagesDollar, MoneyBillSimple, SignatureLock, SquareKanban, TugrikSign, Vault,
        BracketCurly, BracketRoundRight, BracketsCurly, BugSlash, LaptopMobile, WindowAlt,
        WindowMaximize, WindowMinimize, MessageQuestion, FaceGlasses, FaceParty, FaceUnamused,
        FaceWeary, HandBackPointLeft, PersonDress, SnowmanHead, BookMedical, BookUser, BooksMedical,
        ClipboardUser, Crutches, FileMedicalAlt, FileMedical, Lungs, Skeleton, Virus,
        RectangleVertical, Columns3, DrawSquare, H4, HeadSideHeadphones, Scrubber, StepBackward,
        VolumeOff, SquareC, SquareH, SquareL, SquareP, SquareR, Coffin, LightsHoliday, PoliceBox,
        Skull, StarShooting, Telescope, TombstoneAlt, UfoBeam, BellSlash, CircleQuartersAlt,
        CloudExclamation, FileCsv, PartyHorn, ToggleOff, BowlRice, Brightness, DiagramNext,
        DownRight, Up, BookCopy, CalculatorSimple, CircleD, Sink, CircleM, CircleU, Dharmachakra,
        WatchCalculator, WaveTriangle, PenSlash, PencilSlash, TrashCanClock, TrashSlash,
        VectorCircle, Aperture, CameraCctv, ClapperboardPlay, Panorama, StandardDefinition,
        RectangleVerticalHistory, TintSlash, Turntable, Webcam, ConveyorBelt, Dumpster, LampDesk,
        ShieldAlt, BrailleB, BrailleJ, BrailleK, BrailleO, HardHat, UserUnlock, Magnet,
        ScannerKeyboard, ToiletPaperSlash, BedEmpty, Drone, FanTable, Fan, Fireplace, Refrigerator,
        Angle90, Engine, Sickle, TruckBolt, PersonCarryBox, Unicorn, KeyboardLeft, MeterBolt, Mound,
        Pompebled, SnowflakeDroplets, Crow, Dove, RabbitFast, Spider, BuildAlt, ItAlt, Balloon,
        Child, ClothesHanger, HatWinter, Pool8Ball, ShirtLongSleeve, ShirtRunning, Transgender,
        UserTag, BowlSoftServe, CupcakeAlt, MugTeaSaucer, Award, AxeBattle, First, HockeyStickPuck,
        LacrosseStickBall, Cucumber, PanFood, Peapod, PepperAlt, Baguette, BreadSliceButter,
        CubesStacked, SaltShaker, Feedback, Journal, RankingStar, Review, SignUp, Subscription,
        TextBoxEdit, Category, ReferArrow, ChallengeAlt, DepositAlt, SafeBox, ComplianceClipboard,
        CarsCrash, Track, Tax, PeopleDress, CandyCorn, CheeseAlt, SignalStreamSlash, Wifi2, Pattern,
        Replace, SmileyCommentAlt, BookQuran, EarthEuropa, Elevator, TicketAirline, BitcoinSign,
        BriefcaseArrowRight, FileSignature, HandHoldingUsd, MoneyBills, NfcMagnifyingGlass,
        RectanglePro, Shredder, SquarePollHorizontal, BanBug, BarsSort, Binary, BinarySlash,
        BracketCurlyRight, BracketSquareRight, Gears, KeySkeletonLeftRight, CircleUser,
        CommentAltMinus, CommentDots, Language, Messages, SquareQuote, FaceAngryHorns,
        FaceDowncastSweat, FaceFearful, FaceLying, FacePleading, FaceSmileHearts, FaceSmileTongue,
        FaceSmilingHands, FaceTongueSweat, FaceWoozy, HandDots, HandHeart, HandsBubbles,
        MarsStrokeUp, PersonDressSimple, PipeSmoking, UsersGear, BoneBreak, Bong, Hospital,
        MortarPestle, Pager, PrescriptionBottle, RadiationAlt, Toothbrush, UserMd, UserNurse, XRay,
        CircleBolt, Split, ObjectGroup, Podcast, SquareQ, SquareT, CoffinCross, Ornament,
        SpaceStationMoonAlt, SpiderWeb, StarChristmas, FileDownload, FileImage, FileUpload,
        GripHorizontal, GripLinesVertical, GripLines, HexagonExclamation, LightbulbQuestion,
        LightbulbExclamation, LocationExclamation, TimesHexagon, ArrowDownSmallBig, Bath,
        ArrowUpFromDottedLine, ChartMixed, ChartScatter3d, DiagramPrevious, DiagramSankey,
        SortShapesDown, CircleC, CircleK, CircleR, Peace, PencilPaintbrush, Tilde, CircleTrash,
        DialMin, HexagonCheck, SquareEllipsisVertical, SquareEllipsis, CameraSlash,
        CameraViewfinder, Films, MusicNoteSlash, Screencast, StarSharpHalfStroke, TableList,
        DrumSteelpan, ObjectsColumn, RadioAlt, SprayCan, BallPile, Seedling, CalendarHeart,
        HandMiddleFinger, PersonDollyEmpty, Blender, DollyFlatbedAlt, HouseDay, IndustryAlt, Router,
        BrailleE, BrailleV, HouseUser, SatelliteDish, UserMinus, UserRobotXmarks, Lamp, LockOpenAlt,
        SirenOn, BedBunk, DroneAlt, PalletAlt, Frame, HoseReel, PhoneRotary, SprayCanSparkles,
        UtilityPole, Bird, PawClaws, Ram, Squid, Bugs, TentArrowDownToLine, Alicorn, CatSpace,
        DeerRudolph, It, SiteAlt, SiteBrowser, Boot, Family, HouseChimneyHeart, Piñata, UserMusic,
        UserNinja, Banana, CandySweet, WheatSlash, FirstAward, FirstLaurel, LacrosseStick,
        SecondMedal, ThirdAward, CanFood, Pear, PumpkinAlt2, BowlSpoon, Falafel, JugAlt, SushiAlt,
        Tamale, Live, Meeting, SubscriptionAlt, DescriptionAlt, DropDown, ModeAlt, Route,
        TrafficLight, TrainSubwayTunnel, Brain, HeadSideVirus, CircleHeart, BreadLoaf, BurgerFries,
        FilePdf, Wifi, Bullet, GraphicStyle, Images, BookTanakh, MemoCircleCheck, Memo, Note,
        PersonPraying, Tally1, CalendarImage, CalendarWeek, BangladeshiTakaSign,
        BasketShoppingSimple, ChartSimple, DiagramVenn, IndianRupeeSign, MoneyBillsSimple,
        MoneySimpleFromBracket, NfcPen, NotebookAlt, PenClip, PollH, RupiahSign, SignatureSlash,
        SterlingSign, BinaryLock, BracketSquare, Memory, CommentMinus, MessageSlash, Rss,
        FaceMonocle, FacePensive, FaceSleeping, FaceSmileHalo, FaceSmileTear, FaceWorried,
        HandBackPointRibbon, UniformMartialArts, UserSlash, Bacterium, ClipboardPrescription,
        CommentMedical, Ear, FilePrescription, Hospitals, LungsVirus, MaskFace, NotesMedical,
        PrescriptionBottlePill, Smoking, TeethOpen, UserMdChat, VirusSlash, Right, SealExclamation,
        CameraSecurity, Eject, H1, H2, H3, Paragraph, PauseCircle, SlidersV, StepForward,
        VolumeSlash, SquareF, SquareG, SquareJ, SquareU, SquareV, Cauldron, FlaskPoison, HatSanta,
        KnifeKitchen, Mistletoe, Scarecrow, Tombstone, FileExclamation, FileImport, FileMinus,
        PartyBell, LightEmergencyOn, SignalBarsGood, SquareExclamation, TrashUndoAlt, TrashUndo,
        BowlChopsticksNoodles, Cheeseburger, FishCooked, MugMarshmallows, Stroopwafel, WineBottle,
        ArrowsRetweet, AudioDescriptionSlash, ChartCandlestick, Cubes, DiagramCells, EarDeaf,
        HeadSideHeart, UniversalAccess, YinYang, CircleF, CircleJ, CircleL, Pi, PlusMinus, Sigma,
        Theta, ValueAbsolute, DialHigh, PenClipSlash, TrashCanCheck, TrashList, TrashPlus,
        Clapperboard, Gramophone, Kazoo, PaintbrushPencil, PianoKeyboard, Piano, SquareDashed,
        Trumpet, WebcamSlash, CompassSlash, Icicles, PooBolt, TemperatureList, HandSparkles,
        PersonDolly, ComputerClassic, PrintSlash, Shovel, BrailleP, BrailleS, Ethernet, TrafficCone,
        PersonCircleMinus, DoNotEnter, ThermometerAlt, LightCeiling, Microwave, Oven, Pallet, Angle,
        Grate, Hose, Pump, VrCardboard, BoxCircleCheck, FireHydrant, Sheep, TreeAlt, Worm,
        FloppyDiskPen, MeterFire, Meter, SimCards, HouseTsunami, MattressPillow, SunPlantWilt,
        Tents, PersonSign, Scarf, UserHeadset, UserInjured, AppleCore, WheatAwn, BroomBall,
        CardDiamond, FirstMedal, HelmetBattle, Scroll, Staff, ThirdLaurel, SquareMinus, CalendarDay,
        CalendarStar, CalendarXmark, HourglassStart, WatchSmart, Watch, BoxDollar, CalendarDays,
        CediSign, CruzeiroSign, FileCircleInfo, FloppyDiskCircleXmark, GuaraniSign, KipSign,
        ListDropdown, Nfc, PesoSign, PrintMagnifyingGlass, ShopSlash, Signature, BinaryCircleCheck,
        Browsers, FileBinary, Hdd, WindowRestore, CommentAltCheck, CommentAltDots, CommentAltEdit,
        CommentSmile, MessageArrowUp, MessagesQuestion, Voicemail, FaceCowboyHat, FaceDrooling,
        FaceIcicles, FaceMask, FaceNauseated, FacePersevering, FaceSleepy, FaceSmileUpsideDown,
        HandHoldingWater, Eyes, HeartRate, HospitalSymbol, Radiation, MedicalStar, Hexagon, Left,
        SquareSmall, SquareStar, SlidersVSquare, Waveform, SquareA, SquareB, SquareI, SquareO,
        SquareW, SquareX, Ghost, HandSpock, PlanetRinged, Scythe, Transporter3, Transporter6,
        UserAlien, UserVisor, DotCircle, GripVertical, LowVision, CookieAlt, GlassWhiskeyRocks,
        ArrowDownFromDottedLine, ArrowDownToDottedLine, ArrowTurnDownRight, ArrowUpSmallBig,
        ChartRadar, ChartScatterBubble, DownLeft, PersonWalkingWithCane, UpLeft, ChalkboardUser,
        CircleE, CircleN, CircleX, DialLow, Dial, Bee, TrashCheck, VectorPolygon, CameraRotate,
        GifSquare, ImagesUser, MusicNote, RectangleList, Cello, Splotch, TriangleMusic, Anchor,
        Campfire, FeatherPointed, LeafOak, SunDust, ThermometerQuarter, Angel, BoxHeart, LeafHeart,
        ContainerStorage, DollyFlatbed, Flask, HouseNight, BrailleH, BrailleL, BrailleN, BrailleQ,
        BrailleW, WrenchAlt, PersonCircleCheck, PersonCircleXmark, UserCheck, ClipboardCheck,
        HouseReturn, Toilet, LampFloor, Washer, GrateDroplet, WindTurbine, ClockDesk, ShieldSlash,
        ToiletPaperUnder, KiwiBird, DisplayArrowDown, FireFlameSimple, FloppyDisks, Manhole,
        SdCards, TrianglePersonDigging, BagSeedling, FireBurner, MountainCity, Deer, HorseHead,
        Build, InventoryAlt, QrScan, GunSquirt, HatCowboy, CupStrawSwoosh, CupTogo, GlassEmpty,
        UserChef, CardClub, Dagger, FlyingDisc, MaskSnorkel, SecondAward, SecondLaurel, CitrusSlice,
        GarlicAlt, MushroomAlt, Olive, Peanut, BowlScoops, Donut, JarAlt, PanFrying, PlateWheat,
        ShishKebab, Waffle, NewspaperOpen, Newspaper, TextBox, Leave, SwipeLeft, Tap, ConditionAlt,
        PriorityImportance, WorkflowSetting, Workflow, Bucket, FlyInsect, LandLocation, Overview,
        HandsClapping, PeoplePants, SquareHeart, BurgerAlt, FileExport, Wifi1, License,
        MoveToFolder2, Paste, ReflectVertical, RemoveFolder, TriangleWarning, CircleBookOpen,
        UserPilotTie, BarsStaggered, CartArrowDown, ChartSimpleHorizontal, ColonSign, FrancSign,
        ItalianLiraSign, NfcTrash, PhoneFlip, Trademark, HorizontalRule, BallotCheck, MessageBot,
        PaperPlaneTop, PhonePlus, FaceAnguished, FaceAnxiousSweat, FaceDisappointed, FaceHandYawn,
        FaceSadSweat, FaceSmirking, FaceTongueMoney, FaceVomit, FaceZany, FaceZipper, HandBackFist,
        HandsHolding, MarsStrokeRight, UserPen, Cannabis, Capsules, CommentAltMedical, Crutch, Dna,
        ShieldVirus, Stomach, CircleThreeQuarters, HeartHalfStroke, AlignSlash, Banjo, CameraMovie,
        Clipboard, DrawPolygon, Mp3Player, PenSquare, SendBack, Strikethrough, VolumeMute,
        WaveformPath, SquareD, SquareK, SquareZ, FluxCapacitor, PlanetMoon, Raygun, SolarSystem,
        SpaceStationMoon, Transporter2, Transporter, UserAstronaut, CheckCircle, LightEmergency,
        PlusHexagon, SignalBarsFair, StarExclamation, GlassChampagne, ArrowDownToSquare,
        ArrowRightToBracket, ChartBullet, DiagramPredecessor, DiagramSubtask, Down, UpRight, Cat,
        WheelchairMove, CircleB, CircleS, CircleV, CircleXmark, StarAndCrescent, TheaterMasks,
        Airplay, Command, GripDotsVertical, TrashCanPlus, TrashClock, BoltAuto, BoltSlash,
        DroneFront, HighDefinition, GuitarElectric, Mandolin, MusicSlash, Radio, Saxophone,
        Scribble, CloudMeatball, FlowerDaffodil, SnowmanAlt, ThermometerFull, GlobeSnow, HomeHeart,
        Ribbon, UserCrown, ConveyorBeltAlt, BrailleA, BrailleD, BrailleI, BrailleM, BrailleT,
        BrailleU, BrailleY, SdCard, PersonCircleQuestion, UserXmark, ScannerTouchscreen,
        SortCircleUp, SortCircle, Vacuum, CarRear, GaugeCircleMinus, Robot, PlaneSlash,
        ToiletPaperUnderSlash, TransformerBolt, TruckFront, UserPolice, CowAlt, Elephant, Hippo,
        Lobster, Otter, MeterDroplet, Locust, MosquitoNet, Mosquito, Pickaxe, PlantWilt,
        TentArrowLeftRight, TentArrowsDown, SkullCow, Squirrel, Discover, ShovelSnow, Sunglasses,
        HandFist, Medal, SwimmingPool, PineappleAlt, Custard, FlatbreadStuffed, GlassWaterDroplet,
        JarWheat, SushiRoll, Invite, SwipeUp, Condition, PriorityArrows, ExternalWorld, GalaxyStar,
        LightbulbSetting, Massage, RectangleHistoryCirclePlus, SquareUpRight, FaceHeadBandage,
        HeadSideMedical, PeopleArrowsLeftRight, AnimatedIcon, AttributionPen, BrokenImage,
        FollowFolder, NoPeople, Picpeople, PicpeopleFilled, Template, TemplateAlt, CircleBookmark,
        InputText, Tally4, RestroomSimple, UserPilot, CalendarArrowDown, CartShoppingFast,
        FloppyDiskCircleArrowRight, FolderXmark, HouseLaptop, LitecoinSign, MoneyFromBracket,
        NfcLock, NfcSlash, PesetaSign, VoteYea, BarsFilter, Notdef, MessageArrowUpRight,
        MessageText, MessageXmark, WalkieTalkie, Baby, FaceBeamHandOverMouth, FaceNoseSteam,
        FaceRaisedEyebrow, FaceScream, FaceSmileHorns, FaceSunglasses, FaceThermometer,
        HandFingersCrossed, HandLove, HandPointRibbon, HandshakeSimpleSlash, PersonPregnant, Reel,
        HSquare, HandHoldingMedical, IdCardClipAlt, Kidneys, NoteMedical, Poop, Scalpel,
        WatchFitness, HeartHalf, ListTimeline, SquareBolt, BroadcastTower, Clarinet,
        ComputerSpeaker, FilmCanister, Heading, MicrophoneSlash, ObjectUngroup, ParagraphLeft,
        PenNib, PlayCircle, StopCircle, SquareE, SquareN, CandleHolder, HatWitch, PumpkinAlt,
        SkullCrossbones, Transporter5, Ufo, BatteryExclamation, CheckDouble, CircleExclamationCheck,
        Information, MinusCircle, MinusHexagon, RotateExclamation, ShareAltSquare, SignalAltSlash,
        TrashRestoreAlt, DrumstickBite, GlassCitrus, BrightnessLow, ClosedCaptioningSlash,
        DownToLine, HandshakeAngle, KeyboardBrightnessLow, KeyboardBrightness, Octagon, Slash,
        SortSizeDown, SortSizeUp, Cactus, CircleA, CircleG, CircleP, CircleQ, CircleY, StarOfDavid,
        _360Degrees, DeleteRight, TrashCanList, TrashCanSlash, TrashXmark, CircleCamera,
        CircleMicrophoneLines, CircleMicrophone, CircleVideo, CowbellCirclePlus, Drum, Flute,
        EarMuffs, ThermometerEmpty, ThermometerThreeQuarters, Trees, FileUser, HandPaper,
        DollyFlatbedEmpty, FaucetDrip, BrailleR, Digging, Forklift, TabletAndroidAlt, TvRetro,
        ArtificialIntelligence, LocationArrow, UserShield, UsersSlash, Loveseat, ShippingFast,
        Siren, SortCircleDown, Blanket, LightbulbOn, TankWater, TruckMedical, WindowFrame,
        ShieldKeyhole, ShieldXmark, Tape, UtilityPoleDouble, Crab, FishBones, Horse, Snake,
        TreesAlt, ComputerMouse, DesktopArrowDown, Pedestal, UserHelmetSafety, CloverAlt, Bat,
        Turtle, ItComputer, Qr, BlockQuestion, HandHoldingDroplet, HandsHeart, RingDiamond,
        ShirtTankTop, CandyBar, GlassHalf, MartiniGlassCitrus, WheatAwnSlash, Boss, PlaneArrival,
        TowerControl, WarehouseAlt, HandLizard, Acorn, AppleCrate, CandyCane, Jug, Sitemap,
        WifiSlash, AttributionPencil, Beacon, BlogPencil, DesktopWallpaper, Followcollection,
        IconStar, StarCommentAlt, TextShadow, BookCircleArrowRight, InputPipe, Escalator,
        PersonSeat, CalendarArrowUp, Snooze, BahtSign, CartMinus, Inboxes, NairaSign, NoteSticky,
        SquarePollVertical, StoreSlash, VoteNay, BracketRound, AddressCard, HundredPoints,
        MessageArrowDown, MessageSms, SquarePhoneHangup, FaceAstonished, FaceConfounded,
        FaceExplode, FaceEyesXmarks, FaceHushed, FaceThinking, HandBackPointDown,
        HandBackPointRight, HandHoldingSkull, HandWave, HandsHoldingDiamond, PuzzleAlt,
        ThoughtBubble, UserGear, Bacteria, Biohazard, Disease, Lips, Pills, Prescription,
        Procedures, PumpMedical, Stretcher, Tubes, UsersMedical, Viruses, CircleHalf, CircleStar,
        ShareSquare, CameraRetro, Clone, Eraser, FileAudio, Outdent, Swatchbook, SquareY, Alien,
        BookDead, ClawMarks, Galaxy, HoodCloak, PortalExit, Stocking, Transporter1,
        TransporterEmpty, UserRobot, DiamondExclamation, FileZipper, FolderOpen, SignalBarsWeak,
        ToggleOn, BowlChopsticks, CoffeeBean, CircleH, GlassWhiskey, ArrowDownTriangleSquare,
        ArrowLeftFromLine, ArrowTurnDownLeft, ChartWaterfall, SortShapesUp, CircleI, CircleT,
        CircleZ, WaveSine, WaveSquare, CircleEllipsisVertical, DialMedLow, DialMed, GripDots,
        PenFancySlash, PenSwirl, ImageSlash, Guitars, RectanglesMixed, Mountain, Sailboat, Mercury,
        Neuter, Axe, Faucet, Flashlight, BrailleX, BrailleZ, FireExtinguisher, Plug, Screwdriver,
        TabletAndroid, PersonCircleExclamation, Couch, DigitalTachograph, SoapAlt, TabletRugged,
        Shower, DumpsterFire, Moped, ShieldCross, VacuumRobot, WindowFrameOpen, ShieldMinus,
        ShowerDown, HorseSaddle, Monkey, DisplayMedical, DisplaySlash, GrillHotAlt, Dragon, Narwhal,
        Rabbit, SpiderBlackWidow, Whale, BootHeeled, Tshirt, CakeSlice, Badminton, GoalNet, QuizAlt,
        ScrollOld, SkiBootSki, Citrus, KiwiFruit, LeafyGreen, Butter, Flatbread, JugBottle,
        Pancakes, Popsicle, Answer, CatalogAlt, CatalogMagazine, InviteAlt, MeetingAlt, Rank,
        RankingPodium, TextBoxDots, WishlistHeart, WishlistStar, ArrowProgress, Mode,
        DirectionSignal, Chatbot, UserInterfaceUi, Investment, Refund, BuildingNgo, TeamCheckAlt,
        ToDoAlt, DriverMan, Sunday, PhotoCapture, EmployeesWomanMan, Method, Percent90, Restock,
        Customize, HexagonDivide, PlaceOfWorship, ToriiGate, TruckBox, BarberPole, PasswordAlt,
        Dinner, Mix, Banner3, CurveAlt, Nose, Picking, QueueAlt, Multiple, OvalAlt, Oval,
        RotateSquare, DominoEffect, Insight, MegaphoneAnnouncementLeader, PickingBox,
        BenefitDiamond, Age, Trust, LightbulbCfl, BrakeWarning, PigBankBulb, ThreeLeafClover,
        TruckFire, Mp3File, Mp4File, PptFile, FeedbackCycleLoop, SpeechBubbleStory, CandlePoseYoga,
        DownFromBracket, DisplayChartUp, Free, PreviousSquare, SurveyXmark, Auction, LeadershipAlt,
        OrganizationChart, SalaryAlt, NotFoundMagnifyingGlass, NetworkAnalytic, CheapDollar,
        Percent40, Sell, Supplier, Customization, Floor, ShieldDog, SpringCalendar, OctagonMinus,
        OctagonXmark, PrayingHands, SquareDivide, Seal, Svg, AdPaid, BonusStar, Channel,
        TransformationDesign, FaceSunglassesAlt, MoneyBillTransfer, MoneyTransferSmartphone,
        SkillAlt, PlantSeedInvest, ShieldSecurityRisk, HandshakeDealLoan, LimitHand, AgeAlt, Life,
        PlugCircleMinus, _70sMusicDisc, BagShoppingMinus, Dropdown, PointerText, PaperPlaneLaunch,
        SunSalutationYoga, ChatBubbleCall, TimerClockCall, CloudGearAutomation,
        TrophyAchievementSkill, TurnLeftDown, MoneyWings, PlayMicrophone, CompassSouth,
        PriorityArrow, Algorithm, GalaxyAlt, Operation, UpRightFromSquare, Url, Budget, Leadership,
        Risk, FunctionProcess, Productivity, UxBrowser, Builder, FloorAlt, LionHead, Pollution,
        Integral, OctagonExclamation, TruckArrowRight, RankingPodiumEmpty, SoldHouse, Javascript,
        Otp, PasswordComputer, UiUx, PointOfSaleBill, GroceryBag, TransformationShapes, Pending,
        InfoGuide, PlantCare, PlantGrowth, ScrewAlt, LightbulbCflOn, HatBeach, Joker,
        ChartPieSimpleCircleDollar, UnderConstruction, UpFromBracket, CvvCard, ThirdMedal,
        WheatAwnCircleExclamation, BeerMugEmpty, DiaryClasp, FeedbackAlt, LiveAlt, RankingStars,
        Videoconference, ClearAlt, SwipeDown, ArrowsToEye, LandLayerLocation, PigFace, SourceData,
        CalculatorMoney, Challenge, Compliance, GovernmentFlag, DriverWoman, TrainStation,
        EmployeeAlt, EmployeeManAlt, Rent, Fail, LeaderboardAlt, UserSalary, ClockUpArrow,
        CheapStackDollar, Percent10, Percent25, Drawer, CatHead, Ankh, GreaterThan, Analyse,
        BenefitPorcent, FeeReceipt, AgeRestrictionThree, Module, Spy, GuideAlt, RulesAlt, Skill,
        Blood, DocumentCircleWrong, GovernmentBudget, TimeWatchCalendar, IotAlt, Screw,
        SolarPanelSun, BenefitDiamondAlt, Referral, GreekHelmet, GolfHole, HorseshoeBroken,
        SystemCloud, RoadBarrier, HandshakeTrust, Treadmill, LocationPinCall, ChartLineUpDown,
        EndlessLoop, ForeignLanguageAudio, Replay10, SpainMap, PuzzlePieces, CarJourney, AuditAlt,
        Audit, BadgetCheckAlt, Blockchain3, CheapBill, Percent30, Percent60, SupplierAlt, Damage,
        GreaterThanEqual, LessThan, Omega, ExpenseBill, LawyerMan, Onboarding, SpeedometerKpi,
        Banner4, TransformationCircle, AgeRestrictionTwentyOne, ArrowComparison, PersonCv,
        LessonClass, ModelCubeArrows, StudentAlt, ArrowUpwardGrowthCrypto, PiggyBankBudget,
        CareerGrowth, LeadFunnel, Mortgage, RevenueEuro, Snap, Roulette, TruckUtensils,
        PuzzlePieceIntegration, ArrowsSplitUpAndLeft, GroupArrowsRotate, Replay30, CompassEast,
        RefundAlt, HrGroup, CustomerService, Brand, Saturday, CheapStack, ClipboardExclamation,
        Percent100, Selling, Warranty, CustomizeComputer, Lion, BookHeart, TruckCheck, DocumentPaid,
        QueueLine, TipCoin, Muscle, GrowthChartInvest, PeopleRoof, BasketShoppingMinus,
        MemberSearch, ProgressUpload, AnatomicalHeart, DumbbellWeightlifting, BellNotificationCall,
        InboxFull, MailboxEnvelope, ThunderstormRisk, BasketShoppingPlus, WineGlassEmpty, CardHeart,
        CardSpade, NestingDolls, HoneyPot, AnswerAlt, DiaryBookmarkDown, FeedbackHand, Description,
        AddImage, PlugCable, Deposit, Revenue, Total, EmployeeMan, LeaderAlt, Department, HandBill,
        DurationAlt, Tuesday, CrmComputer, Assign, Employees, SendMoney, WorkInProgress, SofaSize,
        BioLeaves, Waste, BellSchoolSlash, Workshop, LawyerWoman, PaymentPos, ConvertDocument,
        MembershipVip, PlanStrategy, RecipeBook, MultipleAlt, Effect, ModelCubeSpace,
        GiftBoxBenefits, LeadManagement, _00sMusicDisc, Desk, ArrowsToCircle,
        ChartMixedUpCircleCurrency, HighFiveCelebrationYes, RunningTrack, ThumbsUpTrust,
        ArrowsSplitRightAndLeft, HoldingHandGear, SummaryCheck, ErrorCamera, ReflectHorizontalAlt,
        CompassWest, RegistrationPaper, RiskAlt, AssessmentAlt, Duration, NotFoundAlt,
        SpeedometerArrow, Debt, Percent75, Percent80, SendMoneySmartphone, DogLeashed, PawHeart,
        Intersection, Om, WomanScientist, MarketplaceStore, Marketplace, Banner5, CurveArrow,
        AgeRestrictionZero, TorchInspirationLeader, SmartHome, UserCoach, UserTrust,
        OperatingSystemUpgrade, ChoirSinging, DumbbellFitness, FingerprintSecurityRisk,
        GroupCommunitySocialMedia, Excavator, TurnRight, CardinalCompass, CompassNorth, SleepingBag,
        _404, NotFound, Payroll, StageTheatre, WastePollution, OctagonPlus, ReservationSmartphone,
        ReservationTable, SoldSignal, Bonus, Kpi, MilkAlt, Recipe, TransformationBlock,
        TogetherPeople, SkillUser, StoryBook, ChecklistTaskBudget, KeyLockCrypto, Iot, Scooter,
        ImproveUser, TalentHand, Introduction, PlugCircleCheck, _60sMusicDisc, DropdownSelect,
        GlobePointer, MovFile, QuillPenStory, ScrollDocumentStory, CandleLotusYoga,
        HeartHealthMuscle, JumpingRope, BrokenChainLinkWrong, AnglesUpDown, Swap, ClipboardQuestion,
        Skip15Seconds, StopSquare, SubtitlesSlash, CheckOutCalendar, Monday, Thursday, IssueLoupe,
        Percent50, BoothCurtain, DrawerAlt, StageConcert, BadgeLeaf, Bio, ShieldCat, Bible,
        Chalkboard, EmptySet, Lambda, RegionPinAlt, HairClipper, PasswordEmail, Fee, KpiEvaluation,
        NoFee, Paid, Membership, Seller, GroceryBasket, InsertArrows, Insert, SkinHair,
        PeopleNetworkPartner, PodiumVictoryLeader, StoreBuyer, PersonShelter, PlugCircleExclamation,
        Meditation, PointerLoading, BalletDance, LoopSquare, RightFromBracket, InsertCreditCard,
        LastSquare, ExternalHardDrive, Pig, BudgetAlt, CalculatorBill, Invest, Guide,
        CustomizationCogwheel, Fabric, Violin, AirPollution, Pets, NotEqual, OctagonDivide,
        BuildingCircleArrowRight, RegionPin, TruckArrowLeft, Token, UserKey, PlateUtensils,
        UtensilsSlash, Banner2, Curve, AgeRestrictionEighteen, BookPlus, FunctionSquare,
        StoryFairyTale, StoryFantasy, SkinDrop, LeaderSpeech, WalletBuyer, CalendarPaymentLoan,
        EmployeeHandbook, CloudBackUpAlt, CloudBackUp, SmartHomeAlt, BenefitHand, Benefit, BonusAlt,
        ConveyorBeltArm, PlugCirclePlus, Webhook, MemberList, RadioButton, DashboardMonitor,
        AudienceMegaphone, TurnLeft, BlockMicrophone, Replay5, Mango, BottleDroplet, DiaryBookmarks,
        FeedbackReview, JournalAlt, Preview, WorkflowAlt, GalaxyPlanet, MatchFire, PlugAlt,
        RevenueAlt, ToDo, StateCountry, Legal, Loan, Expense, LeaderboardTrophy, DailyCalendar,
        Wednesday, CrmAlt, PayrollCalendar, FloorLayer, Tie, CircleDivide, Hamsa, UsersClass,
        MosqueMoon, LockHashtag, PointOfSale, Milk, InsertAlt, Queue, AgeRestrictionSix,
        AgeRestrictionSixteen, MoneyCoinTransfer, ModelCube, Rules, MouseField, BackUp, RoboticArm,
        BenefitIncrease, TalentAlt, DumbbellRay, BagMapPin, TruckLadder, IpAddress, Burst,
        FolderFire, AirplaneWindowOpen, MapPoint, PersonLuggage, Choose, Features, Journey,
        TrainJourney, Branding, InsightHead, Leaderboard, CheckInCalendar, CorporateAlt, Corporate,
        ProblemSolving, Shirt, Sofa, FlowerButterfly, LessThanEqual, OctagonCheck, MosqueAlt,
        ScaleComparisonAlt, MarketplaceAlt, PadlockCheck, SellerStore, GraphCurve, InsertSquare,
        QueueSignal, TargetAudience, AgeRestrictionTwelve, InsightAlt, MoneyTransferAlt, Lesson,
        CircleOverlap, CalendarGavelLegal, _90sMusicDisc, SkeletonRibs, SpartanHelmet, Horseshoe,
        RecycleBin, ShieldTrust, CourtSport, IncenseSticksYoga, StrategyChessRisk, EmailPending,
        MailboxFlagUp, ArrowDownFromArc, ArrowLeftFromArc, ChartKanban, LeftFromBracket,
        CreditCardEye, ClipoardWrong, PauseSquare, RewindButtonCircle, Tricycle, BloodDropper,
        ChooseAlt, Selection, Accident, TourGuidePeople, TrainStationBuilding, RentSignal,
        WalletArrow, VideoDuration, Ux, Blueprint, CustomizeEdit, Handmade, Divide, Gopuram, Kaaba,
        ManScientist, Practice, Script, UserGraduate, Booking, RazorBarber, HashtagLock,
        PasswordSmartphone, AgeRestrictionSeven, AgeRestrictionThirteen, Cryptocurrency,
        MoneyTransferCoinArrow, Student, BloodTestTube, HoldingHandRevenue, Lead, Raccoon,
        ReferralAlt, TrustAlt, PlugCircleBolt, _80sMusicDisc, Chip, LaptopBinary, ProgressComplete,
        ChartMixedUpCircleDollar, WebDesign, StationaryBike, BellNotificationSocialMedia,
        CalendarCall, GroupCall, PhoneGuide, ArrowLeftToArc, Wave, CircleNodes, OrderHistory,
        Resume, SquareDashedCirclePlus, SurveillanceCamera, Third, Walking, MelonAlt, Peanuts,
        SandwichAlt, Catalog, AdminAlt, DirectionSignalArrow, Refer, ChatbotSpeechBubble,
        PlugConnection, CoinUpArrow, ComplianceDocument, Completed, Hr, TabFolder, Crm, Percent20,
        Percent70, Stage, SunglassesAlt, Equals, Mosque, Synagogue, Vihara, Visit, AnalyseAlt,
        PointOfSaleSignal, DotPending, LightbulbHead, Function, BloodTestTubeAlt, Skin,
        CreditCardBuyer, HeartPartnerHandshake, ShoppingCartBuyer, CareerPath, ReferralUser,
        IntroductionHandshake, FlaskGear, SlotMachine, ProgressDownload, Branching,
        ChartPieSimpleCircleCurrency, ResistanceBand, CalendarBirhtdayCake, StarRatingCall,
        ArrowUpFromGroundWater, UserSkillGear, ArrowProgressAlt, RotateReverse, ArrowTurnLeftUp,
        CryptoCalendar, FreeDelivery, PayrollCheck, WhiteSpace, CompassAlt, GovernmentUser,
        AirplaneJourney, Leader, Assessment, BillArrow, CalendarSalary, DepartmentStructure,
        LimitSpeedometer, Plan, Cheap, Knitting, Church, ScaleComparison, Banner, Cv,
        ExchangeCryptocurrency, ConvertShapes, SourceDocumentAlt, SourceDocument, SkinArrow,
        CalculatorMathTax, CalendarEventTax, ClockTimeTracking, BinBottles, MeasuringTape, General,
        Talent, DashboardPanel, InternetSpeedWifi, ToiletsPortable, ArrowUpToArc, FileCloud,
        InsertButtonCircle).sortedBy { it.name }
    return __Filled!!
  }
