package me.localx.icons.straight

import androidx.compose.ui.graphics.vector.ImageVector
import me.localx.icons.straight.outline.*
import kotlin.collections.List as ____KtList

private var __Outline: ____KtList<ImageVector>? = null

public val Icons.Outline.allIconsList: ____KtList<ImageVector>
  get() {
    if (__Outline != null) {
      return __Outline!!
    }
    __Outline = listOf(Marker, User, Home, Heart, Search, Bell, Calendar, Settings, PaperPlane,
        Trash, ShoppingCart, RocketLunch, Building, Eye, Edit, Envelope, PhoneCall, MapMarker,
        Users, Comment, TruckSide, Globe, UsersAlt, Share, ShieldCheck, Coins, BookAlt, SackDollar,
        Star, Apps, AngleRight, Document, Add, SettingsSliders, Pool8Ball, Bulb, AngleLeft,
        Computer, UserAdd, Info, Pencil, Disk, ChartHistogram, Lock, AngleDoubleRight, SearchAlt,
        Comments, ShoppingBag, BookBookmark, Check, Shop, ArrowRight, Interrogation, Gift, Print,
        Bank, Cross, Briefcase, CommentAlt, Flame, BurgerMenu, SignInAlt, UsdCircle, Following,
        MapMarkerEdit, Megaphone, CalendarClock, Ticket, Key, AngleDown, Diploma, CrossedEye,
        Download, Folder, Bookmark, HandHoldingDroplet, Picture, Exclamation, Bolt, Boxes, World,
        TruckMoving, Play, ELearning, AddDocument, SocialNetwork, BookCircleArrowUp, BellRing, Form,
        FileCircleInfo, Filter, Notebook, Refresh, Handshake, Exit, ArrowSmallDown, ClipboardList,
        BadgeCheck, MusicAlt, ChartLineUpDown, Sparkles, Trophy, Receipt, Badge, MagicWand,
        CassetteTape, Camera, Browser, PuzzlePiece, AngleSmallLeft, Thumbtack, DocumentSigned,
        Clean, Laptop, CircleQuartersAlt, CopyAlt, CirclePhone, Map, Plus, Screen, AlarmClock,
        ArrowSmallLeft, FileInvoice, Stats, CircleCross, Diamond, CreditCard, Gym, CommentQuestion,
        DataTransfer, Headset, Books, AppsAdd, ListCheck, ArrowLeft, ChartTree, School, Raindrops,
        CarSide, Database, CommentsQuestion, MemoCircleCheck, List, GraduationCap, Cursor,
        ShoppingBagAdd, CalendarGavelLegal, Clock, HoldingHandRevenue, Volume, MoneyBillTransfer,
        ShoppingBasket, AddressBook, IdBadge, Microphone, Film, At, ClockThree, Flag, Duplicate,
        HeadSideMedical, LocationAlt, CrossSmall, Shield, CommentInfo, AsseptDocument,
        AngleSmallDown, Navigation, MoneyBillWaveAlt, Smartphone, Box, MindShare, MenuDots,
        PlaneAlt, Book, ArrowCircleLeft, Ballot, Clip, CakeBirthday, Dashboard, Expand, StoreAlt,
        TimerClockCall, Palette, BadgePercent, Copy, PlusSmall, Pixabay, Stethoscope, Moon,
        CalendarCheck, Donate, ShieldExclamation, Treatment, CloudBackUpAlt, LinkAlt,
        CircleHalfStroke, HamburgerSoda, HandHoldingMagic, TimeFast, HatChef, Undo, Sun, MoonStars,
        BookOpenCover, PaintBrush, PiggyBank, Gem, CircleSmall, Leaf, TimePast, ChartNetwork, Pulse,
        FolderDownload, Hamburger, WomanHead, AngleCircleUp, CommentCode, Checkbox, ModePortrait,
        EnvelopeOpen, ClockFive, Wallet, WifiAlt, SmileBeam, Circle, BoxAlt, File, Layers, Ban,
        AlbumCircleUser, Stopwatch, RotateRight, Restaurant, ChartConnected, ChildHead, PlayAlt,
        EditAlt, Headphones, Delete, Calculator, MicrophoneAlt, FolderTree, _90sMusicDisc, Dollar,
        LifeRing, CalendarLines, Ship, Square, CloudShowersHeavy, Mouse, GlassCheers, CommentQuote,
        DeleteDocument, CommentHeart, CursorFinger, NetworkCloud, Doctor, Interactive, Venus,
        HouseFlood, CloudSun, FolderUpload, UtilityPoleDouble, Upload, FlowerTulip, ChairOffice,
        RulerCombined, ArrowsRepeat, RemoveUser, EnvelopeOpenDollar, FlagAlt, Qrcode, InboxIn,
        CommentAltEdit, RoomService, Happy, Confetti, MobileNotch, Fill, _60sMusicDisc, LayerPlus,
        ThumbsUpTrust, DeleteUser, Shuffle, ZoomIn, Biking, TestTube, _00sMusicDisc, SearchHeart,
        BoxCheck, Football, WrenchSimple, EnvelopePlus, Mountains, Keyboard, Running, Humidity,
        Stars, CarBuilding, Cars, Garage, Umbrella, Guitar, CashRegister, Fingerprint,
        RectangleHorizontal, Archive, BikingMountain, HandFingersCrossed, Wheat, FileSpreadsheet,
        TimeForward, Mobile, FeedbackCycleLoop, DisplayCode, Gifts, Sack, Car, ArrowAltToLeft,
        Folders, RingsWedding, VideoCamera, Coin, CommentDollar, Fox, ExpandArrows, Asterik,
        AppsDelete, FrenchFries, MugHot, Bus, ChargingStation, UsdSquare, MoneyCheck, Resize, Water,
        FilterSlash, PencilRuler, Strawberry, TemperatureFrigid, Subway, Filters, Physics, Euro,
        Subtitles, Cow, ChessClockAlt, TachometerFast, ToolBox, TreasureChest, CompressAlt,
        CocktailAlt, Plate, AirConditioner, TimeAdd, Medicine, SortAlt, CalendarPlus, PaintRoller,
        PlayPause, QuestionSquare, Basketball, Sticker, Sword, Inbox, Cupcake, GrinBeam, CloudsSun,
        Smoke, SteeringWheel, TimeDelete, BarberShop, Rocket, Soup, Butterfly, CakeWedding, Wind,
        Mailbox, BrainCircuit, RectangleXmark, Spinner, GrinHearts, Grill, WaterBottle, DiceD6,
        CalendarMinus, CommentsDollar, MoneyBillWave, Tablet, Bug, DrinkAlt, StarOctogram,
        Wheelchair, LaptopCode, EnvelopeMarker, Croissant, Steak, DiceAlt, Taxi, PhonePause,
        SadTear, Snowplow, Tire, Tags, Syringe, ShirtLongSleeve, HomeLocation, Crown, CloudUpload,
        Plane, Gallery, CommentCheck, Pharmacy, CloudShare, DoNotEnter, CaretDown, Unlock,
        HourglassEnd, Portrait, Cube, TruckLoading, Target, PizzaSlice, RotateLeft, ArrowUpLeft,
        Bed, BagsShopping, Paw, SignalAlt1, ShieldSecurityRisk, SearchLocation, UserTime,
        ChartTreeMap, Test, Text, Redo, Tree, BedAlt, TruckContainer, Earnings, Cloud, LogOut,
        LevelUpAlt, CarAlt, Flower, CommentArrowUp, Music, ManHead, EngineWarning, CommentPen,
        TimeCheck, MapMarkerHome, Gamepad, Forward, CommentUser, Bullseye, RulerTriangle, BusAlt,
        Equality, CommentSms, CloudDownload, Enter, CircleEnvelope, AngleCircleRight, Mars,
        ArrowUpRight, ArrowUpLeftFromCircle, AddFolder, Resources, AngleUp, Road, SignalAlt2,
        BloodTestTube, AlignJustify, AppsSort, AppleWhole, ArrowCircleDown, CalendarPen,
        CallOutgoing, BusinessTime, Presentation, ArrowDown, Utensils, Loading, Ambulance, Link,
        Balloons, PeoplePoll, ArrowsHCopy, Grid, MinusSmall, GiftCard, ModeLandscape, PhoneOffice,
        AngleDoubleLeft, EnvelopeDownload, GrinAlt, AlbumCirclePlus, Hand, ShieldPlus,
        AngleCircleLeft, TemperatureHigh, InboxOut, MoneyCheckEdit, UsbPendrive, Bike, BadgeDollar,
        AlarmExclamation, Copyright, Popcorn, BullseyePointer, CallIncoming, Fish, Salad,
        CarMechanic, Coffee, ChartPie, Grin, MobileButton, Sad, FolderMinus, Volleyball, Pause,
        TreeChristmas, ArrowAltLeft, Comet, ArrowUpFromSquare, CaretRight, Recycle, Motorcycle,
        AngleSquareLeft, BarsProgress, VectorAlt, Rewind, Network, Money, ArrowsAltH, ZoomOut,
        CarBattery, ArrowToTop, Rugby, Vector, MapMarkerCross, SearchDollar, Highlighter,
        CommentExclamation, BarcodeRead, TimeQuarterPast, PlayingCards, Cheese, Chocolate,
        ClockNine, Label, ThermometerHalf, Arrows, Tractor, BagShoppingMinus, CircleBookOpen,
        LockAlt, Scale, ArrowUp, CommentText, ArrowTurnDownLeft, Triangle, Exchange,
        LightbulbDollar, Infinity, DiceD20, EclipseAlt, TemperatureLow, GarageCar, RubleSign,
        MusicFile, Lipstick, Package, RecordVinyl, BagMapPin, Percentage, GrinStars, Sandwich,
        ArrowAltUp, Summer, GridAlt, CallHistory, Meh, Snowflake, Stamp, ArrowTrendUp, Backpack,
        LetterCase, Speaker, ToolCrop, Beer, Glass, EyeDropper, Camping, Calendars, SensorFire,
        SmileWink, ChessQueen, StrategyChessRisk, SignalAlt, Train, MugAlt, ChartScatterBubble,
        SuitcaseAlt, CommentXmark, Spa, SchoolBus, Drumstick, BreadSlice, BaseballAlt, AlignLeft,
        Pepper, ClockTwo, Registered, DraftingCompass, Reflect, SunriseAlt, CarCrash, FighterJet,
        BadgeSheriff, CommentAltMusic, LuggageRolling, CandyAlt, Candy, Turkey, StarSharpHalf,
        AnglesUpDown, SlidersVSquare, SortAlphaUpAlt, Golf, CupStrawSwoosh, CaretUp, Cookie,
        Interlining, Mug, Tomato, Skating, ArrowAltFromLeft, CodeSimple, IceSkate, Italic,
        ChartPyramid, CannedFood, Mushroom, Pot, AngleSquareUp, ArrowUpwardGrowthCrypto,
        DownFromBracket, Gif, Yen, DiscoBall, SaltPepper, BowArrow, TireRugged, B, ClockSevenThirty,
        Dart, GasPump, HatBirthday, LaughSquint, Fork, Lettuce, CandlePoseYoga, ClockFourThirty, D,
        BlindsOpen, Keynote, ArrowUpSmallBig, Dizzy, Skewer, Sort, CandleLotusYoga, Luchador,
        CloudSleet, TruckMonster, WagonCovered, CirclePhoneFlip, ArrowsCross, Dice, Grimace,
        HockeyPuck, Volcano, Sleigh, Democrat, P, R, BlindsRaised, BoxTissue, MessageCode,
        SquareTerminal, Bells, ObjectIntersect, ObjectSubtract, Onion, CalendarLinesPen,
        BowlingBall, Sledding, Tram, SlidersHSquare, ChevronDoubleDown, ShekelSign, F, G, I, U,
        CodeCommit, RectangleBarcode, Circle1, Circle4, Circle6, Circle7, ArrowSmallUp, Curling,
        DiceOne, CaravanAlt, FireFlameSimple, AngleDoubleSmallRight, N, Blinds, TruckContainerEmpty,
        _3, _7, Circle0, Square1, Square2, Square4, Square6, Square7, BorderBottom,
        BinaryCircleCheck, BorderNone, BorderOuter, CassetteVhs, CircleDashed, ChessRookAlt,
        TextWidth, HatCowboySide, HeadSideCough, BatteryFull, BatteryQuarter, BalanceScaleLeft,
        DoorClosed, Hammer, HeadVr, LightSwitch, BenchTree, BoxFragile, BorderCenterV, BoxOpen,
        Fence, HomeLocationAlt, HouseTree, IndustryWindows, IslandTropical, LinkSlashAlt,
        LuggageCart, Monument, MoneyTransferAlt, Parking, Passport, PlaneProp, RampLoading,
        RouteInterstate, SeatAirline, SignHanging, SquarePlus, ToiletPaperUnder, FileExcel,
        FilePowerpoint, SignalStream, WifiExclamation, HandHorns, HeartCrack, PenNibSlash, Bone,
        Question, TextBoxEdit, Brush, Hastag, ClockSeven, Bahai, VideoPlus, GlobeAlt, Swimmer,
        BabyCarriage, CarGarage, PhotoVideo, Barcode, Rec, MapLocationTrack, FlowerBouquet, Glasses,
        GingerbreadMan, ClockOneThirty, QuoteRight, UndoAlt, FileInvoiceDollar, CloudRain,
        CalendarExclamation, BellSchool, PingPong, Ad, BoxBallot, CaretLeft, MugTea, ArrowLeftToArc,
        Snowflakes, MakeupBrush, Bowling, Cocktail, Pyramid, Broccoli, Dewpoint, BarcodeScan,
        FileCode, RectanglePanoramic, Stop, Egg, Whistle, ArrowAltToBottom, FolderTimes,
        PersonCarryBox, Protractor, Poo, Cherry, TachometerSlow, A, LayerMinus, CodeBranch,
        TextCheck, Bold, FilePsd, Carrot, ArrowsH, HockeyMask, Skiing, TachometerAverage, TruckPlow,
        ArrowAltCircleUp, ClockTen, GrinWink, SadCry, Spoon, Watermelon, DiceD4, ConveyorBeltAlt,
        ArrowUpSquareTriangle, FlipHorizontal, TrainSide, Picnic, Pineapple, ChessKingAlt,
        RugbyHelmet, CloudHail, OilCan, E, GlassWaterDroplet, Kiss, ArrowDownToSquare,
        AngleSquareDown, Club, DiceD12, Meteor, Thunderstorm, TachometerSlowest, EnvelopeBulk, S,
        ArrowCircleUp, TablePivot, BandAid, FileEps, RedoAlt, GrinSquintTears, Smog, KissBeam,
        Lemon, Sauce, AngleDoubleSmallUp, CaretCircleDown, ChessBoard, HockeySticks, SkiingNordic,
        TemperatureDown, ThunderstormSun, Starfighter, CommentAltMiddle, BookFont, Rainbow,
        GaugeCircleMinus, CaretCircleUp, ChessPawn, Snowboarding, ThunderstormMoon, WaterRise,
        Trailer, AgeRestrictionThirteen, _80sMusicDisc, AlarmSnooze, CirclePhoneHangup, ClockEleven,
        Hryvnia, SensorSmoke, ArrowRightToBracket, Square5, ObjectExclude, ObjectUnion, Radish,
        DiceFour, ClockFiveThirty, CarBump, Snowmobile, SortNumericDown, CircleThreeQuarters,
        CheckOutCalendar, C, CarBolt, Tally, Circle5, Skateboard, LacrosseStickBall, BowlingPins,
        ChatBubbleCall, ChessKnight, Dreidel, SkiLift, _70sMusicDisc, H, O, Q, Y, _0, _2, _4, _9,
        Square0, Square8, BookArrowRight, BorderInner, BorderLeft, BorderRight, BasketShoppingPlus,
        BorderStyle, BringForward, BringFront, CodePullRequestClosed, HeadSide, HandshakeDealLoan,
        HeadSideHeadphones, BatterySlash, HammerWar, ItalianLiraSign, BookAtlas, BoxUp, Cabin,
        ConciergeBell, ChartSetTheory, FileChartLine, FishingRod, FlagCheckered, Fort, HotTub,
        HouseBlank, HouseTurret, LandmarkAlt, PlaneTail, TruckCouch, SmileyCommentAlt, CommentImage,
        Compress, Sushi, SnowBlowing, CarWash, TachometerFastest, AngleDoubleSmallDown,
        ArrowTurnLeftUp, CodeCompare, Scissors, FaceTongueSweat, Chair, Grape, BasketballHoop,
        TabletAndroidAlt, AngleSquareRight, Cream, Laugh, X, DiagramProject, Tooth, MaskCarnival,
        Kite, Peach, SmartHomeAlt, AlarmPlus, SensorOn, RulerVertical, Typewriter, Clouds, Taco,
        GolfClub, Eclipse, Rv, FileVideo, CursorPlus, AlignCenter, CoffeePot, Hotdog, CloudShowers,
        Hurricane, TemperatureUp, CursorText, Frown, ChessKnightAlt, CloudHailMixed, Burrito,
        Noodles, DiceD8, Sunset, SortAmountDownAlt, FlagUsa, Flushed, Aubergine, Olives, Cricket,
        DiceThree, CommentAltMinus, CrystalBall, CallMissed, LaughWink, Tired, Sausage, ChessBishop,
        ChessRook, Pennant, Fog, WaterLower, ClockTwelveThirty, FilmSlash, Lasso, LineWidth, Symbol,
        Bacon, ChatbotSpeechBubble, ArrowsAltV, DiceSix, PodiumStar, MartiniGlassCitrus, ArrowsAlt,
        ArrowSquareRight, Shuttlecock, CloudDownloadAlt, ChartScatter, ArrowsToLine, SidebarFlip,
        TableColumns, CloudDisabled, Underline, GraphicTablet, Corn, EggFried, ArrowsToCircle,
        LevelUp, ChessKing, SkiJump, HelicopterSide, StoryFairyTale, TruckRamp, SignalStreamSlash,
        SignalAltSlash, ClockTwelve, Republican, TextSlash, Cowbell, Garlic, Pumpkin,
        ArrowSquareLeft, GolfBall, WindWarning, ThermometerThreeQuarters, L, M, W, Sensor, Circle2,
        Circle8, Windsock, ArrowAltFromRight, J, T, Z, CalendarArrowDown, Kerning, _1, _8, Square9,
        Betamax, BorderAll, CartShoppingFast, DirectionSignalArrow, GalleryThumbnails,
        HighlighterLine, TextSize, HandshakeSimpleSlash, BatteryBolt, BatteryEmpty, BatteryHalf,
        DoorOpen, HammerCrash, LightSwitchOff, Projector, Archway, Binoculars, Castle,
        HouseChimneyHeart, HoldingHandGear, HouseMedical, HouseWindow, Igloo, LocationCrosshairs,
        LockOpenAlt, LocationCrosshairsSlash, ItComputer, ParkingCircle, ParkingSlash, RouteHighway,
        ShoePrints, StreetView, TicketAlt, TrophyStar, VestPatches, Wifi2, People, PeopleDress,
        CandyCorn, CheeseAlt, AnimatedIcon, AttributionPen, BrokenImage, FollowFolder, NoPeople,
        Pattern, Picpeople, PicpeopleFilled, Replace, Template, TemplateAlt, BookQuran,
        CircleBookmark, Baby, GarageOpen, TvMusic, Feather, Minuss, Chess, ChartArea, SensorAlert,
        VenusMars, CloudCheck, LaughBeam, AngleCircleDown, AngleSmallUp, BenefitDiamondAlt,
        TimeOclock, Hourglass, Ftp, ShieldInterrogation, HeartArrow, InternetSpeedWifi, Hiking,
        MarkerTime, PokerChip, CaretSquareRight, Rhombus, Bread, ExchangeAlt, EnvelopeOpenText,
        RulerHorizontal, ChessPiece, Bottle, Shrimp, Incognito, Pound, Angry, CarBus, TireFlat,
        Braille, FunnelDollar, AirFreshener, ShipSide, IceCream, Terrace, Heat, Password, Soap,
        Tennis, Surfing, GrillHotAlt, CloudMoon, Camcorder, CodeFork, Pie, Racquet, TimeForwardTen,
        SquareRoot, RectabgleVertical, Indent, PepperHot, BoxingGlove, ShuttleVan, TruckPickup,
        PageBreak, LinkHorizontal, Jpg, Baseball, ArrowAltToTop, Sunrise, FerrisWheel, OliveOil,
        ChessQueenAlt, SpaceShuttle, ArrowAltRight, CaretSquareDown, ArrowsToEye, FileAi,
        EnvelopeBan, PhoneSlash, PhoneCross, Surprise, ArrowLeftFromLine, CalendarEventTax,
        LevelDown, CloudDrizzle, CloudUploadAlt, CommentSlash, ArrowsRepeat1, CloudSunRain,
        ToolMarquee, Opacity, Knife, CloudMoonRain, GrinTears, DiceD10, ClockOne, CloudRainbow,
        ArrowAltDown, LightEmergencyOn, Overline, ArrowSquareUp, CodeMerge, RectangleCode,
        TableLayout, TableTree, Transform, GrinTongue, MehBlank, Jam, Melon, Pan, ArrowAltToRight,
        CloudsMoon, AngleSmallRight, Tty, ClipboardListCheck, LinkSlash, TableRows, TextBoxDots,
        Billiard, Sphere, MarsDouble, GrinSquint, Avocado, CaretCircleRight,
        ArrowDownTriangleSquare, ChessClock, CloudSnow, ClockNineThirty, LiraSign, Podium, Tenge,
        LevelDownAlt, Circle3, AlbumCollection, VenusDouble, AirplaneWindowOpen, Spade, CarTilt,
        Caravan, OilTemp, Tachometer, ReplyAll, SortAmountDown, ChessPawnAlt, ClockSix, V,
        UserInterfaceUi, Sidebar, SquareCode, Circle9, CowbellMore, Tornado, CalendarArrowUp,
        CheapStackDollar, DiceTwo, FieldHockey, SortDown, CircleEllipsisVertical, RupeeSign, K,
        VideoSlash, _5, _6, CrossReligion, Square3, AgeRestrictionZero, Album, BorderTop,
        GridDividers, LassoSparkles, TextHeight, Brain, FaceEyesXmarks, HeadSideThinking,
        BlockBrick, Block, Apartment, Bomb, City, Dungeon, Farm, FireSmoke, Gavel, Hotel,
        HouseBuilding, HeadSideVirus, HouseChimney, HouseCrack, MapPin, Background, Devices, Mockup,
        ReflectHorizontal, BookmarkSlash, InputNumeric, ScrollTorah, BellConcierge, EarthAfrica,
        EarthAsia, TruckTow, WaterLadder, CircleCalendar, ChartUser, DongSign, Envelopes, Fax,
        FlorinSign, LariSign, MillSign, PaperclipVertical, MartiniGlassEmpty, WonSign,
        BatteryThreeQuarters, BracketsRound, BracketsSquare, Microchip, Terminal, BlenderPhone,
        Bullhorn, ChatArrowDown, MegaphoneAnnouncementLeader, MessageImage, MessageQuote, SmilePlus,
        Symbols, FaceConfused, FaceDisguise, FaceExpressionless, FaceRelieved, EyeDropperHalf,
        FaceShush, FaceSwear, FaceTissue, EmployeesWomanMan, GaugeCirclePlus, PersonSimple,
        CircleQuarter, GaugeCircleBolt, PenFancy, RssAlt, SendBackward, Skip15Seconds, Speakers,
        Subscript, Superscript, Table, VolumeDown, SquareM, SquareS, BookSpells, FlaskPotion,
        HatWizard, HollyBerry, Joystick, PortalEnter, Radar, ScrollDocumentStory, Transporter4,
        Transporter7, CloudQuestion, FileEdit, SealQuestion, QuillPenStory, TrashRestore,
        CoffeeBeans, Meat, ArrowDownLeft, ArrowToRight, ArrowToBottom, ChartGantt, DiagramNested,
        DiagramSuccessor, PlugCircleCheck, SquareInfo, CircleO, CircleW, CircleEllipsis, DialMax,
        DialOff, PenField, ToiletPaperBlankUnder, BlockQuote, FaceViewfinder, ForwardFast,
        ListMusic, PenCircle, PlaceOfWorship, SaxHot, LeafMaple, TeddyBear, Wreath, HandScissors,
        ParachuteBox, Chimney, ScannerImage, BrailleC, BrailleG, DiscDrive, HouseSignal, Satellite,
        SimCard, Tools, UserLock, HouseLeave, LightSwitchOn, ShippingTimed, SolarPanel, Sprinkler,
        DryerAlt, Dryer, GasPumpSlash, ScannerGun, Shelves, Stairs, TimeQuarterTo, TruckFlatbed,
        Dolphin, Trillium, ConveyorBeltEmpty, KeyboardDown, LampStreet, KeyLockCrypto, LaptopSlash,
        MicrochipAi, SpeechBubbleStory, BadgerHoney, Dog, Duck, Frog, Site, FamilyDress,
        FamilyPants, Ring, Socks, UserCowboy, CupStraw, Mace, Quiz, Second, Blueberries, Coconut,
        CrateEmpty, Potato, VideoCameraAlt, BowlScoop, FonduePot, TtyAnswer, Admin, CategoryAlt,
        ExitAlt, Process, SwipeRight, Constellation, LandLayers, BrowserUi, CloudCode, React,
        ChartPieAlt, TeamCheck, CustomerCare, FeaturesAlt, HrPerson, MagnetUser, BicycleJourney,
        TaxAlt, TourVirtual, CallDuration, BrailleNAlt, Friday, PlaneDeparture, RollerCoaster,
        StoreLock, TaxiBus, ToiletPaperSlash, UmbrellaBeach, FileWord, FaceAwesome, HandPeace,
        CopyImage, BreadSliceButter, MemoPad, Notes, SignPostsWrench, Tally2, Tally3, EarthAmericas,
        TicketsAirline, AustralSign, BookSection, BriefcaseBlank, BullseyeArrow, CentSign,
        EnvelopeDot, HandsUsd, HouseChimneyBlank, LightbulbSlash, ManatSign, MessageDollar,
        MessagesDollar, MoneyCheckEditAlt, SignatureLock, SquareKanban, TugrikSign, Vault,
        BracketCurly, BracketsCurly, BracketRoundRight, BugSlash, LaptopMobile, WindowAlt,
        WindowMaximize, WindowMinimize, BowlSoftServe, MessageQuestion, FaceGlasses, FaceParty,
        CloudGearAutomation, FaceUnamused, FaceWeary, PersonDress, SnowmanHead, RectangleVertical,
        Columns3, DrawSquare, H4, Scrubber, StepBackward, VolumeOff, SquareC, SquareH, SquareL,
        SquareP, SquareR, Coffin, LightsHoliday, PoliceBox, Skull, StarShooting, Telescope,
        TombstoneAlt, UfoBeam, BellSlash, CloudExclamation, FileCsv, PartyHorn, ToggleOff,
        TrashCanClock, ArrowsFromDottedLine, BowlRice, Brightness, DiagramNext, DownRight,
        HeadSideBrain, RightFromBracket, Up, BookCopy, CalculatorSimple, CircleD, CircleM, CircleU,
        Dharmachakra, WatchCalculator, WaveTriangle, FaceSunglassesAlt, PenSlash, PencilSlash,
        TrafficLightStop, TrashSlash, VectorCircle, Aperture, CameraCctv, ClapperboardPlay,
        Panorama, StandardDefinition, TintSlash, Turntable, Webcam, PaperPlaneLaunch, ConveyorBelt,
        Dumpster, LampDesk, ShieldAlt, BrailleB, HardHat, PeopleNetworkPartner,
        NotFoundMagnifyingGlass, UserUnlock, Magnet, ScannerKeyboard, Sink, BedEmpty, Drone,
        FanTable, Fan, Fireplace, Refrigerator, Angle90, Engine, Sickle, TruckBolt, MugTeaSaucer,
        Unicorn, BrailleJ, BrailleK, BrailleO, KeyboardLeft, MeterBolt, ToiletPaperBlank, Mound,
        Pompebled, SnowflakeDroplets, Crow, Dove, RabbitFast, Spider, BuildAlt, ItAlt, Balloon,
        Child, ClothesHanger, HandBackPointLeft, HatWinter, ShirtRunning, Transgender, UserTag,
        CupcakeAlt, Award, AxeBattle, First, Cucumber, PanFood, Peapod, PepperAlt, Baguette,
        CubesStacked, SaltShaker, Feedback, Journal, RankingStar, Review, SignUp, Subscription,
        Category, ReferArrow, InsertCreditCard, EarthEuropa, Elevator, TicketAirline, BitcoinSign,
        CarSideBolt, FileSignature, MoneyBills, RectanglePro, Shredder, SquareEllipsisVertical,
        BanBug, BarsSort, Binary, BinarySlash, Gears, CircleUser, CommentDots, Language, Messages,
        NfcMagnifyingGlass, SquareQuote, FaceAngryHorns, FaceFearful, FaceLying, FacePleading,
        FaceSmileHearts, FaceSmileTongue, FaceWoozy, HandDots, HandHeart, HandHoldingUsd,
        HandsBubbles, HandMiddleFinger, LightbulbCflOn, PipeSmoking, UsersGear, CircleBolt, Split,
        ObjectGroup, Podcast, SquareQ, SquareT, CoffinCross, Ornament, SpiderWeb, StarChristmas,
        ChevronDoubleUp, FileDownload, FileImage, FileUpload, GripHorizontal, GripLines,
        HexagonExclamation, LightbulbQuestion, LightbulbExclamation, LocationExclamation,
        ShoppingCartAdd, RankingPodiumEmpty, TimesHexagon, ArrowSmallRight, ChartMixed,
        DiagramPrevious, DiagramSankey, GripLinesVertical, CircleC, CircleK, CircleR, Peace,
        PencilPaintbrush, Tilde, CircleTrash, DialMin, HexagonCheck, SprayCanSparkles,
        SquareEllipsis, CameraSlash, CameraViewfinder, Films, Screencast, TableList, DrumSteelpan,
        ObjectsColumn, RadioAlt, SprayCan, BallPile, Bath, Seedling, CalendarHeart, Blender,
        HouseDay, IndustryAlt, Router, BrailleE, HouseUser, SatelliteDish, SortShapesDown,
        UserMinus, Lamp, SirenOn, BedBunk, DroneAlt, PalletAlt, Frame, GameBoardAlt, HoseReel,
        PhoneRotary, UserRobotXmarks, UtilityPole, Bird, PawClaws, Ram, Squid, BrailleV, Bugs,
        FaceSmilingHands, PumpkinAlt2, Alicorn, CatSpace, DeerRudolph, It, SiteAlt, SiteBrowser,
        Boot, Family, GrinBeamSweat, Piñata, PointOfSaleBill, UserMusic, UserNinja, Banana,
        CandySweet, MarsStrokeUp, WheatSlash, UpRightFromSquare, FirstAward, FirstLaurel,
        FaceDowncastSweat, LacrosseStick, SecondMedal, ThirdAward, CanFood, Pear, BowlSpoon,
        Falafel, JugAlt, SushiAlt, Tamale, Live, Meeting, SubscriptionAlt, DescriptionAlt, DropDown,
        ModeAlt, ArrowsFromLine, PriorityArrow, GalaxyAlt, Algorithm, Pig, Operation, Url,
        BudgetAlt, Budget, CalculatorBill, Invest, Leadership, Guide, Risk, PlugCirclePlus,
        FunctionProcess, Productivity, UxBrowser, Builder, DollyFlatbedAlt, CustomizationCogwheel,
        Fabric, FloorAlt, Violin, Integral, NotEqual, OctagonDivide, OctagonExclamation, SoldHouse,
        Token, RegionPin, Javascript, Otp, Pets, LocationPinCall, Route, TrafficLight, FilePdf,
        SignalBarsGood, Wifi, CircleHeart, BreadLoaf, BurgerFries, Bullet, GraphicStyle, Images,
        MoneyCoinTransfer, BookTanakh, Memo, Note, PersonPraying, Tally1, CalendarImage,
        CalendarWeek, AudioDescriptionSlash, BoxCircleCheck, ChartSimple, DiagramVenn, NfcPen,
        NotebookAlt, PenClip, PollH, PointOfSale, RupiahSign, SignatureSlash, SterlingSign,
        BinaryLock, BracketSquare, Memory, ClockUpArrow, CommentMinus, MessageSlash, Rss,
        EmployeeManAlt, DiamondTurnRight, FaceMonocle, FacePensive, FaceSleeping, FaceSmileTear,
        FaceWorried, HandBackPointRibbon, GasPumpAlt, UserSlash, Right, SealExclamation,
        CameraSecurity, Eject, H1, H2, H3, Paragraph, PauseCircle, SlidersV, StepForward,
        VolumeSlash, SquareF, SquareG, SquareJ, SquareU, SquareV, Cauldron, FlaskPoison, HatSanta,
        KnifeKitchen, Mistletoe, Scarecrow, SortAlphaDownAlt, Tombstone, FileExclamation,
        FileImport, FileMinus, LandLayerLocation, PartyBell, SquareExclamation, TrashUndo,
        Cheeseburger, FishCooked, MugMarshmallows, Stroopwafel, WineBottle, ArrowAltSquareDown,
        AgeRestrictionSix, ArrowsRetweet, ChartCandlestick, Cubes, BowlChopsticksNoodles,
        DiagramCells, EarDeaf, UniversalAccess, YinYang, CircleF, CircleJ, CircleL, Pi, PlusMinus,
        Sigma, SortAlphaDown, Theta, ValueAbsolute, DialHigh, TrashList, TrashPlus, Clapperboard,
        SortNumericDownAlt, SolarPanelSun, Gramophone, Kazoo, PaintbrushPencil, PianoKeyboard,
        Piano, SquareDashed, Trumpet, WebcamSlash, CompassSlash, Icicles, PooBolt, TemperatureList,
        HandSparkles, PersonDolly, ComputerClassic, PrintSlash, Shovel, Ethernet, TrafficCone,
        PersonCircleMinus, ThermometerAlt, LightCeiling, Microwave, Oven, Pallet, Angle, Grate,
        Hose, Pump, ShoppingCartCheck, VrCardboard, FireHydrant, TimeWatchCalendar, TimeHalfPast,
        Sheep, TreeAlt, Worm, BrailleP, BrailleS, MeterFire, Meter, SimCards, HouseTsunami,
        MattressPillow, Tents, PersonSign, Scarf, UserHeadset, UserInjured, AppleCore, WheatAwn,
        BroomBall, CardDiamond, FirstMedal, HelmetBattle, Scroll, Staff, ThirdLaurel, ThirdMedal,
        Mango, BottleDroplet, CommentArrowDown, DiaryBookmarks, DiaryClasp, FeedbackAlt,
        FeedbackReview, JournalAlt, LiveAlt, RankingStars, Videoconference, ClearAlt, SwipeDown,
        Preview, BurgerGlass, BlogText, Squircle, MehRollingEyes, SquareMinus, PersonCircleXmark,
        TrafficLightGo, BoxOpenFull, CalendarDay, CalendarStar, CalendarXmark, HourglassStart,
        WatchSmart, Watch, BoxDollar, CalendarDays, CediSign, CruzeiroSign, GuaraniSign,
        HandHoldingBox, KipSign, ListDropdown, ModelCubeArrows, Nfc, PesoSign, ShopSlash, Signature,
        ScaleComparisonAlt, Browsers, FileBinary, Hdd, WindowRestore, CommentSmile,
        MessagesQuestion, Voicemail, FaceDrooling, FaceCowboyHat, FaceIcicles, FaceMask,
        FaceNauseated, FacePersevering, FaceSleepy, GroupArrowsRotate, GrinTongueSquint,
        MailboxFlagUp, CheckInCalendar, HeadSideMask, Hexagon, Left, SquareSmall, SquareStar,
        RewindButtonCircle, Waveform, SquareA, SquareB, SquareI, SquareO, SquareW, SquareX, Ghost,
        HandSpock, PlanetRinged, Scythe, Transporter3, Transporter6, UserAlien, UserVisor,
        DotCircle, GreaterThanEqual, GripVertical, LowVision, PiggyBankBudget, CookieAlt,
        ArrowDownFromArc, ChartRadar, CreditCardEye, DownLeft, UpLeft, ChalkboardUser, CircleE,
        CircleN, CircleX, DialLow, Dial, MessageArrowUp, TrashCheck, VectorPolygon, CameraRotate,
        Bee, ChartLineUp, CommentAltDots, GifSquare, ImagesUser, MusicNote, RectangleList, Cello,
        Splotch, TriangleMusic, Anchor, Campfire, FeatherPointed, LeafOak, SunDust,
        ThermometerQuarter, Angel, BoxHeart, HandHoldingWater, LeafHeart, ContainerStorage,
        DisplayArrowDown, DollyFlatbed, Flask, HouseNight, WrenchAlt, UserCheck, ClipboardCheck,
        HouseReturn, PersonCircleCheck, Toilet, LampFloor, Washer, FireFlameCurved, GrateDroplet,
        WindTurbine, ClockDesk, GlassWhiskeyRocks, ShieldSlash, MenuDotsVertical, KiwiBird,
        BrailleH, BrailleL, BrailleN, BrailleQ, BrailleW, FileChartPie, FloppyDisks, Manhole,
        SdCards, BagSeedling, FireBurner, MountainCity, PuzzlePieceIntegration, Deer, HorseHead,
        LessThanEqual, Build, InventoryAlt, QrScan, GunSquirt, HatCowboy, CommentAltCheck,
        LeftFromBracket, CupTogo, GlassEmpty, UserChef, CardClub, Dagger, FlyingDisc,
        CaretSquareLeft1, MaskSnorkel, SecondAward, SecondLaurel, CitrusSlice, GarlicAlt,
        MushroomAlt, Olive, Peanut, BowlScoops, Donut, JarAlt, PanFrying, PlateWheat, ShishKebab,
        Waffle, NewspaperOpen, Newspaper, TextBox, Leave, SwipeLeft, Tap, ConditionAlt,
        PriorityImportance, LinkHorizontalSlash, ShopLock, TablePicnic, TimeTwentyFour,
        TourGuidePeople, TrainTram, TreeDeciduous, VideoArrowUpRight, FileExport, Wifi1,
        HandsClapping, PeoplePants, SquareHeart, BurgerAlt, Api, License, MarsStrokeRight, Paste,
        ReflectVertical, RemoveFolder, SignOutAlt, StarAndCrescent, TriangleWarning, BarsStaggered,
        BasketShoppingMinus, BellNotificationCall, ChartMixedUpCircleDollar, ColonSign,
        FaceTongueMoney, FaceSadSweat, FrancSign, MugHotAlt, NfcTrash, PhoneFlip, Trademark,
        HorizontalRule, BallotCheck, MapMarkerSmile, MessageBot, PhonePlus, SpaceStationMoon,
        FaceAnguished, FaceAnxiousSweat, FaceDisappointed, FaceHandYawn, FaceSmirking, FaceVomit,
        FaceZany, FaceZipper, HandBackFist, GrowthChartInvest, HandsHolding, PeopleCarryBox,
        UserPen, AlignSlash, Banjo, CameraMovie, Clipboard, DrawPolygon, Mp3Player, PenSquare,
        SendBack, Strikethrough, VolumeMute, WaveformPath, SquareD, SquareK, SquareZ, FluxCapacitor,
        PlanetMoon, Raygun, SolarSystem, Transporter2, Transporter, UserAstronaut, CheckCircle,
        LightEmergency, PlusHexagon, StarExclamation, GlassChampagne, CartArrowDown, ChartBullet,
        CarCircleBolt, DiagramPredecessor, DiagramSubtask, Down, SortCircleUp, UpRight,
        WheelchairMove, CircleB, CircleS, CircleV, CircleXmark, TheaterMasks, Airplay, Command,
        TrashClock, BoltAuto, BoltSlash, DroneFront, HighDefinition, MoveToFolder2, GuitarElectric,
        Mandolin, MusicSlash, Radio, Saxophone, Scribble, CloudMeatball, FlowerDaffodil, SnowmanAlt,
        ThermometerFull, GlobeSnow, HomeHeart, Ribbon, UserCrown, BrailleA, BrailleD, SdCard,
        UserPilotTie, UserXmark, ScannerTouchscreen, SignalBarsFair, SortCircle, Vacuum, CarRear,
        Robot, PlaneSlash, TentArrowsDown, TransformerBolt, TruckFront, UserPolice, CowAlt,
        Elephant, Hippo, Lobster, Otter, BrailleI, BrailleM, BrailleT, BrailleU, BrailleY,
        MeterDroplet, Locust, MosquitoNet, Mosquito, Pickaxe, PlantWilt, Cat, SkullCow, Squirrel,
        Discover, HeartHalfStroke, ShovelSnow, Sunglasses, MapMarkerQuestion, TrashCanPlus,
        HandFist, GripDotsVertical, Medal, SwimmingPool, PineappleAlt, Custard, FlatbreadStuffed,
        JarWheat, SushiRoll, Invite, SquareUpRight, SwipeUp, Ux, InputText, Tally4, RestroomSimple,
        UserPilot, CaretSquareLeft, FolderXmark, HouseLaptop, LitecoinSign, MoneyFromBracket,
        NfcLock, NfcSlash, PesetaSign, VoteYea, BarsFilter, Notdef, CoinUpArrow, MessageText,
        MessageXmark, WalkieTalkie, DownToLine, FaceScream, FaceRaisedEyebrow, FaceNoseSteam,
        FaceSunglasses, FaceThermometer, HandLove, PersonPregnant, Reel, HeartHalf, ListTimeline,
        SquareBolt, BroadcastTower, Clarinet, ComputerSpeaker, FilmCanister, Heading,
        MicrophoneSlash, ObjectUngroup, ParagraphLeft, PenNib, PlayCircle, StopCircle, SquareE,
        SquareN, CandleHolder, HatWitch, PumpkinAlt, SkullCrossbones, Transporter5, Ufo,
        BatteryExclamation, CheckDouble, CaretQuareUp, Information, MinusCircle, MinusHexagon,
        RotateExclamation, ShoppingCartBuyer, DrumstickBite, GlassCitrus, ArrowCircleRight,
        ArrowUpFromGroundWater, BrightnessLow, HandshakeAngle, KeyboardBrightness, Octagon, Slash,
        Cactus, CircleA, CircleG, CircleP, CircleQ, CircleY, _360Degrees, CalendarBirhtdayCake,
        DeleteRight, StarRatingCall, TrashXmark, CircleCamera, CircleExclamationCheck,
        CircleMicrophone, CircleVideo, Drum, Flute, EarMuffs, Tape, ThermometerEmpty, Trees,
        FileUser, HandPaper, DiaryBookmarkDown, FaucetDrip, Digging, Forklift, TvRetro,
        ArtificialIntelligence, LocationArrow, PeopleArrowsLeftRight, UserShield, UsersSlash,
        Loveseat, ShippingFast, Siren, SortCircleDown, Blanket, LightbulbOn, TankWater,
        TruckMedical, WindowFrame, BorderStyleAlt, ShieldKeyhole, ShieldXmark, Crab, FishBones,
        Horse, Snake, TreesAlt, BrailleR, BloodTestTubeAlt, ComputerMouse, DesktopArrowDown,
        Pedestal, CloverAlt, TachometerAltSlowest, StarOfDavid, Bat, Turtle, Qr, BlockQuestion,
        HandsHeart, RingDiamond, CandyBar, GlassHalf, HouseChimneyWindow, CardHeart, CardSpade,
        NestingDolls, Third, Walking, MelonAlt, Peanuts, PointOfSaleSignal, GiftBoxBenefits,
        HoneyPot, SandwichAlt, AnswerAlt, Catalog, FeedbackHand, SortSizeUp, AdminAlt, Description,
        Refer, WineGlassEmpty, AddImage, PlugCable, PlugConnection, ModelCubeSpace,
        ComplianceDocument, Deposit, Revenue, Total, Boss, Completed, Hr, EmployeeMan, LeaderAlt,
        TabFolder, Department, HandBill, DurationAlt, Tuesday, CrmComputer, Crm, Assign, Employees,
        Percent20, Percent70, RoadSignLeft, Skin, InsertButtonCircle, PenFancySlash, PlaneArrival,
        TowerControl, ToDoAlt, Vest, WarehouseAlt, Sitemap, WifiSlash, HandLizard, Acorn,
        AppleCrate, CandyCane, Jug, AttributionPencil, Beacon, BlogPencil, DesktopWallpaper,
        Followcollection, IconStar, TextShadow, BookArrowUp, ArrowUpToArc, InputPipe, Escalator,
        PersonSeat, Snooze, BahtSign, CartMinus, FingerprintSecurityRisk, Inboxes, HandHoldingSkull,
        MessageArrowDown, NairaSign, NoteSticky, StoreSlash, VoteNay, BracketRound,
        HandsHoldingDiamond, AddressCard, HundredPoints, MessageSms, FaceAstonished, FaceConfounded,
        DialMedLow, FaceExplode, FaceHushed, CursorTextAlt, CommentAltMiddleTop, FaceThinking,
        HandBackPointDown, ClockTimeTracking, HandWave, PuzzleAlt, ThoughtBubble, TimeForwardSixty,
        UserGear, CircleHalf, CircleStar, ShareSquare, CameraRetro, Clone, Eraser, FileAudio,
        Outdent, Swatchbook, SquareY, Alien, BookDead, ClawMarks, Galaxy, HoodCloak, PortalExit,
        Stocking, Transporter1, TransporterEmpty, UserRobot, DiamondExclamation, FileZipper,
        FolderOpen, ParkingCircleSlash, ToggleOn, BowlChopsticks, CoffeeBean, GlassWhiskey,
        ChartWaterfall, ArrowAltFromBottom, PersonCircleExclamation, SkiBootSki, CircleH, CircleI,
        CircleT, CircleZ, SquarePollVertical, WaveSine, WaveSquare, DialMed, GripDots, NotFoundAlt,
        PenSwirl, TeamCheckAlt, ImageSlash, Guitars, RectanglesMixed, Mountain, Sailboat,
        TachometerAltSlow, Mercury, Neuter, Axe, ChatArrowGrow, Faucet, Flashlight,
        FireExtinguisher, Plug, Screwdriver, TabletAndroid, HandHoldingSeeding, Couch,
        DigitalTachograph, SoapAlt, TabletRugged, Shower, DumpsterFire, Moped, ShieldCross,
        VacuumRobot, ShieldMinus, ShowerDown, HorseSaddle, Monkey, BrailleX, BrailleZ,
        DisplayMedical, DisplaySlash, CalculatorMathTax, TorchInspirationLeader, Dragon, Narwhal,
        Rabbit, Whale, BootHeeled, Tshirt, CakeSlice, ArrowSquareDown, Badminton, GoalNet, QuizAlt,
        ScrollOld, Citrus, KiwiFruit, LeafyGreen, ArrowsToDottedLine, Butter, Flatbread, JugBottle,
        Pancakes, Popsicle, Answer, CatalogAlt, CatalogMagazine, InviteAlt, MeetingAlt, Rank,
        RankingPodium, WishlistHeart, WishlistStar, ArrowProgress, Mode, CodePullRequestDraft,
        DirectionSignal, BookCircleArrowRight, Chatbot, SquarePhoneHangup, Investment, Sunday,
        PhotoCapture, Method, Percent90, Restock, Customize, HexagonDivide, ToriiGate, BarberPole,
        PigBankBulb, TruckBox, PasswordAlt, Dinner, Mix, Banner3, CurveAlt, Nose, Picking, QueueAlt,
        Multiple, OvalAlt, Oval, RotateSquare, DominoEffect, Insight, MapMarkerSlash, Age, Trust,
        PickingBox, BenefitDiamond, LightbulbCfl, BrakeWarning, TruckFire, ArrowTurnLeft, Mp3File,
        Mp4File, PptFile, LaptopArrowDown, Free, DisplayChartUp, HouseFire, PreviousSquare,
        SurveyXmark, ThreeLeafClover, TentArrowTurnLeft, PersonCirclePlus, MapMarkerCheck,
        HouseCircleCheck, HouseChimneyUser, FaceGrinTongueWink, DiagramLeanCanvas,
        CircleWaveformLines, ArrowFromRight, ArrowAltSquareLeft, SafeBox, ComplianceClipboard,
        Auction, LeadershipAlt, CarsCrash, Track, OrganizationChart, SalaryAlt, MoveToFolder,
        NetworkAnalytic, CheapDollar, Percent40, Sell, Supplier, Customization, Floor, OctagonMinus,
        OctagonXmark, PrayingHands, SquareDivide, Seal, Svg, AdPaid, BonusStar, Channel,
        TransformationDesign, AgeAlt, Life, SkillAlt, ArrowUpRightAndArrowDownLeftFromCenter,
        LimitHand, Dropdown, PointerText, PlugCircleMinus, ShieldDog, SpringCalendar,
        PlantSeedInvest, MoneyWings, RectangleVerticalHistory, SignPosts, PlayMicrophone,
        CompassSouth, TrophyAchievementSkill, SunSalutationYoga, MoneyTransferSmartphone,
        HeadSideCoughSlash, PasswordComputer, UiUx, GroceryBag, TransformationShapes, Pending,
        InfoGuide, ArrowUpRightFromSquare, ExpandArrowsAlt, PhotoFilmMusic, ClockTwoThirty,
        PlantCare, PlantGrowth, ScrewAlt, HatBeach, Joker, BracketSquareRight, MusicNoteSlash,
        PersonDressSimple, UnderConstruction, LionHead, Pollution, CvvCard, SpaceStationMoonAlt,
        VideoArrowDownLeft, UpFromBracket, TruckArrowRight, TentArrowDownToLine,
        SquarePollHorizontal, PersonDollyEmpty, ClockElevenThirty, ChartScatter3d,
        ChartPieSimpleCircleDollar, ArrowDownSmallBig, ArrowAltSquareUp, ArrowAltFromTop,
        ArrowAltCircleDown, PigFace, SourceData, CalculatorMoney, Challenge, Compliance,
        GovernmentFlag, EmployeeAlt, BorderCenterH, DriverWoman, Rent, TrainStation, Fail,
        LeaderboardAlt, UserSalary, Percent10, Percent25, Drawer, Ankh, GreaterThan, PenClipSlash,
        Analyse, BenefitPorcent, FeeReceipt, Module, MoneyBillsSimple, Spy, GuideAlt, RulesAlt,
        Skill, Blood, LocationDotSlash, GovernmentBudget, IotAlt, Screw, Referral, GreekHelmet,
        GolfHole, HorseshoeBroken, SystemCloud, RoadBarrier, HandshakeTrust, MoneySimpleFromBracket,
        BeerMugEmpty, SunPlantWilt, Treadmill, BasketShoppingSimple, CatHead, EndlessLoop,
        AgeRestrictionThree, HouseCrackAlt, HouseCircleXmark, Replay10, SpainMap,
        WheatAwnCircleExclamation, TrashUndoAlt, TrashCanCheck, HouseChimneyCrack, HeadSideHeart,
        ForeignLanguageAudio, FloppyDiskPen, DocumentCircleWrong, BangladeshiTakaSign, PuzzlePieces,
        AuditAlt, Audit, CarJourney, Blockchain3, CheapBill, Percent30, Percent60, SupplierAlt,
        LessThan, Omega, ExpenseBill, LawyerMan, Onboarding, SpeedometerKpi, Banner4,
        TransformationCircle, ArrowComparison, PersonCv, Snap, LessonClass, KissWinkHeart,
        StudentAlt, BadgetCheckAlt, ArrowTurnDownRight, CareerGrowth, LeadFunnel, Mortgage,
        RevenueEuro, PersonWalkingWithCane, Roulette, TruckUtensils, ArrowsSplitUpAndLeft,
        ArrowDownToDottedLine, Damage, AgeRestrictionTwentyOne, Replay30, CompassEast,
        WineGlassCrack, TrianglePersonDigging, PrintMagnifyingGlass, Condition, GalaxyStar,
        LightbulbSetting, RefundAlt, HrGroup, CustomerService, SeatbeltSafetyDriver, Brand,
        Saturday, CheapStack, ClipboardExclamation, Percent100, Selling, Warranty,
        CustomizeComputer, BookHeart, TruckCheck, DocumentPaid, QueueLine, TipCoin, PeopleRoof,
        MapMarkerPlus, Muscle, PaperPlaneTop, MemberSearch, ProgressUpload, AnatomicalHeart,
        DumbbellWeightlifting, InboxFull, MailboxEnvelope, ThunderstormRisk, Lion, HouseFlag,
        RectangleHistoryCirclePlus, SendMoney, SofaSize, Workshop, LawyerWoman, PaymentPos,
        ConvertDocument, MembershipVip, PlanStrategy, RecipeBook, MultipleAlt, Effect,
        HighFiveCelebrationYes, HandPointRibbon, FaceSmileHorns, LeadManagement, Desk, RunningTrack,
        DistributeSpacingVertical, CowbellCirclePlus, TrashRestoreAlt, BioLeaves, Waste,
        ArrowFromBottom, SummaryCheck, PostalAddress, CodePullRequest, ErrorCamera,
        ClockThreeThirty, CompassWest, WorkInProgress, TrashCanSlash, TrashCanList,
        ReflectHorizontalAlt, ClockTenThirty, CircleMicrophoneLines, ChartMixedUpCircleCurrency,
        BellSchoolSlash, BalanceScaleRight, ArrowsSplitRightAndLeft, ArrowAltCircleRight,
        StarCommentAlt, RegistrationPaper, DriverMan, RiskAlt, AssessmentAlt, Duration,
        SpeedometerArrow, Debt, Percent75, Percent80, Intersection, Om, WomanScientist,
        MarketplaceStore, Marketplace, Banner5, CurveArrow, SmartHome, UserCoach, UserTrust,
        ChoirSinging, DumbbellFitness, Excavator, DogLeashed, PawHeart, TurnRight, CardinalCompass,
        CompassNorth, SleepingBag, SpiderBlackWidow, SortShapesUp, SortAlphaUp, SendMoneySmartphone,
        RadarMonitoringTrack, OperatingSystemUpgrade, HandBackPointRight, GroupCommunitySocialMedia,
        _404, NotFound, Payroll, WorkflowSettingAlt, StageTheatre, OctagonPlus, SoldSignal,
        ReservationSmartphone, ReservationTable, Bonus, Kpi, PersonSeatReclined, MilkAlt, Recipe,
        TransformationBlock, TogetherPeople, Introduction, SkillUser, StoryBook, MapMarkerMinus,
        Iot, Scooter, ImproveUser, TalentHand, DropdownSelect, ArrowFromTop, BrokenChainLinkWrong,
        GlobePointer, MovFile, JumpingRope, WastePollution, Swap, ClipboardQuestion, FuelGauge,
        GpsNavigation, HeartHealthMuscle, Lighthouse, TrainTrack, StopSquare, SubtitlesSlash,
        ChecklistTaskBudget, AssistiveListeningSystems, ArrowAltSquareRight, ChallengeAlt,
        DepositAlt, Tax, Monday, Thursday, MoneyBillSimple, IssueLoupe, Percent50, BoothCurtain,
        DrawerAlt, StageConcert, Bible, Chalkboard, EmptySet, Lambda, HairClipper, PasswordEmail,
        Fee, KpiEvaluation, NoFee, Paid, Membership, Seller, GroceryBasket, InsertArrows, Insert,
        PersonShelter, SkinHair, StoreBuyer, HockeyStickPuck, Meditation, RegionPinAlt,
        PointerLoading, BalletDance, BadgeLeaf, Bio, ShieldCat, LoopSquare, PodiumVictoryLeader,
        LastSquare, SpaghettiMonsterFlying, PlugCircleExclamation, HouseCircleExclamation,
        ExternalHardDrive, UserKey, PlateUtensils, UtensilsSlash, Banner2, Curve,
        AgeRestrictionEighteen, BookPlus, FunctionSquare, StoryFantasy, SkinDrop, BracketCurlyRight,
        ConveyorBeltArm, LeaderSpeech, TirePressureWarning, WalletBuyer, EmployeeHandbook,
        KeySkeletonLeftRight, BenefitHand, Benefit, BonusAlt, Webhook, MemberList, RadioButton,
        DashboardMonitor, AudienceMegaphone, CommentsQuestionCheck, AirPollution, TurnLeft,
        CloudBackUp, HouseLock, BlockMicrophone, Replay5, ClockSixThirty, TruckArrowLeft,
        TrafficLightSlow, TachometerAltFastest, StarSharpHalfStroke, ClockEightThirty,
        CalendarPaymentLoan, BuildingCircleArrowRight, BriefcaseArrowRight, ArrowUpToDottedLine,
        ArrowUpFromDottedLine, ArrowFromLeft, ArrowAltCircleLeft, WorkflowAlt, GalaxyPlanet,
        MatchFire, PlugAlt, RevenueAlt, ToDo, Legal, Loan, StateCountry, Expense, LeaderboardTrophy,
        DailyCalendar, Wednesday, CrmAlt, PayrollCalendar, FloorLayer, Tie, CircleDivide, Hamsa,
        UsersClass, MosqueMoon, LockHashtag, Milk, InsertAlt, Queue, ModelCube, Rules,
        AgeRestrictionSixteen, FaceSmileHalo, MouseField, BackUp, RoboticArm, BenefitIncrease,
        TalentAlt, IndianRupeeSign, DumbbellRay, TruckLadder, IpAddress, BookOpenReader, Burst,
        FolderFire, MapPoint, PersonLuggage, UniformMartialArts, TrainSubwayTunnel,
        DistributeSpacingHorizontal, WorkflowSetting, Workflow, Bucket, FlyInsect, LandLocation,
        IncenseSticksYoga, ArrowTrendDown, Overview, Choose, Features, Journey, TrainJourney,
        Branding, InsightHead, Leaderboard, CorporateAlt, Corporate, ProblemSolving, Shirt, Sofa,
        ArrowToLeft, OctagonCheck, MosqueAlt, MarketplaceAlt, PadlockCheck, SellerStore, GraphCurve,
        InsertSquare, QueueSignal, TargetAudience, InsightAlt, Lesson, CircleOverlap,
        ArrowLeftFromArc, SkeletonRibs, SpartanHelmet, Horseshoe, RecycleBin, ShieldTrust,
        CourtSport, EmailPending, FlowerButterfly, ChartKanban, ClipoardWrong, PauseSquare,
        Tricycle, BloodDropper, FloppyDiskCircleXmark, FaceSmileUpsideDown, CommentArrowUpRight,
        ArrowDownFromDottedLine, AngleDoubleSmallLeft, AgeRestrictionTwelve, PriorityArrows,
        ExternalWorld, Massage, ChooseAlt, Selection, Accident, RentSignal, WalletArrow,
        VideoDuration, Blueprint, CustomizeEdit, Handmade, Divide, Gopuram, Kaaba, ManScientist,
        Practice, Script, UserGraduate, RazorBarber, Booking, PlugCircleBolt, HashtagLock,
        PasswordSmartphone, AgeRestrictionSeven, Cryptocurrency, TrustAlt, Student, Lead, Raccoon,
        ReferralAlt, Chip, BellNotificationSocialMedia, LaptopBinary, ProgressComplete, WebDesign,
        DownLeftAndUpRightToCenter, StationaryBike, CalendarCall, GroupCall, PhoneGuide, Wave,
        CircleNodes, OrderHistory, Resume, CarTunnel, SurveillanceCamera, TrainStationBuilding,
        ToiletPaperUnderSlash, TentArrowLeftRight, SquareDashedCirclePlus, PersonCircleQuestion,
        MoneyTransferCoinArrow, ChartSimpleHorizontal, Stage, SunglassesAlt, Equals,
        FaceHeadBandage, Mosque, Synagogue, Vihara, AnalyseAlt, HandHoldingHeart, ArrowProgressAlt,
        SortSizeDown, Visit, DotPending, LightbulbHead, GrinTongueWink, IntroductionHandshake,
        Function, DollyFlatbedEmpty, MessageArrowUpRight, CareerPath, ReferralUser, ShirtTankTop,
        CreditCardBuyer, FlaskGear, SlotMachine, ProgressDownload, Branching, ResistanceBand,
        RotateReverse, CryptoCalendar, FreeDelivery, PayrollCheck, FloppyDiskCircleArrowRight,
        WhiteSpace, CompassAlt, WheatAwnSlash, UserSkillGear, UserHelmetSafety, SortAmountUpAlt,
        SortAmountUp, ShareAltSquare, KeyboardBrightnessLow, HouseChimneyMedical,
        HeartPartnerHandshake, FaceBeamHandOverMouth, ClosedCaptioningSlash,
        ChartPieSimpleCircleCurrency, Refund, BuildingNgo, GovernmentUser, Leader, AirplaneJourney,
        Assessment, BillArrow, CalendarSalary, DepartmentStructure, LimitSpeedometer, Plan, Cheap,
        Knitting, Church, ScaleComparison, Banner, Cv, ExchangeCryptocurrency, ConvertShapes,
        SourceDocument, SkinArrow, BinBottles, MeasuringTape, General, Talent, DashboardPanel,
        ToiletsPortable, FileCloud, WindowFrameOpen, TachometerAltAverage, SourceDocumentAlt,
        SignalBarsWeak).sortedBy { it.name }
    return __Outline!!
  }
